Repository PHP-CS-Fixer/PHP-CS-Fixer, pull requests merged in 2018-03, with the labels that each got.

#3574 GeneralPhpdocAnnotationRemoveFixer - remove PHPDoc if no content is left
  src/Fixer/Phpdoc/GeneralPhpdocAnnotationRemoveFixer.php
  tests/Fixer/Phpdoc/GeneralPhpdocAnnotationRemoveFixerTest.php
Labels: bug

#3576 Fix Doctrine Annotation test cases merging
  tests/Fixer/DoctrineAnnotation/DoctrineAnnotationBracesFixerTest.php
  tests/Fixer/DoctrineAnnotation/DoctrineAnnotationIndentationFixerTest.php
  tests/Fixer/DoctrineAnnotation/DoctrineAnnotationSpacesFixerTest.php
Labels: tests / CI

#3577 DoctrineAnnotationArrayAssignmentFixer - Add test case
  tests/Fixer/DoctrineAnnotation/DoctrineAnnotationArrayAssignmentFixerTest.php
Labels: tests / CI

#3594 ElseifFixer - Bug with alternative syntax
  src/Fixer/ControlStructure/ElseifFixer.php
  tests/Fixer/ControlStructure/ElseifFixerTest.php
Labels: bug

#3135 Add ArrayIndentationFixer
  .php_cs.dist
  README.rst
  src/Fixer/PhpUnit/PhpUnitTestAnnotationFixer.php
  src/Fixer/Whitespace/ArrayIndentationFixer.php
  tests/AutoReview/FixerFactoryTest.php
  tests/Console/ConfigurationResolverTest.php
  tests/Fixer/Alias/BacktickToShellExecFixerTest.php
  tests/Fixer/Basic/BracesFixerTest.php
  tests/Fixer/ClassNotation/ClassAttributesSeparationFixerTest.php
  tests/Fixer/Comment/MultilineCommentOpeningClosingFixerTest.php
  tests/Fixer/ControlStructure/IncludeFixerTest.php
  tests/Fixer/ControlStructure/YodaStyleFixerTest.php
  tests/Fixer/PhpUnit/PhpUnitNoExpectationAnnotationFixerTest.php
  tests/Fixer/Phpdoc/PhpdocTrimFixerTest.php
  tests/Fixer/StringNotation/EscapeImplicitBackslashesFixerTest.php
  tests/Fixer/StringNotation/ExplicitStringVariableFixerTest.php
  tests/Fixer/StringNotation/SingleQuoteFixerTest.php
  tests/Fixer/Whitespace/ArrayIndentationFixerTest.php
  tests/Fixer/Whitespace/MethodChainingIndentationFixerTest.php
  tests/Fixtures/Integration/priority/array_indentation,braces.test
  tests/Tokenizer/TokensAnalyzerTest.php
Labels: feature

#3616 FixerFactoryTest - Don't rely on autovivification
  tests/AutoReview/FixerFactoryTest.php
Labels: RTM, tests / CI

#3615 Detect fabbot.io
  .php_cs.dist
Labels: RTM, tests / CI

#3477 PhpUnitStrictFixer: handle static calls
  src/Fixer/PhpUnit/PhpUnitStrictFixer.php
  tests/Fixer/PhpUnit/PhpUnitStrictFixerTest.php
Labels: feature

#3479 PhpUnitConstructFixer: handle static calls
  src/Fixer/PhpUnit/PhpUnitConstructFixer.php
  tests/Fixer/PhpUnit/PhpUnitConstructFixerTest.php
Labels: feature

#3344 Fix method chaining indentation in HTML
  src/Fixer/Whitespace/MethodChainingIndentationFixer.php
  tests/Fixer/Whitespace/MethodChainingIndentationFixerTest.php
Labels: bug

#3545 Add the 'none' sort algorithm to OrderedImportsFixer
  README.rst
  src/Fixer/Import/OrderedImportsFixer.php
  tests/Fixer/Import/OrderedImportsFixerTest.php
Labels: feature

#3632 DateTimeImmutableFixer bug with adding tokens while iterating over them
  src/Fixer/ClassUsage/DateTimeImmutableFixer.php
  tests/Fixer/ClassUsage/DateTimeImmutableFixerTest.php
Labels: bug
