Repository PHP-CS-Fixer/PHP-CS-Fixer, pull requests merged in 2018-10, with the labels that each got.

#3977 NoSuperfluousPhpdocTagsFixer - Fix handling of description with variable
  src/Fixer/Phpdoc/NoSuperfluousPhpdocTagsFixer.php
  tests/Fixer/Phpdoc/NoSuperfluousPhpdocTagsFixerTest.php
Labels: RTM, annotation, bug

#4016 Bump console component due to it's bug
  composer.json
Labels: RTM, bug

#4028 PhpdocNoEmptyReturnFixer - handle single line PHPDoc
  src/Fixer/Phpdoc/PhpdocNoEmptyReturnFixer.php
  tests/Fixer/Phpdoc/PhpdocNoEmptyReturnFixerTest.php
Labels: RTM, bug

#4034 PhpUnitTestCaseIndicator - handle anonymous class
  src/Indicator/PhpUnitTestCaseIndicator.php
  tests/Indicator/PhpUnitTestCaseIndicatorTest.php
Labels: bug

#4037 NativeFunctionInvocationFixer - fix function detection
  src/Fixer/FunctionNotation/NativeFunctionInvocationFixer.php
  tests/Fixer/FunctionNotation/NativeFunctionInvocationFixerTest.php
Labels: bug

#4030 Add get_required_files and user_error aliases
  src/Fixer/Alias/NoAliasFunctionsFixer.php
Labels: RTM, feature

#4025 Add phpdoc_types_order rule to Symfony's ruleset
  README.rst
  src/RuleSet.php
Labels: RTM, enhancement

#4031 Correct FixerOptionBuilder::getOption return type
  src/FixerConfiguration/FixerOptionBuilder.php
Labels: enhancement

#3778 DX: Throw an exception if FileReader::read fails
  src/FileReader.php
  src/Runner/FileFilterIterator.php
  tests/FileReaderTest.php
Labels: RTM, cleanup, enhancement

#4002 NoSuperfluousPhpdocTagsFixer - Allow `mixed` in superfluous PHPDoc by configuration
  README.rst
  src/Fixer/Phpdoc/NoSuperfluousPhpdocTagsFixer.php
  tests/Fixer/Phpdoc/NoSuperfluousPhpdocTagsFixerTest.php
Labels: feature
