Repository PHP-CS-Fixer/PHP-CS-Fixer, pull requests merged in 2018-11, with the labels that each got.

#4091 Adjust misleading sentence in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#4092 UseTransformer - simplify/optimize
  src/Tokenizer/Transformer/UseTransformer.php
  tests/Tokenizer/Transformer/UseTransformerTest.php
Labels: enhancement

#4077 DX: cleanup - NoAliasFunctionsFixer - use FunctionsAnalyzer
  src/Fixer/Alias/NoAliasFunctionsFixer.php
Labels: cleanup

#4069 DX: Add dev-tools directory to gitattributes as export-ignore
  .gitattributes
Labels: cleanup

#4097 DX: namespace casing
  tests/AutoReview/ComposerTest.php
  tests/AutoReview/TransformerTest.php
  tests/Tokenizer/Generator/NamespacedStringTokenGeneratorTest.php
  tests/Tokenizer/Resolver/TypeShortNameResolverTest.php
Labels: RTM

#4084 MethodChainingIndentation - fix priority with Braces
  src/Fixer/Whitespace/MethodChainingIndentationFixer.php
  tests/AutoReview/FixerFactoryTest.php
  tests/Fixtures/Integration/priority/braces,method_chaining_indentation.test
Labels: bug

#4088 Add Travis test with strict types
  .travis.yml
  src/Fixer/Phpdoc/PhpdocAnnotationWithoutDotFixer.php
Labels: RTM, tests / CI

#4115 Changes for upcoming Travis' infra migration
  .travis.yml
Labels: RTM, tests / CI

#3774 PhpUnitTestClassRequiresCoversFixer - Remove unneeded loop and use phpunit indicator class
  src/Fixer/PhpUnit/PhpUnitTestClassRequiresCoversFixer.php
Labels: cleanup

#3974 Psr4Fixer - class with anonymous class
  src/Fixer/Basic/Psr4Fixer.php
  tests/Fixer/Basic/Psr4FixerTest.php
Labels: bug

#4071 DX: do not insert Token when calling removeLeadingWhitespace/removeTrailingWhitespace from Tokens
  src/Tokenizer/Tokens.php
  tests/Tokenizer/TokensTest.php
Labels: enhancement

#4073 IsNullFixer - fix function detection
  src/Fixer/LanguageConstruct/IsNullFixer.php
  tests/Fixer/LanguageConstruct/IsNullFixerTest.php
Labels: bug

#4107 Preg::split - fix for non-UTF8 subject
  src/Preg.php
  tests/Differ/DiffConsoleFormatterTest.php
  tests/PregTest.php
Labels: bug

#4116 OrderedImportsFixer - fix sorting without any grouping
  src/Fixer/Import/OrderedImportsFixer.php
  tests/Fixer/Import/OrderedImportsFixerTest.php
  tests/Fixtures/Integration/misc/PHP7.test
Labels: bug

#4096 DX: fixing typo
  src/Fixer/FunctionNotation/ImplodeCallFixer.php
Labels: cleanup

#4099 HeaderCommentFixer - throw exception on invalid header configuration
  src/Fixer/Comment/HeaderCommentFixer.php
  tests/Fixer/Comment/HeaderCommentFixerTest.php
Labels: bug

#4122 DX: AppVeyor - Update Composer download link
  .appveyor.yml
Labels: tests / CI

#4070 Docs: Add link to a VS Code extension in readme
  README.rst
  src/Console/Command/ReadmeCommand.php
Labels: documentation

#4047 Token - inline $other->getPrototype() to speedup equals()
  src/Tokenizer/Token.php
Labels: enhancement

#3968 SelfAccessorFixer - support FQCN
  src/Fixer/ClassNotation/SelfAccessorFixer.php
  tests/Fixer/ClassNotation/SelfAccessorFixerTest.php
Labels: bug

#3987 Run HeaderCommentFixer after NoBlankLinesAfterPhpdocFixer
  src/Fixer/Comment/HeaderCommentFixer.php
  tests/AutoReview/FixerFactoryTest.php
  tests/Fixtures/Integration/priority/no_blank_lines_after_phpdoc,header_comment.test
Labels: bug

#4046 Token - Added fast isset() path to token->equals()
  src/Tokenizer/Token.php
Labels: enhancement

#4048 Tokens - inlined extractTokenKind() call on the hot path
  src/Tokenizer/Tokens.php
Labels: enhancement

#3436 Add a handful of integration tests
  tests/AutoReview/FixerFactoryTest.php
  tests/Fixtures/Integration/priority/class_attributes_separation,braces.test
  tests/Fixtures/Integration/priority/no_empty_statement,multiline_whitespace_before_semicolons.test
Labels: RTM, enhancement, tests / CI

#4036 ExplicitStringVariableFixer - fixes for backticks and for 2 variables next to each other
  src/Fixer/StringNotation/ExplicitStringVariableFixer.php
  tests/AutoReview/FixerFactoryTest.php
  tests/Fixer/StringNotation/ExplicitStringVariableFixerTest.php
  tests/Fixtures/Integration/priority/backtick_to_shell_exec,explicit_string_variable.test
Labels: RTM, bug

#4100 PhpdocAddMissingParamAnnotationFixer - Handle variable number of arguments and pass by reference cases
  src/Fixer/Phpdoc/PhpdocAddMissingParamAnnotationFixer.php
  tests/Fixer/Phpdoc/PhpdocAddMissingParamAnnotationFixerTest.php
Labels: bug
