Repository PHP-CS-Fixer/PHP-CS-Fixer, pull requests merged in 2018-06, with the labels that each got.

#3803 NoEmptyPhpdocFixer/PhpdocAddMissingParamAnnotationFixer - missing priority test
  src/Fixer/Phpdoc/PhpdocAddMissingParamAnnotationFixer.php
  src/Fixer/Phpdoc/PhpdocNoAliasTagFixer.php
  src/Fixer/Phpdoc/PhpdocNoEmptyReturnFixer.php
  tests/AutoReview/FixerFactoryTest.php
  tests/Fixtures/Integration/priority/no_empty_phpdoc,phpdoc_add_missing_param_annotation.test
Labels: tests / CI

#3797 DX: ProjectCodeTest - shall not depends on xdebug/phpdbg anymore
  tests/AutoReview/ProjectCodeTest.php
Labels: tests / CI

#3801 NativeFunctionInvocationFixe - fix buggy config validation
  src/Fixer/FunctionNotation/NativeFunctionInvocationFixer.php
  tests/Fixer/FunctionNotation/NativeFunctionInvocationFixerTest.php
Labels: bug

#3640 Add PhpdocToReturnTypeFixer
  README.rst
  src/Fixer/FunctionNotation/PhpdocToReturnTypeFixer.php
  tests/AutoReview/FixerFactoryTest.php
  tests/Fixer/FunctionNotation/PhpdocToReturnTypeFixerTest.php
  tests/Fixtures/Integration/misc/void_return,phpdoc_to_return_type.test
  tests/Fixtures/Integration/priority/fully_qualified_strict_types,phpdoc_to_return_type.test
  tests/Fixtures/Integration/priority/phpdoc_to_return_type,phpdoc_scalar.test
  tests/Fixtures/Integration/priority/return_type_declaration,phpdoc_to_return_type.test
Labels: feature

#3804 Cleanup: remove useless constructor comment
  src/Console/ConfigurationResolver.php
Labels: RTM, cleanup

#3805 Cleanup: add missing @param type
  tests/Tokenizer/Generator/NamespacedStringTokenGeneratorTest.php
Labels: cleanup

#3800 Symfony:risky ruleset: include set_type_to_cast rule
  README.rst
  src/RuleSet.php
Labels: enhancement

#3785 PhpUnitDedicateAssertFixer - fix to assertCount too
  src/Fixer/PhpUnit/PhpUnitDedicateAssertFixer.php
  tests/Fixer/PhpUnit/PhpUnitDedicateAssertFixerTest.php
Labels: feature

#3524 MethodArgumentSpaceFixer - Add ensure_single_line option
  .php_cs.dist
  README.rst
  src/Fixer/FunctionNotation/MethodArgumentSpaceFixer.php
  src/RuleSet.php
  tests/Fixer/FunctionNotation/MethodArgumentSpaceFixerTest.php
  tests/RuleSetTest.php
Labels: feature

#3127 Add NativeConstantInvocationFixer
  .travis.yml
  README.rst
  src/Cache/Directory.php
  src/Console/Command/DescribeCommand.php
  src/Console/ConfigurationResolver.php
  src/Fixer/Basic/NonPrintableCharacterFixer.php
  src/Fixer/ClassNotation/VisibilityRequiredFixer.php
  src/Fixer/ConstantNotation/NativeConstantInvocationFixer.php
  src/Fixer/FunctionNotation/PhpdocToReturnTypeFixer.php
  src/Fixer/FunctionNotation/ReturnTypeDeclarationFixer.php
  src/Fixer/FunctionNotation/VoidReturnFixer.php
  src/Fixer/Import/FullyQualifiedStrictTypesFixer.php
  src/Fixer/Import/NoUnusedImportsFixer.php
  src/Fixer/LanguageConstruct/ExplicitIndirectVariableFixer.php
  src/Fixer/ListNotation/ListSyntaxFixer.php
  src/Fixer/Operator/TernaryToNullCoalescingFixer.php
  src/Fixer/Strict/DeclareStrictTypesFixer.php
  src/Fixer/Whitespace/CompactNullableTypehintFixer.php
  src/Linter/ProcessLinter.php
  src/RuleSet.php
  src/Tokenizer/Analyzer/Analysis/NamespaceUseAnalysis.php
  src/Tokenizer/Analyzer/NamespaceUsesAnalyzer.php
  src/Tokenizer/Transformer/CurlyBraceTransformer.php
  src/Tokenizer/Transformer/SquareBraceTransformer.php
  src/Tokenizer/Transformers.php
  tests/AutoReview/FixerTest.php
  tests/AutoReview/ProjectCodeTest.php
  tests/Cache/DirectoryTest.php
  tests/Console/ConfigurationResolverTest.php
  tests/Fixer/ConstantNotation/NativeConstantInvocationFixerTest.php
  tests/Fixer/FunctionNotation/PhpdocToReturnTypeFixerTest.php
  tests/FixerDefinition/VersionSpecificCodeSampleTest.php
  tests/FixerDefinition/VersionSpecificationTest.php
  tests/IntegrationTest.php
  tests/Runner/RunnerTest.php
  tests/Smoke/StdinTest.php
  tests/Test/AbstractIntegrationCaseFactory.php
  tests/Test/AbstractIntegrationTestCase.php
  tests/Test/InternalIntegrationCaseFactory.php
  tests/Tokenizer/Analyzer/Analysis/NamespaceUseAnalysisTest.php
  tests/Tokenizer/Analyzer/NamespaceUsesAnalyzerTest.php
Labels: feature

#3808 LowercaseStaticReferenceFixer - Fix constants handling
  src/Fixer/Casing/LowercaseStaticReferenceFixer.php
  tests/Fixer/Casing/LowercaseStaticReferenceFixerTest.php
Labels: bug

#3815 NoSuperfluousPhpdocTagsFixer - support array/callable type hints
  src/Fixer/Phpdoc/NoSuperfluousPhpdocTagsFixer.php
  tests/Fixer/Phpdoc/NoSuperfluousPhpdocTagsFixerTest.php
Labels: bug

#3829 Fix typos in changelog
  CHANGELOG.md
Labels: RTM
