Repository PHP-CS-Fixer/PHP-CS-Fixer, pull requests merged in 2018-05, with the labels that each got.

#3723 Extend tests coverage
  src/Cache/Cache.php
  src/Doctrine/Annotation/Tokens.php
  tests/AutoReview/ProjectCodeTest.php
  tests/Cache/CacheTest.php
  tests/Console/WarningsDetectorTest.php
  tests/FileReaderTest.php
  tests/FileRemovalTest.php
  tests/FixerFactoryTest.php
  tests/Fixtures/FixCommand/TextDiffTestInput.php
  tests/Fixtures/Integration/misc/class_definition,no_trailing_whitespace.test
  tests/Fixtures/Test/FileReaderTest/StdinFakeStream.php
  tests/Linter/CachingLinterTest.php
  tests/StdinFileInfoTest.php
  tests/Tokenizer/CTTest.php
  tests/UtilsTest.php
Labels: tests / CI

#3724 BlankLineBeforeStatementFixer - Add case and default as options
  src/Fixer/Whitespace/BlankLineBeforeStatementFixer.php
  tests/AutoReview/FixerFactoryTest.php
  tests/Fixer/Whitespace/BlankLineBeforeStatementFixerTest.php
  tests/Fixtures/Integration/priority/no_extra_blank_lines,blank_line_before_statement.test
Labels: feature

#3445 Rewrite NoUnusedImportsFixer
  src/Fixer/Import/NoUnusedImportsFixer.php
  tests/Fixer/Import/NoUnusedImportsFixerTest.php
  tests/Fixtures/Integration/misc/PHP7.test
Labels: bug, refactoring

#3668 Rewrite NoUnusedImportsFixer
  src/Fixer/Import/NoUnusedImportsFixer.php
  src/Fixer/PhpUnit/PhpUnitOrderedCoversFixer.php
  src/Tokenizer/Analyzer/Analysis/NamespaceAnalysis.php
  src/Tokenizer/Analyzer/NamespaceUsesAnalyzer.php
  src/Tokenizer/Analyzer/NamespacesAnalyzer.php
  src/Tokenizer/Resolver/TypeShortNameResolver.php
  tests/Fixer/Import/NoUnusedImportsFixerTest.php
  tests/Fixtures/Integration/misc/PHP7.test
  tests/Tokenizer/Analyzer/Analysis/NamespaceAnalysisTest.php
  tests/Tokenizer/Analyzer/NamespaceUsesAnalyzerTest.php
  tests/Tokenizer/Analyzer/NamespacesAnalyzerTest.php
Labels: bug, refactoring

#3233 PhpdocAlignFixer - Fix linebreak inconsistency
  src/Fixer/Phpdoc/PhpdocAlignFixer.php
  tests/Fixer/Phpdoc/PhpdocAlignFixerTest.php
Labels: RTM, bug

#3656 DX: Clean ups
  tests/AutoReview/ComposerTest.php
  tests/AutoReview/FixerFactoryTest.php
  tests/Fixtures/Integration/priority/phpdoc_no_empty_return,phpdoc_trim.test
  tests/Fixtures/Integration/priority/phpdoc_no_package,phpdoc_trim.test
  tests/Fixtures/Integration/priority/unary_operator_spaces,not_operator_with_space.test
  tests/Fixtures/Integration/priority/unary_operator_spaces,not_operator_with_successor_space.test
  tests/IntegrationTest.php
  tests/Smoke/CiIntegrationTest.php
  tests/Test/AbstractIntegrationTestCase.php
Labels: cleanup

#3658 DX: Clean ups
  src/Fixer/Alias/BacktickToShellExecFixer.php
  src/Fixer/ClassUsage/DateTimeImmutableFixer.php
  src/Fixer/StringNotation/EscapeImplicitBackslashesFixer.php
  src/Indicator/PhpUnitTestCaseIndicator.php
  src/Tokenizer/Analyzer/Analysis/TypeAnalysis.php
  tests/AutoReview/ProjectCodeTest.php
  tests/Fixer/ClassNotation/OrderedClassElementsFixerTest.php
  tests/Fixtures/Integration/priority/standardize_not_equals,binary_operator_spaces.test
  tests/Indicator/PhpUnitTestCaseIndicatorTest.php
Labels: bug, cleanup, tests / CI

#3534 MultilineWhitespaceBeforeSemicolonsFixer - support static calls
  src/Fixer/Semicolon/MultilineWhitespaceBeforeSemicolonsFixer.php
  tests/Fixer/Semicolon/MultilineWhitespaceBeforeSemicolonsFixerTest.php
Labels: feature

#3671 ArrayIndentationFixer - Fix indentation in HTML
  src/Fixer/Whitespace/ArrayIndentationFixer.php
  tests/Fixer/Whitespace/ArrayIndentationFixerTest.php
Labels: bug

#3731 PhpdocIndentFixer - crash fix
  src/Fixer/Phpdoc/PhpdocIndentFixer.php
  tests/Fixer/Phpdoc/PhpdocIndentFixerTest.php
Labels: bug

#3622 Docs: Update descriptions
  README.rst
  src/Fixer/ClassUsage/DateTimeImmutableFixer.php
  src/Fixer/Comment/CommentToPhpdocFixer.php
  src/Fixer/PhpUnit/PhpUnitSetUpTearDownVisibilityFixer.php
Labels: documentation, enhancement

#3585 Add ReturnAssignmentFixer
  .php_cs.dist
  README.rst
  src/Console/Command/ReadmeCommand.php
  src/Fixer/PhpUnit/PhpUnitTestAnnotationFixer.php
  src/Fixer/ReturnNotation/ReturnAssignmentFixer.php
  tests/AutoReview/FixerFactoryTest.php
  tests/ConfigTest.php
  tests/Console/Output/ErrorOutputTest.php
  tests/Fixer/ReturnNotation/ReturnAssignmentFixerTest.php
  tests/Fixtures/Integration/priority/no_empty_statement,return_assignment.test
  tests/Fixtures/Integration/priority/return_assignment,blank_line_before_statement.test
  tests/Tokenizer/TokenTest.php
  tests/Tokenizer/TokensAnalyzerTest.php
Labels: feature

#2577 Add LogicalOperatorsFixer
  .php_cs.dist
  README.rst
  src/Fixer/Operator/LogicalOperatorsFixer.php
  tests/Fixer/Operator/LogicalOperatorsFixerTest.php
Labels: feature

#3709 Add SetTypeToCastFixer
  README.rst
  src/Fixer/Alias/SetTypeToCastFixer.php
  tests/Fixer/Alias/SetTypeToCastFixerTest.php
Labels: feature

#3733 Disable Composer optimized autoloader by default
  .appveyor.yml
  .travis.yml
  circle.yml
  composer.json
Labels: enhancement

#3738 ReturnAssignmentFixer description update
  README.rst
  src/Fixer/ReturnNotation/ReturnAssignmentFixer.php
Labels: documentation, enhancement

#3748 PhpUnitStrictFixer - extend risky note
  README.rst
  src/Fixer/PhpUnit/PhpUnitStrictFixer.php
Labels: documentation

#3749 Make sure PHPUnit is cased correctly in fixers descriptions
  README.rst
  src/Fixer/Comment/NoTrailingWhitespaceInCommentFixer.php
  src/Fixer/Phpdoc/GeneralPhpdocAnnotationRemoveFixer.php
  src/Fixer/Phpdoc/PhpdocAnnotationWithoutDotFixer.php
  src/Fixer/Phpdoc/PhpdocNoAccessFixer.php
  src/Fixer/Phpdoc/PhpdocNoEmptyReturnFixer.php
  src/Fixer/Phpdoc/PhpdocNoPackageFixer.php
  src/Fixer/Phpdoc/PhpdocOrderFixer.php
  src/Fixer/Phpdoc/PhpdocSeparationFixer.php
  src/Fixer/Phpdoc/PhpdocSummaryFixer.php
  src/Fixer/Phpdoc/PhpdocTrimFixer.php
  tests/AutoReview/FixerTest.php
Labels: documentation, tests / CI

#3740 NoUnusedImportsFixer - remove SF exception
  src/Fixer/Import/NoUnusedImportsFixer.php
Labels: BC break

#3755 YodaStyleFixer - handle space between var name and index
  src/Fixer/ControlStructure/YodaStyleFixer.php
  tests/Fixer/ControlStructure/YodaStyleFixerTest.php
Labels: bug

#3765 Fix binary-prefixed double-quoted strings to single quotes
  src/Fixer/StringNotation/SingleQuoteFixer.php
  tests/Fixer/StringNotation/SingleQuoteFixerTest.php
Labels: bug

#3568 New Autoreview: Correct option casing
  README.rst
  src/Console/Command/DescribeCommand.php
  src/Console/Command/HelpCommand.php
  src/Fixer/ClassNotation/ClassDefinitionFixer.php
  src/Fixer/Comment/HeaderCommentFixer.php
  src/Fixer/Import/OrderedImportsFixer.php
  src/FixerConfiguration/AliasedFixerOption.php
  src/FixerConfiguration/AliasedFixerOptionBuilder.php
  src/FixerConfiguration/FixerConfigurationResolver.php
  src/RuleSet.php
  tests/AutoReview/FixerTest.php
  tests/Console/Command/DescribeCommandTest.php
  tests/Fixer/ClassNotation/ClassDefinitionFixerTest.php
  tests/Fixer/Comment/HeaderCommentFixerTest.php
  tests/Fixer/Import/OrderedImportsFixerTest.php
  tests/FixerConfiguration/AliasedFixerOptionBuilderTest.php
  tests/FixerConfiguration/AliasedFixerOptionTest.php
  tests/FixerConfiguration/FixerConfigurationResolverTest.php
  tests/Test/AbstractFixerWithAliasedOptionsTestCase.php
Labels: cleanup, refactoring

#3761 Application: when run with FUTURE_MODE, error_reporting(-1) is done in entry file instead
  php-cs-fixer
  src/Console/Application.php
Labels: cleanup, enhancement

#3766 Add NoBinaryStringFixer
  .php_cs.dist
  README.rst
  src/Fixer/StringNotation/NoBinaryStringFixer.php
  tests/Fixer/StringNotation/NoBinaryStringFixerTest.php
Labels: feature

#3451 Update findPHPUnit functions
  src/Fixer/PhpUnit/PhpUnitNoExpectationAnnotationFixer.php
  src/Fixer/PhpUnit/PhpUnitTestAnnotationFixer.php
  src/Indicator/PhpUnitTestCaseIndicator.php
  tests/Indicator/PhpUnitTestCaseIndicatorTest.php
Labels: RTM, cleanup, enhancement

#3771 UX: always set error_reporting in entry file, not Application
  php-cs-fixer
  src/Console/Application.php
Labels: BC break

#3735 Add LowercaseStaticReferenceFixer
  README.rst
  src/Fixer/Casing/LowercaseStaticReferenceFixer.php
  src/RuleSet.php
  tests/Fixer/Casing/LowercaseStaticReferenceFixerTest.php
Labels: feature

#3768 Improve deprecation messages
  src/AbstractFixer.php
  src/Console/ConfigurationResolver.php
  src/Fixer/Alias/RandomApiMigrationFixer.php
  src/Fixer/ClassNotation/OrderedClassElementsFixer.php
  src/Fixer/ClassNotation/SingleClassElementPerStatementFixer.php
  src/Fixer/ClassNotation/VisibilityRequiredFixer.php
  src/Fixer/ControlStructure/NoUnneededControlParenthesesFixer.php
  src/Fixer/Operator/BinaryOperatorSpacesFixer.php
  src/Fixer/PhpUnit/PhpUnitConstructFixer.php
  src/Fixer/PhpUnit/PhpUnitDedicateAssertFixer.php
  src/Fixer/PhpUnit/PhpUnitStrictFixer.php
  src/Fixer/Phpdoc/GeneralPhpdocAnnotationRemoveFixer.php
  src/Fixer/Phpdoc/PhpdocNoAliasTagFixer.php
  src/Fixer/Phpdoc/PhpdocReturnSelfReferenceFixer.php
  src/Fixer/Whitespace/NoExtraBlankLinesFixer.php
  src/Fixer/Whitespace/NoSpacesAroundOffsetFixer.php
  src/FixerConfiguration/FixerConfigurationResolverRootless.php
  tests/Console/ConfigurationResolverTest.php
  tests/Fixer/Alias/RandomApiMigrationFixerTest.php
  tests/Fixer/ClassNotation/OrderedClassElementsFixerTest.php
  tests/Fixer/ClassNotation/SingleClassElementPerStatementFixerTest.php
  tests/Fixer/ClassNotation/VisibilityRequiredFixerTest.php
  tests/Fixer/ControlStructure/NoUnneededControlParenthesesFixerTest.php
  tests/Fixer/DoctrineAnnotation/DoctrineAnnotationSpacesFixerTest.php
  tests/Fixer/LanguageConstruct/IsNullFixerTest.php
  tests/Fixer/PhpUnit/PhpUnitConstructFixerTest.php
  tests/Fixer/PhpUnit/PhpUnitDedicateAssertFixerTest.php
  tests/Fixer/PhpUnit/PhpUnitStrictFixerTest.php
  tests/Fixer/Phpdoc/PhpdocNoAliasTagFixerTest.php
  tests/Fixer/Phpdoc/PhpdocReturnSelfReferenceFixerTest.php
  tests/Fixer/Whitespace/NoExtraBlankLinesFixerTest.php
  tests/Fixer/Whitespace/NoSpacesAroundOffsetFixerTest.php
  tests/FixerConfiguration/FixerConfigurationResolverRootlessTest.php
  tests/Fixtures/DeprecatedFixer.php
Labels: enhancement

#3773 AbstractFixerWithAliasedOptionsTestCase - don't export
  .gitattributes
Labels: cleanup, releases

#3770 Handle binary flags in heredoc_to_nowdoc
  src/Fixer/StringNotation/HeredocToNowdocFixer.php
  tests/Fixer/StringNotation/HeredocToNowdocFixerTest.php
Labels: bug

#3776 ExplicitStringVariableFixer - handle binary strings
  src/Fixer/StringNotation/ExplicitStringVariableFixer.php
  tests/Fixer/StringNotation/ExplicitStringVariableFixerTest.php
Labels: bug

#3777 EscapeImplicitBackslashesFixer - handle binary strings
  src/Fixer/StringNotation/EscapeImplicitBackslashesFixer.php
  tests/Fixer/StringNotation/EscapeImplicitBackslashesFixerTest.php
Labels: bug

#3698 YodaStyleFixer - Add always_move_variable option
  README.rst
  src/Fixer/ControlStructure/YodaStyleFixer.php
  tests/Fixer/ControlStructure/YodaStyleFixerTest.php
Labels: feature

#3453 PhpdocAlignFixer - add align option
  README.rst
  src/Fixer/Phpdoc/PhpdocAlignFixer.php
  tests/Fixer/Phpdoc/PhpdocAlignFixerTest.php
Labels: feature

#3708 EspaceImplicitBackslashesFixer - Fix escaping multiple backslashes
  src/Fixer/StringNotation/EscapeImplicitBackslashesFixer.php
  tests/Fixer/StringNotation/EscapeImplicitBackslashesFixerTest.php
Labels: bug

#3779 Misc fixes
  src/Fixer/ControlStructure/NoBreakCommentFixer.php
  src/Fixer/PhpUnit/PhpUnitStrictFixer.php
  src/Tokenizer/Analyzer/Analysis/ArgumentAnalysis.php
  src/Tokenizer/Resolver/TypeShortNameResolver.php
Labels: cleanup

#3780 ShortScalarCastFixer - Change binary cast to string cast as well
  README.rst
  src/Fixer/CastNotation/ShortScalarCastFixer.php
  tests/Fixer/CastNotation/ShortScalarCastFixerTest.php
Labels: feature

#3737 Add NoUnsetOnPropertyFixer
  .php_cs.dist
  README.rst
  src/Fixer/LanguageConstruct/NoUnsetOnPropertyFixer.php
  tests/AutoReview/FixerFactoryTest.php
  tests/Fixer/LanguageConstruct/NoUnsetOnPropertyFixerTest.php
  tests/Fixtures/Integration/priority/no_unset_on_property,combine_consecutive_unsets.test
Labels: feature

#3783 CI: Split COLLECT_COVERAGE job
  .travis.yml
Labels: tests / CI

#3691 Add PhpdocTrimAfterDescriptionFixer
  .php_cs.dist
  README.rst
  src/DocBlock/ShortDescription.php
  src/Fixer/Phpdoc/PhpdocSummaryFixer.php
  src/Fixer/Phpdoc/PhpdocTrimAfterDescriptionFixer.php
  tests/DocBlock/ShortDescriptionTest.php
  tests/Fixer/Phpdoc/PhpdocTrimAfterDescriptionFixerTest.php
Labels: feature

#3734 Add NoSuperfluousPhpdocTagsFixer
  README.rst
  src/Fixer/Phpdoc/NoSuperfluousPhpdocTagsFixer.php
  src/Fixer/Phpdoc/PhpdocReturnSelfReferenceFixer.php
  tests/AutoReview/FixerFactoryTest.php
  tests/Fixer/Phpdoc/NoSuperfluousPhpdocTagsFixerTest.php
  tests/Fixtures/Integration/priority/no_superfluous_phpdoc_tags,no_empty_phpdoc.test
  tests/Fixtures/Integration/priority/phpdoc_return_self_reference,no_superfluous_phpdoc_tags.test
Labels: feature

#3060 Add ErrorSuppressionFixer
  README.rst
  src/Fixer/LanguageConstruct/ErrorSuppressionFixer.php
  src/Fixer/LanguageConstruct/SilencedDeprecationErrorFixer.php
  src/RuleSet.php
  src/Tokenizer/Analyzer/FunctionsAnalyzer.php
  tests/Fixer/LanguageConstruct/ErrorSuppressionFixerTest.php
  tests/Tokenizer/Analyzer/FunctionsAnalyzerTest.php
Labels: feature

#3745 Add PhpUnitInternalClassFixer
  .php_cs.dist
  README.rst
  src/Fixer/PhpUnit/PhpUnitInternalClassFixer.php
  src/Indicator/PhpUnitTestCaseIndicator.php
  tests/AutoReview/FixerFactoryTest.php
  tests/Fixer/PhpUnit/PhpUnitInternalClassFixerTest.php
  tests/Fixtures/Integration/priority/php_unit_internal_class,final_internal_class.test
  tests/Indicator/PhpUnitTestCaseIndicatorTest.php
Labels: feature

#3792 DX: Upgrade DX deps
  composer.json
Labels: tests / CI

#3790 ProcessLinter - don't execute external process without timeout! It can freeze!
  src/Linter/ProcessLinter.php
Labels: bug

#3796 DX: StdinTest - do not assume name of folder, into which project was cloned
  tests/Smoke/StdinTest.php
Labels: tests / CI

#3789 DX: ProjectCodeTest.testThatDataProvidersAreCorrectlyNamed - performance optimization
  tests/AutoReview/ProjectCodeTest.php
Labels: tests / CI

#3476 Add PhpUnitTestCaseStaticMethodCallsFixer
  .php_cs.dist
  README.rst
  src/Fixer/PhpUnit/PhpUnitTestCaseStaticMethodCallsFixer.php
  tests/Console/Command/SelfUpdateCommandTest.php
  tests/Fixer/Alias/NoAliasFunctionsFixerTest.php
  tests/Fixer/Alias/RandomApiMigrationFixerTest.php
  tests/Fixer/LanguageConstruct/IsNullFixerTest.php
  tests/Fixer/PhpUnit/PhpUnitTestCaseStaticMethodCallsFixerTest.php
  tests/FixerConfiguration/AllowedValueSubsetTest.php
Labels: feature
