Repository PHP-CS-Fixer/PHP-CS-Fixer, pull requests merged in 2018-04, with the labels that each got.

#3665 CircleCI fix
  circle.yml
Labels: tests / CI

#3666 Use "set -eu" in shell scripts
  README.rst
  benchmark.sh
  check_trailing_spaces.sh
  dev-tools/build.sh
  dev-tools/ci-integration.sh
  dev-tools/trigger-website.sh
  tests/Smoke/CiIntegrationTest.php
Labels: enhancement

#3676 RunnerTest - workaround for failing Symfony v2.8.37
  tests/Runner/RunnerTest.php
Labels: tests / CI

#3662 DX: Add Smoke/InstallViaComposerTest
  tests/Smoke/InstallViaComposerTest.php
Labels: RTM, tests / CI

#3647 DX: Add CachingLinter for tests
  src/Linter/CachingLinter.php
  tests/AutoReview/ProjectCodeTest.php
  tests/Test/AbstractFixerTestCase.php
  tests/Test/AbstractIntegrationTestCase.php
Labels: RTM, tests / CI

#3663 DX: During deployment, run all smoke tests and don't allow to skip phar-related ones
  .travis.yml
  phpunit.xml.dist
  tests/Smoke/PharTest.php
Labels: tests / CI

#3188 AppVeyor - add PHP 7.x
  .appveyor.yml
Labels: RTM, tests / CI

#3681 CiIntegrationTest - fix incompatibility from 2.x line
  tests/Smoke/CiIntegrationTest.php
Labels: tests / CI

#3692 DX: Optimize tests
  tests/AutoReview/ProjectFixerConfigurationTest.php
  tests/Console/Command/DescribeCommandTest.php
  tests/Console/Command/FixCommandTest.php
  tests/Console/Command/SelfUpdateCommandTest.php
  tests/Report/AbstractReporterTestCase.php
  tests/Report/JunitReporterTest.php
  tests/Report/XmlReporterTest.php
  tests/Smoke/PharTest.php
  tests/Smoke/StdinTest.php
  tests/Test/AbstractFixerTestCase.php
  tests/Test/AbstractIntegrationTestCase.php
  tests/Test/AccessibleObjectTest.php
Labels: tests / CI

#3547 MultilineWhitespaceBeforeSemicolonsFixer - chained call for a return fix
  src/Fixer/Semicolon/MultilineWhitespaceBeforeSemicolonsFixer.php
  tests/Fixer/Semicolon/MultilineWhitespaceBeforeSemicolonsFixerTest.php
Labels: RTM, bug

#3673 PhpdocScalarFixer - Add "types" option
  README.rst
  src/Fixer/Phpdoc/PhpdocScalarFixer.php
  tests/Fixer/Phpdoc/PhpdocScalarFixerTest.php
Labels: RTM, bug

#3578 Add interface for deprecated options
  README.rst
  src/AbstractFixer.php
  src/Console/Command/DescribeCommand.php
  src/Console/Command/HelpCommand.php
  src/Fixer/DoctrineAnnotation/DoctrineAnnotationSpacesFixer.php
  src/Fixer/LanguageConstruct/IsNullFixer.php
  src/Fixer/Operator/BinaryOperatorSpacesFixer.php
  src/Fixer/PhpUnit/PhpUnitDedicateAssertFixer.php
  src/FixerConfiguration/DeprecatedFixerOption.php
  src/FixerConfiguration/DeprecatedFixerOptionInterface.php
  src/FixerConfiguration/FixerOptionBuilder.php
  tests/AutoReview/FixerTest.php
  tests/Console/Command/DescribeCommandTest.php
  tests/Fixer/DoctrineAnnotation/DoctrineAnnotationSpacesFixerTest.php
  tests/Fixer/LanguageConstruct/IsNullFixerTest.php
  tests/Fixer/PhpUnit/PhpUnitDedicateAssertFixerTest.php
  tests/FixerConfiguration/DeprecatedFixerOptionTest.php
Labels: I/O, documentation, enhancement

#3670 PhpdocTypesOrderFixer - Fix ordering of nested generics
  src/Fixer/Phpdoc/PhpdocTypesOrderFixer.php
  tests/Fixer/Phpdoc/PhpdocTypesOrderFixerTest.php
Labels: annotation, bug

#3528 MethodChainingIndentationFixer - nested params bugfix
  src/Fixer/Whitespace/MethodChainingIndentationFixer.php
  tests/Fixer/Whitespace/MethodChainingIndentationFixerTest.php
Labels: bug

#3597 DeclareStrictTypesFixer - fix bug of removing line
  src/Fixer/Strict/DeclareStrictTypesFixer.php
  tests/AutoReview/FixerFactoryTest.php
  tests/Fixer/Strict/DeclareStrictTypesFixerTest.php
  tests/Fixtures/Integration/misc/declare_strict_types,single_blank_line_before_namespace.test
  tests/Fixtures/Integration/priority/declare_strict_types,declare_equal_normalize.test
Labels: bug

#3606 PhpdocToCommentFixer - allow multiple (
  src/Fixer/Phpdoc/PhpdocToCommentFixer.php
  tests/Fixer/Phpdoc/PhpdocToCommentFixerTest.php
Labels: bug

#3686 README.rst - Format all code-like strings in fixer descriptions
  README.rst
  src/Fixer/Alias/EregToPregFixer.php
  src/Fixer/ClassNotation/SelfAccessorFixer.php
  src/Fixer/ClassNotation/VisibilityRequiredFixer.php
  src/Fixer/Import/NoLeadingImportSlashFixer.php
  src/Fixer/Import/NoUnusedImportsFixer.php
  src/Fixer/Import/OrderedImportsFixer.php
  src/Fixer/PhpUnit/PhpUnitConstructFixer.php
  src/Fixer/PhpUnit/PhpUnitDedicateAssertFixer.php
  src/Fixer/Phpdoc/PhpdocAddMissingParamAnnotationFixer.php
  src/Fixer/Phpdoc/PhpdocAlignFixer.php
  src/Fixer/Phpdoc/PhpdocInlineTagFixer.php
  src/Fixer/Phpdoc/PhpdocNoAccessFixer.php
  src/Fixer/Phpdoc/PhpdocNoEmptyReturnFixer.php
  src/Fixer/Phpdoc/PhpdocNoPackageFixer.php
  src/Fixer/Phpdoc/PhpdocNoUselessInheritdocFixer.php
  src/Fixer/Phpdoc/PhpdocOrderFixer.php
  src/Fixer/Phpdoc/PhpdocSingleLineVarSpacingFixer.php
  src/Fixer/Phpdoc/PhpdocVarWithoutNameFixer.php
  src/Fixer/ReturnNotation/NoUselessReturnFixer.php
  tests/AutoReview/FixerTest.php
Labels: documentation, enhancement

#3701 Use correct casing for "PHPDoc"
  README.rst
  src/AbstractPhpdocTypesFixer.php
  src/Fixer/Comment/NoTrailingWhitespaceInCommentFixer.php
  src/Fixer/Phpdoc/GeneralPhpdocAnnotationRemoveFixer.php
  src/Fixer/Phpdoc/PhpdocAddMissingParamAnnotationFixer.php
  src/Fixer/Phpdoc/PhpdocAlignFixer.php
  src/Fixer/Phpdoc/PhpdocAnnotationWithoutDotFixer.php
  src/Fixer/Phpdoc/PhpdocInlineTagFixer.php
  src/Fixer/Phpdoc/PhpdocNoAccessFixer.php
  src/Fixer/Phpdoc/PhpdocNoEmptyReturnFixer.php
  src/Fixer/Phpdoc/PhpdocNoPackageFixer.php
  src/Fixer/Phpdoc/PhpdocOrderFixer.php
  src/Fixer/Phpdoc/PhpdocSeparationFixer.php
  src/Fixer/Phpdoc/PhpdocSummaryFixer.php
  src/Fixer/Phpdoc/PhpdocTrimFixer.php
  src/Fixer/Phpdoc/PhpdocTypesFixer.php
Labels: documentation

#3700 README.rst - Format all code-like strings in fixer description
  README.rst
  src/Fixer/Alias/BacktickToShellExecFixer.php
  src/Fixer/PhpUnit/PhpUnitSetUpTearDownVisibilityFixer.php
Labels: documentation

#3605 DoctrineAnnotationIndentationFixer - Fix indentation with mixed lines
  src/Fixer/DoctrineAnnotation/DoctrineAnnotationIndentationFixer.php
  tests/Fixer/DoctrineAnnotation/DoctrineAnnotationIndentationFixerTest.php
Labels: annotation, bug

#3607 PhpdocVarWithoutNameFixer - update sample with @ type
  src/Fixer/Phpdoc/PhpdocVarWithoutNameFixer.php
  tests/Fixer/Phpdoc/PhpdocVarWithoutNameFixerTest.php
Labels: cleanup, documentation

#3715 SingleImportPerStatementFixer - Fix handling whitespace before opening brace
  src/Fixer/Import/SingleImportPerStatementFixer.php
  tests/Fixer/Import/SingleImportPerStatementFixerTest.php
Labels: bug

#3674 YodaStyleFixer - Fix variable detection for multidimensional arrays
  src/Fixer/ControlStructure/YodaStyleFixer.php
  src/Fixer/Phpdoc/PhpdocAlignFixer.php
  tests/Fixer/ControlStructure/YodaStyleFixerTest.php
Labels: bug
