Repository PHP-CS-Fixer/PHP-CS-Fixer, pull requests merged in 2018-02, with the labels that each got.

#3513 Making AppVeyor happy
  tests/IntegrationTest.php
Labels: tests / CI

#3512 Add missing array typehints
  src/Fixer/ClassNotation/ClassDefinitionFixer.php
Labels: enhancement

#3522 Remove LOCK_EX
  src/Cache/FileHandler.php
Labels: bug

#3521 Use HTTPS
  README.rst
  doc/COOKBOOK-FIXERS.md
  phpunit.xml.dist
  src/Console/Command/HelpCommand.php
  src/Tokenizer/Token.php
  src/Tokenizer/Tokens.php
  tests/Fixer/Alias/NoMixedEchoPrintFixerTest.php
  tests/Fixer/Phpdoc/PhpdocInlineTagFixerTest.php
  tests/Fixer/Phpdoc/PhpdocSeparationFixerTest.php
Labels: documentation

#3531 Backport PHPMD to LTS version to ease maintainability
  .travis.yml
  dev-tools/composer.json
  phpmd.xml
  src/AbstractDoctrineAnnotationFixer.php
  src/AbstractFunctionReferenceFixer.php
  src/AbstractPhpdocTypesFixer.php
  src/Console/Command/FixCommand.php
  src/Console/ConfigurationResolver.php
  src/Console/Output/ProcessOutput.php
  src/DocBlock/Annotation.php
  src/DocBlock/DocBlock.php
  src/Doctrine/Annotation/Token.php
  src/Error/ErrorsManager.php
  src/Fixer/ClassNotation/VisibilityRequiredFixer.php
  src/Fixer/Comment/HeaderCommentFixer.php
  src/Fixer/Comment/NoEmptyCommentFixer.php
  src/Fixer/DoctrineAnnotation/DoctrineAnnotationIndentationFixer.php
  src/Fixer/Import/OrderedImportsFixer.php
  src/Fixer/LanguageConstruct/ClassKeywordRemoveFixer.php
  src/Fixer/PhpTag/NoShortEchoTagFixer.php
  src/Fixer/Phpdoc/PhpdocAlignFixer.php
  src/Fixer/Phpdoc/PhpdocIndentFixer.php
  src/Fixer/Phpdoc/PhpdocToCommentFixer.php
  src/Fixer/Whitespace/NoExtraConsecutiveBlankLinesFixer.php
  src/FixerFactory.php
  src/FixerFileProcessedEvent.php
  src/Linter/LintingException.php
  src/Linter/ProcessLinter.php
  src/RuleSet.php
  src/Runner/FileFilterIterator.php
  src/Runner/Runner.php
  src/StdinFileInfo.php
  src/Tokenizer/AbstractTransformer.php
  src/Tokenizer/Token.php
  src/Tokenizer/Tokens.php
  src/Tokenizer/Transformers.php
  tests/AbstractDoctrineAnnotationFixerTestCase.php
  tests/DocBlock/LineTest.php
  tests/Fixer/Phpdoc/PhpdocInlineTagFixerTest.php
Labels: tests / CI

#3539 Update UnifiedDiffOutputBuilder from gecko-packages/gecko-diff-output-builder usage after it was incorporated into sebastian/diff
  composer.json
  src/Console/Command/DescribeCommand.php
  src/Differ/UnifiedDiffer.php
Labels: I/O

#3518 FixerFactoryTest - Test each priority test file is listed as test
  tests/AutoReview/FixerFactoryTest.php
Labels: tests / CI

#3549 DescribeCommand - use our Differ wrapper class, not external one directly
  src/Console/Command/DescribeCommand.php
Labels: cleanup

#3555 DX: composer.json - drop branch-alias, branch is already following the version
  composer.json
Labels: cleanup, releases

#3516 Use null|type instead of ?type in PHPDocs
  src/FileReader.php
Labels: enhancement
