Repository PHP-CS-Fixer/PHP-CS-Fixer, pull requests merged in 2018-08, with the labels that each got.

#3867 PhpdocAnnotationWithoutDotFixer - Handle trailing whitespaces
  src/Fixer/Phpdoc/PhpdocAnnotationWithoutDotFixer.php
  tests/Fixer/Phpdoc/PhpdocAnnotationWithoutDotFixerTest.php
Labels: bug

#3954 NoSuperfluousPhpdocTagsFixer - Index invalid or out of range
  src/Fixer/Phpdoc/NoSuperfluousPhpdocTagsFixer.php
  tests/Fixer/Phpdoc/NoSuperfluousPhpdocTagsFixerTest.php
Labels: bug

#3924 FullyQualifiedStrictTypesFixer - space bug
  src/Tokenizer/Analyzer/ArgumentsAnalyzer.php
  tests/Fixer/Import/FullyQualifiedStrictTypesFixerTest.php
  tests/Tokenizer/Analyzer/ArgumentsAnalyzerTest.php
Labels: bug

#3950 Circle CI v2 yml
  .circleci/config.yml
  .gitattributes
  circle.yml
Labels: tests / CI

#3944 ExplicitStringVariableFixer - fix array handling
  src/Fixer/StringNotation/ExplicitStringVariableFixer.php
  tests/Fixer/StringNotation/ExplicitStringVariableFixerTest.php
Labels: bug

#3957 NoTrailingWhitespaceFixer - trim space after opening tag
  src/Fixer/Whitespace/NoTrailingWhitespaceFixer.php
  tests/Fixer/Whitespace/NoTrailingWhitespaceFixerTest.php
Labels: bug

#3908 StrictParamFixer - fix edge case
  src/Fixer/Strict/StrictParamFixer.php
  tests/Fixer/Strict/StrictParamFixerTest.php
Labels: bug

#3912 FullyQualifiedStrictTypesFixer - NoSuperfluousPhpdocTagsFixer - adjust priority
  src/Fixer/Import/FullyQualifiedStrictTypesFixer.php
  tests/AutoReview/FixerFactoryTest.php
  tests/Fixtures/Integration/priority/fully_qualified_strict_types,no_superfluous_phpdoc_tags.test
Labels: bug

#3882 PhpdocAnnotationWithoutDotFixer - Handle empty line in comment
  src/Fixer/Phpdoc/PhpdocAnnotationWithoutDotFixer.php
  tests/Fixer/Phpdoc/PhpdocAnnotationWithoutDotFixerTest.php
Labels: enhancement

#3913 TokensAnalyzer - fix isConstantInvocation
  src/Tokenizer/TokensAnalyzer.php
  tests/Tokenizer/TokensAnalyzerTest.php
Labels: bug

#3891 PhpdocNoEmptyReturnFixer - account for null[]
  src/DocBlock/Annotation.php
  src/Fixer/Phpdoc/PhpdocNoEmptyReturnFixer.php
  tests/DocBlock/AnnotationTest.php
  tests/Fixer/Phpdoc/PhpdocNoEmptyReturnFixerTest.php
Labels: enhancement

#3886 Add PhpUnitMethodCasingFixer
  README.rst
  src/Fixer/PhpUnit/PhpUnitMethodCasingFixer.php
  src/Fixer/PhpUnit/PhpUnitTestAnnotationFixer.php
  tests/AutoReview/FixerFactoryTest.php
  tests/Fixer/PhpUnit/PhpUnitMethodCasingFixerTest.php
  tests/Fixer/PhpUnit/PhpUnitTestAnnotationFixerTest.php
  tests/Fixtures/Integration/priority/php_unit_test_annotation,php_unit_method_casing.test
Labels: feature

#3812 Add FopenFlagOrderFixer & FopenFlagsFixer
  README.rst
  src/AbstractFopenFlagFixer.php
  src/Fixer/FunctionNotation/FopenFlagOrderFixer.php
  src/Fixer/FunctionNotation/FopenFlagsFixer.php
  src/RuleSet.php
  tests/Fixer/FunctionNotation/FopenFlagOrderFixerTest.php
  tests/Fixer/FunctionNotation/FopenFlagsFixerTest.php
Labels: feature

#3739 Add MagicMethodCasingFixer
  README.rst
  src/Fixer/Casing/MagicMethodCasingFixer.php
  src/RuleSet.php
  tests/Fixer/Casing/MagicMethodCasingFixerTest.php
Labels: feature

#3826 Add CombineNestedDirnameFixer
  README.rst
  src/Fixer/FunctionNotation/CombineNestedDirnameFixer.php
  src/Fixer/LanguageConstruct/DirConstantFixer.php
  src/RuleSet.php
  tests/AutoReview/FixerFactoryTest.php
  tests/Fixer/FunctionNotation/CombineNestedDirnameFixerTest.php
  tests/Fixtures/Integration/priority/combine_nested_dirname,method_argument_space.test
  tests/Fixtures/Integration/priority/combine_nested_dirname,no_spaces_inside_parenthesis.test
  tests/Fixtures/Integration/priority/combine_nested_dirname,no_trailing_whitespace.test
  tests/Fixtures/Integration/priority/combine_nested_dirname,no_whitespace_in_blank_line.test
  tests/Fixtures/Integration/priority/dir_constant,combine_nested_dirname.test
Labels: feature

#3907 Add ImplodeCallFixer
  README.rst
  src/DocBlock/Annotation.php
  src/DocBlock/DocBlock.php
  src/Fixer/FunctionNotation/ImplodeCallFixer.php
  src/Fixer/FunctionNotation/MethodArgumentSpaceFixer.php
  src/Fixer/PhpUnit/PhpUnitInternalClassFixer.php
  src/Fixer/PhpUnit/PhpUnitMethodCasingFixer.php
  src/Fixer/PhpUnit/PhpUnitNoExpectationAnnotationFixer.php
  src/Fixer/PhpUnit/PhpUnitOrderedCoversFixer.php
  src/Fixer/PhpUnit/PhpUnitTestAnnotationFixer.php
  src/Fixer/Phpdoc/PhpdocAlignFixer.php
  src/Fixer/Whitespace/NoExtraBlankLinesFixer.php
  src/Fixer/Whitespace/NoTrailingWhitespaceFixer.php
  src/RuleSet.php
  tests/AutoReview/FixerFactoryTest.php
  tests/Fixer/FunctionNotation/ImplodeCallFixerTest.php
  tests/Fixtures/Integration/priority/implode_call,method_argument_space.test
  tests/Fixtures/Integration/priority/no_alias_functions,implode_call.test
Labels: feature
