Repository PHP-CS-Fixer/PHP-CS-Fixer, pull requests merged in 2018-07, with the labels that each got.

#3841 NoAliasFunctionsFixer - add opt in option for ext-mbstring aliasses
  README.rst
  src/Fixer/Alias/NoAliasFunctionsFixer.php
  tests/Fixer/Alias/NoAliasFunctionsFixerTest.php
Labels: RTM, feature

#3817 Update integrations tests
  tests/AutoReview/FixerFactoryTest.php
  tests/Fixtures/Integration/priority/no_empty_statement,no_singleline_whitespace_before_semicolons.test
Labels: RTM, tests / CI

#3813 PhpUnitDedicateAssertFixer - fix "sizeOf" same as "count".
  src/Fixer/PhpUnit/PhpUnitDedicateAssertFixer.php
  tests/Fixer/PhpUnit/PhpUnitDedicateAssertFixerTest.php
Labels: RTM, enhancement

#3833 BinaryOperatorSpacesFixer - Add "no space" fix strategy
  README.rst
  src/Fixer/Operator/BinaryOperatorSpacesFixer.php
  tests/Fixer/Operator/BinaryOperatorSpacesFixerTest.php
Labels: RTM, feature

#3866 SpaceAfterSemicolonFixer - loop over all tokens
  src/Fixer/Semicolon/SpaceAfterSemicolonFixer.php
  tests/Fixer/Semicolon/SpaceAfterSemicolonFixerTest.php
Labels: bug

#3848 Add install/update instructions for PHIVE to the README
  README.rst
  src/Console/Command/ReadmeCommand.php
Labels: RTM, documentation

#3839 MethodArgumentSpaceFixer - add empty line incorrectly
  src/Fixer/FunctionNotation/MethodArgumentSpaceFixer.php
  tests/Fixer/FunctionNotation/MethodArgumentSpaceFixerTest.php
Labels: bug

#3877 NamespacesAnalyzer - Optimize performance
  src/Tokenizer/Analyzer/NamespacesAnalyzer.php
Labels: refactoring

#3878 NativeFunctionInvocationFixer - use the NamespacesAnalyzer to remove duplicated code
  src/Fixer/FunctionNotation/NativeFunctionInvocationFixer.php
Labels: refactoring

#3884 NoSuperfluousPhpdocTagsFixer - handle null in every position
  src/Fixer/Phpdoc/NoSuperfluousPhpdocTagsFixer.php
  tests/Fixer/Phpdoc/NoSuperfluousPhpdocTagsFixerTest.php
Labels: RTM, bug

#3887 ArrayIndentFixer - Don't indent empty lines
  src/Fixer/Whitespace/ArrayIndentationFixer.php
  tests/Fixer/Whitespace/ArrayIndentationFixerTest.php
Labels: RTM, bug

#3888 NoExtraBlankLinesFixer - remove blank lines after open tag
  src/Fixer/Whitespace/NoExtraBlankLinesFixer.php
  tests/Fixer/Whitespace/NoExtraBlankLinesFixerTest.php
  tests/Fixtures/Integration/priority/no_unused_imports,no_extra_blank_lines.test
Labels: RTM, bug

#3890 StrictParamFixer - make it case-insensitive
  src/Fixer/Strict/StrictParamFixer.php
  tests/Fixer/Strict/StrictParamFixerTest.php
Labels: RTM, bug

#3892 PhpdocNoEmptyReturnFixer - fix docs
  README.rst
  src/Fixer/Phpdoc/PhpdocNoEmptyReturnFixer.php
Labels: RTM, documentation

#3895 FunctionsAnalyzer - false positive for constant and function definition
  src/Fixer/LanguageConstruct/ErrorSuppressionFixer.php
  src/Tokenizer/Analyzer/FunctionsAnalyzer.php
  tests/Tokenizer/Analyzer/FunctionsAnalyzerTest.php
Labels: RTM, bug

#3897 DX: FunctionsAnalyzer - simplifying return expression
  src/Tokenizer/Analyzer/FunctionsAnalyzer.php
Labels: RTM, cleanup

#3873 Add the native_function_invocation fixer in the Symfony:risky ruleset
  .php_cs.dist
  README.rst
  src/RuleSet.php
Labels: RTM, enhancement

#3903 DX: cleanup - remove special treatment for PHP <5.6
  src/Fixer/ClassNotation/SelfAccessorFixer.php
  src/Utils.php
  tests/Console/Command/SelfUpdateCommandTest.php
  tests/Fixer/ClassNotation/SelfAccessorFixerTest.php
  tests/Fixer/ClassNotation/VisibilityRequiredFixerTest.php
  tests/Fixer/ControlStructure/YodaStyleFixerTest.php
  tests/Fixer/Import/NoLeadingImportSlashFixerTest.php
  tests/Fixer/Strict/StrictParamFixerTest.php
  tests/Test/AbstractIntegrationTestCase.php
  tests/Tokenizer/TokensAnalyzerTest.php
Labels: RTM, cleanup

#3920 Docs: Fix typo
  src/Fixer/LanguageConstruct/CombineConsecutiveUnsetsFixer.php
Labels: documentation

#3914 NoUnreachableDefaultArgumentValueFixer - remove `null` for nullable typehints
  src/Fixer/FunctionNotation/NoUnreachableDefaultArgumentValueFixer.php
  tests/Fixer/FunctionNotation/NoUnreachableDefaultArgumentValueFixerTest.php
Labels: enhancement

#3937 LowercaseStaticReferenceFixer - Fix "Parent" word in namespace
  src/Fixer/Casing/LowercaseStaticReferenceFixer.php
  tests/Fixer/Casing/LowercaseStaticReferenceFixerTest.php
Labels: RTM, bug

#3940 DX: fix phpdoc parameter type
  src/Fixer/PhpUnit/PhpUnitInternalClassFixer.php
Labels: RTM

#3948 DX: cleanup - remove redundant @param annotations
  tests/Tokenizer/Analyzer/CommentsAnalyzerTest.php
Labels: RTM, cleanup

#3951 NoSuperfluousPhpdocTagsFixer - do not call strtolower with null
  src/Fixer/Phpdoc/NoSuperfluousPhpdocTagsFixer.php
  tests/Fixer/Phpdoc/NoSuperfluousPhpdocTagsFixerTest.php
Labels: RTM, bug

#3876 NativeConstantInvocationFixer - add the scope option
  README.rst
  src/Fixer/ConstantNotation/NativeConstantInvocationFixer.php
  src/RuleSet.php
  tests/Fixer/ConstantNotation/NativeConstantInvocationFixerTest.php
Labels: feature
