Repository PHP-CS-Fixer/PHP-CS-Fixer, pull requests merged in 2019-11, with the labels that each got.

#4610 Travis CI - Update known files list
  .travis.yml
Labels: RTM, topic/tests

#4615 Remove workaround for dev-tools install reg. Phive
  dev-tools/install.sh
Labels: topic/tests

#4607 Configure no_superfluous_phpdoc_tags for Symfony
  src/RuleSet.php
Labels: kind/cleanup, kind/enhancement

#4585 Fix deprecation notices
  tests/Fixer/ClassNotation/ClassDefinitionFixerTest.php
  tests/Fixer/Comment/HeaderCommentFixerTest.php
  tests/Fixer/Import/OrderedImportsFixerTest.php
  tests/Fixtures/Integration/priority/no_blank_lines_after_phpdoc,header_comment.test
Labels: RTM, kind/enhancement, topic/tests

#4587 Output details - Explain why a file was skipped
  src/Console/Output/ProcessOutput.php
  tests/Smoke/CiIntegrationTest.php
Labels: RTM, kind/enhancement

#4589 PhpdocToReturnType - Add support for Foo[][]
  src/DocBlock/Annotation.php
  tests/DocBlock/AnnotationTest.php
  tests/Fixer/FunctionNotation/PhpdocToReturnTypeFixerTest.php
Labels: RTM, kind/enhancement

#4594 Braces - fix both single line comment styles
  src/Fixer/Basic/BracesFixer.php
  tests/Fixer/Basic/BracesFixerTest.php
Labels: kind/bug

#4595 Import cannot be used after `::` so can be removed
  src/Fixer/Import/NoUnusedImportsFixer.php
  tests/Fixer/Import/NoUnusedImportsFixerTest.php
Labels: RTM, kind/enhancement

#4609 PhpdocTypesOrderFixer - Prevent unexpected default value change
  src/Fixer/Phpdoc/PhpdocTypesOrderFixer.php
  tests/Fixer/Phpdoc/PhpdocTypesOrderFixerTest.php
Labels: kind/bug

#4452 Add SingleLineThrowFixer
  README.rst
  src/Fixer/FunctionNotation/SingleLineThrowFixer.php
  tests/AutoReview/FixerFactoryTest.php
  tests/Fixer/FunctionNotation/SingleLineThrowFixerTest.php
  tests/Fixtures/Integration/priority/concat_space,single_line_throw.test
Labels: RTM, kind/feature

#3928 Add FinalPublicMethodForAbstractClassFixer
  README.rst
  src/Fixer/ClassNotation/FinalPublicMethodForAbstractClassFixer.php
  tests/Fixer/ClassNotation/FinalPublicMethodForAbstractClassFixerTest.php
Labels: kind/feature

#4584 Increase PHPStan level to 1
  .travis.yml
  dev-tools/composer.json
  phpstan.neon
  src/AbstractLinesBeforeNamespaceFixer.php
  src/Console/Command/DescribeCommand.php
  src/Fixer/Basic/BracesFixer.php
  src/Fixer/ClassNotation/ClassAttributesSeparationFixer.php
  src/Fixer/Import/SingleImportPerStatementFixer.php
Labels: kind/enhancement, topic/tests

#4586 BracesFixer - handle dynamic static method call
  src/Fixer/Basic/BracesFixer.php
  tests/Fixer/Basic/BracesFixerTest.php
Labels: kind/bug

#4572 TokensAnalyzer - handle nested anonymous classes
  src/Tokenizer/TokensAnalyzer.php
  tests/Fixer/ClassNotation/VisibilityRequiredFixerTest.php
  tests/Tokenizer/TokensAnalyzerTest.php
Labels: kind/bug

#4596 Ensure compatibility with PHP 7.4 numeric literal separator
  tests/Fixer/Alias/PowToExponentiationFixerTest.php
  tests/Fixer/ControlStructure/YodaStyleFixerTest.php
  tests/Fixer/Operator/StandardizeIncrementFixerTest.php
Labels: kind/enhancement, topic/7.4

#4602 Ensure compatibility with PHP 7.4 spread operator in array expression
  tests/Fixer/ArrayNotation/NoTrailingCommaInSinglelineArrayFixerTest.php
  tests/Fixer/ArrayNotation/NoWhitespaceBeforeCommaInArrayFixerTest.php
  tests/Fixer/ArrayNotation/TrailingCommaInMultilineArrayFixerTest.php
  tests/Fixer/ArrayNotation/WhitespaceAfterCommaInArrayFixerTest.php
  tests/Fixer/Whitespace/ArrayIndentationFixerTest.php
Labels: kind/enhancement, topic/7.4

#4603 Ensure compatibility with PHP 7.4 null coalescing assignment operator
  .composer-require-checker.json
  src/Fixer/Operator/BinaryOperatorSpacesFixer.php
  src/Tokenizer/TokensAnalyzer.php
  tests/Fixer/Operator/BinaryOperatorSpacesFixerTest.php
  tests/Tokenizer/TokensAnalyzerTest.php
Labels: kind/enhancement, topic/7.4

#4593 Ensure compatibility with PHP 7.4 typed properties
  README.rst
  src/Fixer/ClassNotation/ClassAttributesSeparationFixer.php
  src/Fixer/ClassNotation/NoNullPropertyInitializationFixer.php
  src/Fixer/ClassNotation/SingleClassElementPerStatementFixer.php
  src/Fixer/ClassNotation/VisibilityRequiredFixer.php
  src/Fixer/LanguageConstruct/NoUnsetOnPropertyFixer.php
  src/Tokenizer/Transformer/NullableTypeTransformer.php
  tests/Fixer/ClassNotation/ClassAttributesSeparationFixerTest.php
  tests/Fixer/ClassNotation/NoNullPropertyInitializationFixerTest.php
  tests/Fixer/ClassNotation/OrderedClassElementsFixerTest.php
  tests/Fixer/ClassNotation/ProtectedToPrivateFixerTest.php
  tests/Fixer/ClassNotation/SingleClassElementPerStatementFixerTest.php
  tests/Fixer/ClassNotation/VisibilityRequiredFixerTest.php
  tests/Fixer/Naming/NoHomoglyphNamesFixerTest.php
  tests/Fixer/Phpdoc/PhpdocToCommentFixerTest.php
  tests/Fixer/Whitespace/CompactNullableTypehintFixerTest.php
  tests/Tokenizer/TokensAnalyzerTest.php
  tests/Tokenizer/Transformer/NullableTypeTransformerTest.php
Labels: kind/enhancement, topic/7.4

#4600 Ensure compatibility with PHP 7.4 arrow functions
  .composer-require-checker.json
  .travis.yml
  phpstan.neon
  src/Fixer/FunctionNotation/FunctionDeclarationFixer.php
  src/Fixer/FunctionNotation/FunctionTypehintSpaceFixer.php
  src/Fixer/FunctionNotation/MethodArgumentSpaceFixer.php
  src/Fixer/FunctionNotation/NoUnreachableDefaultArgumentValueFixer.php
  src/Fixer/FunctionNotation/PhpdocToReturnTypeFixer.php
  src/Fixer/FunctionNotation/StaticLambdaFixer.php
  src/Tokenizer/Analyzer/FunctionsAnalyzer.php
  src/Tokenizer/Token.php
  src/Tokenizer/TokensAnalyzer.php
  src/Tokenizer/Transformer/ReturnRefTransformer.php
  src/Tokenizer/Transformer/TypeColonTransformer.php
  tests/Fixer/ArrayNotation/NoMultilineWhitespaceAroundDoubleArrowFixerTest.php
  tests/Fixer/Casing/LowercaseKeywordsFixerTest.php
  tests/Fixer/ControlStructure/YodaStyleFixerTest.php
  tests/Fixer/FunctionNotation/FunctionDeclarationFixerTest.php
  tests/Fixer/FunctionNotation/FunctionTypehintSpaceFixerTest.php
  tests/Fixer/FunctionNotation/MethodArgumentSpaceFixerTest.php
  tests/Fixer/FunctionNotation/NoUnreachableDefaultArgumentValueFixerTest.php
  tests/Fixer/FunctionNotation/PhpdocToReturnTypeFixerTest.php
  tests/Fixer/FunctionNotation/ReturnTypeDeclarationFixerTest.php
  tests/Fixer/FunctionNotation/StaticLambdaFixerTest.php
  tests/Fixer/FunctionNotation/VoidReturnFixerTest.php
  tests/Fixer/Operator/BinaryOperatorSpacesFixerTest.php
  tests/Fixer/Whitespace/CompactNullableTypehintFixerTest.php
  tests/Tokenizer/Analyzer/BlocksAnalyzerTest.php
  tests/Tokenizer/Analyzer/CommentsAnalyzerTest.php
  tests/Tokenizer/Analyzer/FunctionsAnalyzerTest.php
  tests/Tokenizer/TokensAnalyzerTest.php
  tests/Tokenizer/Transformer/ArrayTypehintTransformerTest.php
  tests/Tokenizer/Transformer/BraceClassInstantiationTransformerTest.php
  tests/Tokenizer/Transformer/NullableTypeTransformerTest.php
  tests/Tokenizer/Transformer/ReturnRefTransformerTest.php
  tests/Tokenizer/Transformer/TypeColonTransformerTest.php
Labels: kind/enhancement, topic/7.4

#4597 Fix PHP 7.4 deprecation notices
  src/Fixer/CastNotation/LowercaseCastFixer.php
  src/Fixer/CastNotation/ShortScalarCastFixer.php
  tests/Fixer/CastNotation/LowercaseCastFixerTest.php
  tests/Fixer/CastNotation/ShortScalarCastFixerTest.php
  tests/Fixer/ControlStructure/YodaStyleFixerTest.php
Labels: topic/7.4, topic/tests

#4588 Fix STDIN test when path is one level deep
  tests/Smoke/StdinTest.php
Labels: kind/enhancement, topic/tests

#4622 Disallow PHP 7.4 failures on Travis CI
  .travis.yml
Labels: RTM, topic/tests

#4626 FinalPublicMethodForAbstractClassFixer - Do not attempt to mark abstract public methods as final
  src/Fixer/ClassNotation/FinalPublicMethodForAbstractClassFixer.php
  tests/Fixer/ClassNotation/FinalPublicMethodForAbstractClassFixerTest.php
Labels: RTM, kind/bug

#4632 NullableTypeDeclarationForDefaultNullValueFixer - fix for not lowercase "null"
  src/Fixer/FunctionNotation/NullableTypeDeclarationForDefaultNullValueFixer.php
  tests/Fixer/FunctionNotation/NullableTypeDeclarationForDefaultNullValueFixerTest.php
Labels: RTM, kind/bug

#4623 README - Mark up as code
  README.rst
  src/Fixer/ClassNotation/FinalPublicMethodForAbstractClassFixer.php
  src/Fixer/ClassNotation/FinalStaticAccessFixer.php
  src/Fixer/ClassNotation/SelfStaticAccessorFixer.php
Labels: RTM, kind/enhancement, topic/documentation

#4569 PhpdocOrderByValueFixer - Introduction
  README.rst
  src/Fixer/PhpUnit/PhpUnitOrderedCoversFixer.php
  src/Fixer/Phpdoc/PhpdocOrderByValueFixer.php
  src/RuleSet.php
  tests/Fixer/Phpdoc/PhpdocOrderByValueFixerTest.php
Labels: RTM, kind/feature

#4608 Allow Symfony 5 components
  .composer-require-checker.json
  .travis.yml
  composer.json
  phpstan.neon
  src/Console/ConfigurationResolver.php
  src/Event/Event.php
  src/FixerFileProcessedEvent.php
  src/Runner/FileFilterIterator.php
  src/Runner/Runner.php
  tests/AutoReview/ProjectCodeTest.php
  tests/Console/ConfigurationResolverTest.php
  tests/Event/EventTest.php
Labels: RTM, kind/enhancement

#4655 Improve docs - README
  README.rst
  src/Console/Command/HelpCommand.php
Labels: topic/documentation

#4634 Make all options snake_case
  README.rst
  src/Fixer/ClassNotation/FinalClassFixer.php
  src/Fixer/ClassNotation/FinalInternalClassFixer.php
  src/Fixer/ClassNotation/OrderedClassElementsFixer.php
  tests/AutoReview/FixerTest.php
  tests/Fixer/ClassNotation/FinalInternalClassFixerTest.php
  tests/Fixer/ClassNotation/OrderedClassElementsFixerTest.php
Labels: kind/enhancement

#4476 FunctionsAnalyzer - add "isTheSameClassCall" for correct verifying of function calls
  src/Fixer/PhpUnit/PhpUnitConstructFixer.php
  src/Fixer/PhpUnit/PhpUnitDedicateAssertFixer.php
  src/Fixer/PhpUnit/PhpUnitStrictFixer.php
  src/Fixer/PhpUnit/PhpUnitTestCaseStaticMethodCallsFixer.php
  src/Tokenizer/Analyzer/FunctionsAnalyzer.php
  tests/Fixer/PhpUnit/PhpUnitConstructFixerTest.php
  tests/Fixer/PhpUnit/PhpUnitDedicateAssertFixerTest.php
  tests/Fixer/PhpUnit/PhpUnitStrictFixerTest.php
  tests/Fixer/PhpUnit/PhpUnitTestCaseStaticMethodCallsFixerTest.php
  tests/Tokenizer/Analyzer/FunctionsAnalyzerTest.php
Labels: kind/enhancement, kind/refactoring

#4645 Check PHP extensions on runtime
  php-cs-fixer
Labels: kind/enhancement, topic/I/O

#4638 Ensure compatibility with PHP 7.4
  src/Fixer/FunctionNotation/NullableTypeDeclarationForDefaultNullValueFixer.php
  src/Fixer/Phpdoc/PhpdocLineSpanFixer.php
  tests/Fixer/FunctionNotation/NullableTypeDeclarationForDefaultNullValueFixerTest.php
  tests/Fixer/Phpdoc/PhpdocLineSpanFixerTest.php
Labels: RTM, kind/enhancement, topic/7.4

#4654 ArrayIndentationFixer - Fix array indentation for multiline values
  src/Fixer/Whitespace/ArrayIndentationFixer.php
  tests/Fixer/Whitespace/ArrayIndentationFixerTest.php
Labels: RTM, kind/bug, kind/enhancement

#4660 TokensAnalyzer::isConstantInvocation - fix for extending multiple interfaces
  src/Tokenizer/TokensAnalyzer.php
  tests/Tokenizer/TokensAnalyzerTest.php
Labels: kind/bug

#4641 Add typed properties test to VisibilityRequiredFixerTest
  src/Fixer/ClassNotation/VisibilityRequiredFixer.php
  src/Tokenizer/Transformer/NullableTypeTransformer.php
  tests/Fixer/ClassNotation/VisibilityRequiredFixerTest.php
  tests/Tokenizer/Transformer/NullableTypeTransformerTest.php
Labels: kind/enhancement, topic/7.4

#4666 Remove deprecated rules: lowercase_constants, php_unit_ordered_covers, silenced_deprecation_error
  README.rst
  UPGRADE-v3.md
  src/Fixer/Casing/LowercaseConstantsFixer.php
  src/Fixer/LanguageConstruct/SilencedDeprecationErrorFixer.php
  src/Fixer/PhpUnit/PhpUnitOrderedCoversFixer.php
  tests/Fixer/Casing/LowercaseConstantsFixerTest.php
  tests/Fixer/LanguageConstruct/SilencedDeprecationErrorFixerTest.php
  tests/Fixer/PhpUnit/PhpUnitOrderedCoversFixerTest.php
Labels: kind/cleanup

#4605 PhpdocToParamTypeFixer - cover more cases
  src/Fixer/FunctionNotation/PhpdocToParamTypeFixer.php
  tests/Fixer/FunctionNotation/PhpdocToParamTypeFixerTest.php
Labels: kind/bug

#4668 TokensAnalyzer::isConstantInvocation - fix for interface method return type
  src/Tokenizer/TokensAnalyzer.php
  tests/Tokenizer/TokensAnalyzerTest.php
Labels: kind/bug
