Repository PHP-CS-Fixer/PHP-CS-Fixer, pull requests merged in 2019-06, with the labels that each got.

#4419 PhpUnitTestCaseStaticMethodCallsFixer - skip anonymous classes and lambda
  src/Fixer/PhpUnit/PhpUnitTestCaseStaticMethodCallsFixer.php
  tests/Fixer/PhpUnit/PhpUnitTestCaseStaticMethodCallsFixerTest.php
Labels: bug

#4420 MethodArgumentSpaceFixer - PHP7.3 trailing commas in function calls
  src/Fixer/FunctionNotation/MethodArgumentSpaceFixer.php
  tests/Fixer/FunctionNotation/MethodArgumentSpaceFixerTest.php
Labels: bug

#4427 DX: stop using reserved T_FN in code samples
  tests/Fixer/Import/OrderedImportsFixerTest.php
  tests/Fixer/Import/SingleLineAfterImportsFixerTest.php
Labels: 7.4

#4345 Travis: PHP 7.4 isn't allowed to fail anymore
  .travis.yml
Labels: 7.4, tests / CI
