Repository PHP-CS-Fixer/PHP-CS-Fixer, pull requests merged in 2019-03, with the labels that each got.

#4303 FullyQualifiedStrictTypesFixer - Fix the short type detection when a question mark (nullable) is prefixing it.
  src/Fixer/Import/FullyQualifiedStrictTypesFixer.php
  src/Tokenizer/Analyzer/Analysis/TypeAnalysis.php
  tests/Fixer/Import/FullyQualifiedStrictTypesFixerTest.php
  tests/Tokenizer/Analyzer/Analysis/TypeAnalysisTest.php
Labels: RTM, bug

#4313 SelfAccessorFixer - fix for part qualified class name
  src/Fixer/ClassNotation/SelfAccessorFixer.php
  tests/Fixer/ClassNotation/SelfAccessorFixerTest.php
Labels: RTM, bug

#4314 PhpUnitTestCaseStaticMethodCallsFixer - fix for having property with name as method to update
  src/Fixer/PhpUnit/PhpUnitTestCaseStaticMethodCallsFixer.php
  tests/Fixer/PhpUnit/PhpUnitTestCaseStaticMethodCallsFixerTest.php
Labels: RTM, bug

#4327 TokensAnalyzer - add concat operator to list of binary operators
  src/Fixer/ControlStructure/YodaStyleFixer.php
  src/Tokenizer/TokensAnalyzer.php
  tests/Fixer/ControlStructure/YodaStyleFixerTest.php
  tests/Tokenizer/TokensAnalyzerTest.php
Labels: RTM, bug

#4335 Cache - add indent and line ending to cache signature
  src/Cache/Cache.php
  src/Cache/Signature.php
  src/Cache/SignatureInterface.php
  src/Console/ConfigurationResolver.php
  tests/Cache/CacheTest.php
  tests/Cache/FileHandlerTest.php
  tests/Cache/SignatureTest.php
Labels: RTM, bug

#4338 Fix wording
  README.rst
  src/Console/Command/HelpCommand.php
  src/Fixer/PhpUnit/PhpUnitNamespacedFixer.php
Labels: RTM, cleanup, documentation

#4340 Travis: build against 7.4snapshot instead of nightly
  .travis.yml
Labels: RTM, tests / CI

#4316 NoUnsetCastFixer - Test for higher-precedence operators
  src/Fixer/CastNotation/NoUnsetCastFixer.php
  tests/Fixer/CastNotation/NoUnsetCastFixerTest.php
Labels: bug

#3922 Make some more classes final
  src/DocBlock/Annotation.php
  src/DocBlock/DocBlock.php
  src/DocBlock/Line.php
  src/DocBlock/Tag.php
  src/DocBlock/TagComparator.php
  src/Tokenizer/Token.php
  src/Tokenizer/Tokens.php
Labels: RTM, cleanup

#4121 SingleTraitInsertPerStatementFixer - Introduction
  README.rst
  src/Fixer/ClassNotation/SingleTraitInsertPerStatementFixer.php
  src/RuleSet.php
  tests/AutoReview/FixerFactoryTest.php
  tests/Fixer/ClassNotation/SingleTraitInsertPerStatementFixerTest.php
  tests/Fixtures/Integration/priority/single_trait_insert_per_statement,braces.test
  tests/Fixtures/Integration/priority/single_trait_insert_per_statement,space_after_semicolon.test
Labels: feature

#4126 NativeFunctionTypeDeclarationCasingFixer - Introduction
  README.rst
  src/Fixer/Casing/NativeFunctionTypeDeclarationCasingFixer.php
  src/RuleSet.php
  tests/Fixer/Casing/NativeFunctionTypeDeclarationCasingFixerTest.php
Labels: RTM, feature

#4191 [7.3] NoWhitespaceBeforeCommaInArrayFixer - fix comma after heredoc-end
  README.rst
  src/Fixer/ArrayNotation/NoWhitespaceBeforeCommaInArrayFixer.php
  tests/Fixer/ArrayNotation/NoWhitespaceBeforeCommaInArrayFixerTest.php
  tests/Fixtures/Integration/misc/PHP7_3.test
Labels: RTM, enhancement

#4112 NoSuperfluousPhpdocTagsFixer - Add missing code sample, groom tests
  src/Fixer/Phpdoc/NoSuperfluousPhpdocTagsFixer.php
  tests/Fixer/Phpdoc/NoSuperfluousPhpdocTagsFixerTest.php
Labels: cleanup, documentation

#4342 [7.3] MethodArgumentSpaceFixer - fix comma after heredoc-end
  README.rst
  src/Fixer/FunctionNotation/MethodArgumentSpaceFixer.php
  tests/Fixer/FunctionNotation/MethodArgumentSpaceFixerTest.php
  tests/Fixtures/Integration/misc/PHP7_3.test
Labels: feature

#4341 [7.3] TrailingCommaInMultilineArrayFixer - fix comma after heredoc-end
  README.rst
  src/Fixer/ArrayNotation/TrailingCommaInMultilineArrayFixer.php
  tests/Fixer/ArrayNotation/TrailingCommaInMultilineArrayFixerTest.php
  tests/Fixtures/Integration/misc/PHP7_3.test
Labels: feature

#4339 Change BracesFixer to avoid indenting PHP inline braces
  src/Fixer/Basic/BracesFixer.php
  tests/Fixer/Basic/BracesFixerTest.php
Labels: enhancement

#4328 Add PhpUnitDedicateAssertInternalTypeFixer
  README.rst
  src/Fixer/PhpUnit/PhpUnitDedicateAssertInternalTypeFixer.php
  src/Fixer/PhpUnit/PhpUnitTargetVersion.php
  src/RuleSet.php
  tests/AutoReview/FixerFactoryTest.php
  tests/Fixer/PhpUnit/PhpUnitDedicateAssertInternalTypeFixerTest.php
  tests/Fixtures/Integration/priority/php_unit_dedicate_assert,php_unit_dedicate_assert_internal_type.test
Labels: feature, waiting review

#4113 OrderedInterfacesFixer - Introduction
  README.rst
  src/Fixer/ClassNotation/OrderedInterfacesFixer.php
  tests/Fixer/ClassNotation/OrderedInterfacesFixerTest.php
Labels: feature, waiting review

#4344 VoidReturnFixer - handle yield from
  src/Fixer/FunctionNotation/VoidReturnFixer.php
  tests/Fixer/FunctionNotation/VoidReturnFixerTest.php
Labels: RTM, bug

#4167 PhpUnitMockShortWillReturnFixer - Introduction
  README.rst
  src/Fixer/PhpUnit/PhpUnitMockShortWillReturnFixer.php
  tests/Fixer/PhpUnit/PhpUnitMockShortWillReturnFixerTest.php
Labels: RTM, feature, input required

#4350 StrictParamFixer - Don't detect functions in use statements
  src/Fixer/Strict/StrictParamFixer.php
  tests/Fixer/Strict/StrictParamFixerTest.php
Labels: RTM, bug

#4346 BracesFixer - Do not pull close tag onto same line as a comment
  src/Fixer/Basic/BracesFixer.php
  tests/Fixer/Basic/BracesFixerTest.php
Labels: RTM, bug
