Repository PHP-CS-Fixer/PHP-CS-Fixer, pull requests merged in 2019-10, with the labels that each got.

#4564 Move readme-update command to Section 3
  doc/COOKBOOK-FIXERS.md
Labels: RTM, topic/documentation

#4559 Allow 7.4snapshot to fail due to a bug on it
  .travis.yml
Labels: topic/tests

#4548 HeredocIndentationFixer - remove whitespace in empty lines
  src/Fixer/Whitespace/HeredocIndentationFixer.php
  tests/Fixer/Whitespace/HeredocIndentationFixerTest.php
Labels: RTM, kind/bug

#4546 DX: removing unnecessary variable initialization
  src/Fixer/PhpUnit/PhpUnitTestClassRequiresCoversFixer.php
Labels: kind/cleanup

#4490 Allow running if installed as project specific
  php-cs-fixer
Labels: topic/I/O

#4401 Add NullableTypeDeclarationForDefaultNullValueFixer
  README.rst
  src/Fixer/FunctionNotation/NullableTypeDeclarationForDefaultNullValueFixer.php
  tests/AutoReview/FixerFactoryTest.php
  tests/Fixer/FunctionNotation/NullableTypeDeclarationForDefaultNullValueFixerTest.php
  tests/Fixtures/Integration/priority/nullable_type_declaration_for_default_null_value,no_unreachable_default_argument_value.test
Labels: RTM, kind/feature

#4275 Issue #4274: Let lowercase_constants directive to be configurable.
  README.rst
  src/Fixer/Casing/ConstantCaseFixer.php
  src/Fixer/Casing/LowercaseConstantsFixer.php
  src/RuleSet.php
  tests/Fixer/Casing/ConstantCaseFixerTest.php
  tests/RuleSetTest.php
Labels: RTM, kind/feature

#3995 Change default config of native_function_invocation
  README.rst
  UPGRADE-v3.md
  src/Fixer/FunctionNotation/NativeFunctionInvocationFixer.php
  tests/Fixer/FunctionNotation/NativeFunctionInvocationFixerTest.php
Labels: RTM, kind/BC break, kind/enhancement

#4570 Command::execute() should always return an integer
  src/Console/Command/DescribeCommand.php
  src/Console/Command/ReadmeCommand.php
  src/Console/Command/SelfUpdateCommand.php
Labels: RTM, kind/enhancement

#4500 NoSuperfluousPhpdocTags - Add remove_inheritdoc option
  README.rst
  src/Fixer/Phpdoc/NoSuperfluousPhpdocTagsFixer.php
  tests/Fixer/Phpdoc/NoSuperfluousPhpdocTagsFixerTest.php
Labels: RTM, kind/feature

#4531 PhpdocAlignFixer - add "property-read" and "property-write" to allowed tags
  README.rst
  src/Fixer/Phpdoc/PhpdocAlignFixer.php
  tests/Fixer/Phpdoc/PhpdocAlignFixerTest.php
Labels: RTM, kind/feature

#4577 Fix command exit code on lint error after fixing fix.
  README.rst
  src/Console/Command/FixCommand.php
  src/Console/Command/FixCommandExitStatusCalculator.php
  src/Fixer/FunctionNotation/VoidReturnFixer.php
  tests/Console/Command/FixCommandExitStatusCalculatorTest.php
Labels: RTM, kind/bug

#4534 MbStrFunctionsFixer - Add "str_split" => "mb_str_split" mapping [PHP7.4]
  src/Fixer/Alias/MbStrFunctionsFixer.php
  tests/Fixer/Alias/MbStrFunctionsFixerTest.php
Labels: RTM, kind/enhancement

#4518 PhpUnitNoExpectationAnnotationFixer - fix handling expect empty exception message
  src/Fixer/PhpUnit/PhpUnitNoExpectationAnnotationFixer.php
  tests/Fixer/PhpUnit/PhpUnitNoExpectationAnnotationFixerTest.php
Labels: RTM, kind/bug

#4183 IndentationTypeFixer - fix handling 2 spaces indent
  src/Fixer/Whitespace/IndentationTypeFixer.php
  tests/Fixer/Whitespace/IndentationTypeFixerTest.php
Labels: RTM, kind/bug

#4033 Raise deprecation warnings on usage of deprecated aliases
  src/FixerConfiguration/FixerConfigurationResolver.php
  tests/FixerConfiguration/FixerConfigurationResolverTest.php
Labels: RTM, kind/enhancement

#4573 CombineConsecutiveIssetsFixer - fix stop based on precedence
  README.rst
  src/Console/Command/DescribeCommand.php
  src/Console/Command/HelpCommand.php
  src/Console/Output/ErrorOutput.php
  src/Fixer/ConstantNotation/NativeConstantInvocationFixer.php
  src/Fixer/LanguageConstruct/CombineConsecutiveIssetsFixer.php
  src/Fixer/StringNotation/EscapeImplicitBackslashesFixer.php
  tests/Fixer/LanguageConstruct/CombineConsecutiveIssetsFixerTest.php
  tests/Smoke/PharTest.php
Labels: kind/bug

#4505 NoSuperfluousPhpdocTagsFixer - allow params that aren't on the signature
  README.rst
  src/Fixer/Phpdoc/NoSuperfluousPhpdocTagsFixer.php
  tests/Fixer/Phpdoc/NoSuperfluousPhpdocTagsFixerTest.php
Labels: RTM, kind/feature

#4000 FinalStaticAccessFixer - Introduction
  README.rst
  src/Fixer/ClassNotation/FinalStaticAccessFixer.php
  tests/AutoReview/FixerFactoryTest.php
  tests/Fixer/ClassNotation/FinalStaticAccessFixerTest.php
  tests/Fixtures/Integration/priority/final_internal_class,final_static_access.test
  tests/Fixtures/Integration/priority/php_unit_test_case_static_method_calls,final_static_access.test
Labels: RTM, kind/feature

#4580 Add suport for true/false return type hints.
  src/Fixer/FunctionNotation/PhpdocToReturnTypeFixer.php
  tests/AutoReview/FixerFactoryTest.php
  tests/Fixer/FunctionNotation/PhpdocToReturnTypeFixerTest.php
  tests/Fixtures/Integration/priority/phpdoc_types,phpdoc_to_return_type.test
Labels: kind/bug

#4517 Verify PCRE pattern before use
  src/Preg.php
  tests/PregTest.php
Labels: RTM, kind/enhancement

#4566 Update symfony ruleset
  README.rst
  src/RuleSet.php
  tests/Fixtures/Integration/misc/PHP7.test
  tests/Fixtures/Integration/set/@Symfony.test-out.php
  tests/Fixtures/Integration/set/@Symfony_whitespaces.test-out.php
Labels: RTM, kind/enhancement

#4581 FunctionsAnalyzer: fix for comment in type
  src/Tokenizer/Analyzer/FunctionsAnalyzer.php
  tests/Tokenizer/Analyzer/FunctionsAnalyzerTest.php
Labels: RTM, kind/bug

#4355 GlobalNamespaceImportFixer - Introduction
  README.rst
  src/Fixer/ConstantNotation/NativeConstantInvocationFixer.php
  src/Fixer/FunctionNotation/NativeFunctionInvocationFixer.php
  src/Fixer/Import/GlobalNamespaceImportFixer.php
  src/Tokenizer/Analyzer/ClassyAnalyzer.php
  tests/AutoReview/FixerFactoryTest.php
  tests/Fixer/Import/GlobalNamespaceImportFixerTest.php
  tests/Fixtures/Integration/priority/global_namespace_import,no_unused_imports.test
  tests/Fixtures/Integration/priority/global_namespace_import,ordered_imports.test
  tests/Fixtures/Integration/priority/native_constant_invocation,global_namespace_import.test
  tests/Fixtures/Integration/priority/native_function_invocation,global_namespace_import.test
  tests/Tokenizer/Analyzer/ClassyAnalyzerTest.php
Labels: RTM, kind/feature
