Repository PHP-CS-Fixer/PHP-CS-Fixer, pull requests merged in 2019-07, with the labels that each got.

#4453 Fix preg_match error on 7.4snapshot
  src/Fixer/ControlStructure/NoSuperfluousElseifFixer.php
Labels: bug

#4461 IsNullFixer - fix null coalescing operator handling
  src/Fixer/LanguageConstruct/IsNullFixer.php
  tests/Fixer/LanguageConstruct/IsNullFixerTest.php
Labels: bug

#4463 Add apostrophe to possessive "team's"
  README.rst
  src/Console/Command/ReadmeCommand.php
Labels: RTM, documentation

#4432 DX: remove empty sets from RuleSet
  .php_cs.dist
  UPGRADE-v3.md
  src/RuleSet.php
  tests/RuleSetTest.php
Labels: BC break, RTM

#4471 ReadmeCommandTest - use CommandTester
  tests/Console/Command/ReadmeCommandTest.php
Labels: tests / CI

#4421 FunctionTypehintSpaceFixer - Ensure single space between type declaration and parameter
  README.rst
  src/Fixer/FunctionNotation/FunctionTypehintSpaceFixer.php
  tests/Fixer/FunctionNotation/FunctionTypehintSpaceFixerTest.php
Labels: RTM, bug

#4467 ToolInfo - fix access to reference without checking existence
  src/ToolInfo.php
Labels: bug

#4472 Fix non-static closure unbinding this on PHP 7.4
  src/Fixer/ControlStructure/NoBreakCommentFixer.php
Labels: RTM, bug

#4384 MethodArgumentSpaceFixer - fix for on_multiline:ensure_fully_multiline with trailing comma in function call
  src/Fixer/FunctionNotation/MethodArgumentSpaceFixer.php
  tests/Fixer/FunctionNotation/MethodArgumentSpaceFixerTest.php
Labels: bug

#4436 MethodArgumentSpaceFixer - handle misplaced )
  src/Fixer/FunctionNotation/MethodArgumentSpaceFixer.php
  tests/Fixer/FunctionNotation/MethodArgumentSpaceFixerTest.php
  tests/Fixer/FunctionNotation/NativeFunctionInvocationFixerTest.php
  tests/Fixer/Phpdoc/NoBlankLinesAfterPhpdocFixerTest.php
  tests/Fixer/Strict/StrictParamFixerTest.php
Labels: bug

#4404 FileLintingIterator - fix current value on end/invalid
  src/Runner/FileLintingIterator.php
  tests/AutoReview/ProjectCodeTest.php
  tests/Runner/FileLintingIteratorTest.php
Labels: bug

#4385 CommentToPhpdocFixer - allow to ignore tags
  README.rst
  src/Fixer/Comment/CommentToPhpdocFixer.php
  tests/Fixer/Comment/CommentToPhpdocFixerTest.php
Labels: RTM, feature
