Repository PHP-CS-Fixer/PHP-CS-Fixer, pull requests merged in 2019-01, with the labels that each got.

#4190 Travis CI - fix config
  .travis.yml
Labels: tests / CI

#4194 [7.3] NativeFunctionInvocationFixer - add tests for PHP 7.3
  tests/Fixer/FunctionNotation/NativeFunctionInvocationFixerTest.php
  tests/Fixtures/Integration/misc/PHP7_3.test
Labels: enhancement

#4181 MultilineCommentOpeningClosingFixer - fix handling empty comment
  src/Fixer/Comment/MultilineCommentOpeningClosingFixer.php
  tests/Fixer/Comment/MultilineCommentOpeningClosingFixerTest.php
Labels: bug

#4195 [7.3] SetTypeToCastFixer - support PHP 7.3
  src/Fixer/Alias/SetTypeToCastFixer.php
  tests/Fixer/Alias/SetTypeToCastFixerTest.php
  tests/Fixtures/Integration/misc/PHP7_3.test
Labels: enhancement

#4197 [7.3] StrictParamFixer - support PHP 7.3
  src/Fixer/Strict/StrictParamFixer.php
  tests/Fixer/Strict/StrictParamFixerTest.php
  tests/Fixtures/Integration/misc/PHP7_3.test
Labels: enhancement

#3881 Add PhpdocVarAnnotationCorrectOrderFixer
  README.rst
  src/Fixer/Phpdoc/PhpdocVarAnnotationCorrectOrderFixer.php
  src/RuleSet.php
  tests/Fixer/Alias/NoAliasFunctionsFixerTest.php
  tests/Fixer/Phpdoc/PhpdocVarAnnotationCorrectOrderFixerTest.php
Labels: feature

#4102 Add NoUnsetCastFixer
  README.rst
  src/Fixer/CastNotation/NoUnsetCastFixer.php
  src/RuleSet.php
  tests/Fixer/CastNotation/NoUnsetCastFixerTest.php
Labels: feature

#4198 [7.3] PowToExponentiationFixer - adding to PHP7.3 integration test
  tests/Fixtures/Integration/misc/PHP7_3.test
Labels: RTM, enhancement

#4200 [7.3] ModernizeTypesCastingFixer - support PHP 7.3
  src/Fixer/CastNotation/ModernizeTypesCastingFixer.php
  tests/Fixer/CastNotation/ModernizeTypesCastingFixerTest.php
  tests/Fixtures/Integration/misc/PHP7_3.test
Labels: RTM, enhancement

#4202 [7.3] ErrorSuppressionFixer - support PHP 7.3
  src/Fixer/LanguageConstruct/ErrorSuppressionFixer.php
  tests/Fixer/LanguageConstruct/ErrorSuppressionFixerTest.php
  tests/Fixer/LanguageConstruct/SilencedDeprecationErrorFixerTest.php
  tests/Fixtures/Integration/misc/PHP7_3.test
Labels: RTM, enhancement

#4201 [7.3] MultilineWhitespaceBeforeSemicolonsFixer - add tests for PHP 7.3
  tests/Fixer/Semicolon/MultilineWhitespaceBeforeSemicolonsFixerTest.php
  tests/Fixtures/Integration/misc/PHP7_3.test
Labels: enhancement

#4208 [7.3] NativeFunctionCasingFixerTest - tests for 7.3
  tests/Fixer/Casing/NativeFunctionCasingFixerTest.php
Labels: enhancement

#4207 [7.3] RandomApiMigrationFixerTest - tests for 7.3
  tests/Fixer/Alias/RandomApiMigrationFixerTest.php
Labels: enhancement

#4206 DX: enable multiline_whitespace_before_semicolons
  README.rst
  src/Console/ConfigurationResolver.php
  src/RuleSet.php
  tests/Console/ConfigurationResolverTest.php
  tests/FixerDefinition/VersionSpecificCodeSampleTest.php
  tests/Runner/RunnerTest.php
  tests/Test/AbstractFixerTestCase.php
  tests/Test/AbstractIntegrationTestCase.php
Labels: cleanup

#4216 Psr4Fixer - fix for multiple classy elements in file
  src/Fixer/Basic/Psr4Fixer.php
  tests/Fixer/Basic/Psr0FixerTest.php
  tests/Fixer/Basic/Psr4FixerTest.php
Labels: bug

#4217 Psr0Fixer - class with anonymous class
  src/Fixer/Basic/Psr0Fixer.php
  tests/Fixer/Basic/Psr0FixerTest.php
Labels: bug

#4199 [7.3] MethodChainingIndentationFixer - add tests for PHP 7.3
  tests/Fixer/Whitespace/MethodChainingIndentationFixerTest.php
  tests/Fixtures/Integration/misc/PHP7_3.test
Labels: enhancement

#4211 [7.3] PhpUnitDedicateAssertFixer - support PHP 7.3
  src/Fixer/PhpUnit/PhpUnitDedicateAssertFixer.php
  tests/Fixer/PhpUnit/PhpUnitDedicateAssertFixerTest.php
  tests/Fixtures/Integration/misc/PHP7_3.test
Labels: enhancement

#4222 [7.3] PhpUnitExpectationFixer - support PHP 7.3
  src/Fixer/PhpUnit/PhpUnitExpectationFixer.php
  tests/Fixer/PhpUnit/PhpUnitExpectationFixerTest.php
  tests/Fixtures/Integration/misc/PHP7_3.test
Labels: enhancement

#4223 [7.3] PhpUnitMockFixer - add tests for PHP 7.3
  tests/Fixer/PhpUnit/PhpUnitMockFixerTest.php
  tests/Fixtures/Integration/misc/PHP7_3.test
Labels: enhancement

#4213 [7.3] PHP7.3 integration tests
  tests/Fixtures/Integration/misc/PHP7_3.test
Labels: enhancement

#4209 [7.3] PhpUnitStrictFixerTest - tests for 7.3
  tests/Fixer/PhpUnit/PhpUnitStrictFixerTest.php
  tests/Fixtures/Integration/misc/PHP7_3.test
Labels: enhancement

#4205 DX: PhpdocAlignFixer - refactor to use DocBlock
  src/Fixer/Phpdoc/PhpdocAlignFixer.php
Labels: cleanup

#4214 [7.3] NoUnsetOnPropertyFixerTest - tests for 7.3
  src/Fixer/LanguageConstruct/NoUnsetOnPropertyFixer.php
  tests/Fixer/LanguageConstruct/NoUnsetOnPropertyFixerTest.php
  tests/Fixtures/Integration/misc/PHP7_3.test
Labels: enhancement

#4210 [7.3] PhpUnitConstructFixer - add test for PHP 7.3
  tests/Fixer/PhpUnit/PhpUnitConstructFixerTest.php
Labels: enhancement

#4193 [7.3] CombineNestedDirnameFixer - support PHP 7.3
  src/Fixer/FunctionNotation/CombineNestedDirnameFixer.php
  tests/AutoReview/FixerFactoryTest.php
  tests/Fixer/FunctionNotation/CombineNestedDirnameFixerTest.php
  tests/Fixtures/Integration/misc/PHP7_3.test
  tests/Fixtures/Integration/misc/combine_nested_dirname,no_trailing_whitespace.test
  tests/Fixtures/Integration/misc/combine_nested_dirname,no_whitespace_in_blank_line.test
  tests/Fixtures/Integration/priority/combine_nested_dirname,method_argument_space.test
Labels: enhancement

#4219 NativeFunctionCasingFixer - handle T_RETURN_REF
  src/Fixer/Casing/NativeFunctionCasingFixer.php
  tests/Fixer/Casing/NativeFunctionCasingFixerTest.php
Labels: bug

#4229 IsNullFixer - fix parenthesis not closed
  src/Fixer/LanguageConstruct/IsNullFixer.php
  tests/Fixer/LanguageConstruct/IsNullFixerTest.php
Labels: bug

#4224 FunctionToConstantFixer - handle T_RETURN_REF
  src/Fixer/LanguageConstruct/FunctionToConstantFixer.php
  tests/Fixer/LanguageConstruct/FunctionToConstantFixerTest.php
Labels: bug

#4220 NativeFunctionInvocationFixer - namespaced strict to remove backslash
  src/Fixer/FunctionNotation/NativeFunctionInvocationFixer.php
  tests/Fixer/FunctionNotation/NativeFunctionInvocationFixerTest.php
Labels: bug

#4230 [7.3] IsNullFixer - fix trailing comma
  src/Fixer/LanguageConstruct/IsNullFixer.php
  tests/Fixer/LanguageConstruct/IsNullFixerTest.php
Labels: enhancement

#4232 DX: remove Utils::splitLines
  src/DocBlock/DocBlock.php
  src/Utils.php
  tests/UtilsTest.php
Labels: cleanup

#4234 [7.3] Test that "LITERAL instanceof X" is valid
  tests/Fixtures/Integration/misc/PHP7_3.test
Labels: enhancement

#4254 PhpUnitDedicateAssertFixer - fix for count with additional operations
  src/Fixer/PhpUnit/PhpUnitDedicateAssertFixer.php
  tests/Fixer/PhpUnit/PhpUnitDedicateAssertFixerTest.php
Labels: bug

#4262 FixCommand - fix help
  .gitattributes
  .travis.yml
  phpunit.xml.dist
  tests/Smoke/AbstractSmokeTest.php
  tests/Smoke/CiIntegrationTest.php
  tests/Smoke/InstallViaComposerTest.php
  tests/Smoke/PharTest.php
  tests/Smoke/StdinTest.php
Labels: bug
