Repository PHP-CS-Fixer/PHP-CS-Fixer, pull requests merged in 2019-04, with the labels that each got.

#4357 Fix short list syntax detection.
  src/Tokenizer/Transformer/BraceClassInstantiationTransformer.php
  src/Tokenizer/Transformer/CurlyBraceTransformer.php
  src/Tokenizer/Transformer/SquareBraceTransformer.php
  src/Tokenizer/Transformer/UseTransformer.php
  tests/Fixer/ListNotation/ListSyntaxFixerTest.php
  tests/Tokenizer/Transformer/CurlyBraceTransformerTest.php
  tests/Tokenizer/Transformer/SquareBraceTransformerTest.php
Labels: RTM, bug

#4353 Add more priority tests
  tests/AutoReview/FixerFactoryTest.php
  tests/Fixer/Phpdoc/PhpdocSeparationFixerTest.php
  tests/Fixer/Phpdoc/PhpdocSummaryFixerTest.php
  tests/Fixtures/Integration/priority/class_attributes_separation,indentation_type.test
  tests/Fixtures/Integration/priority/method_separation,indentation_type.test
Labels: cleanup, tests / CI

#4351 code grooming
  src/AbstractNoUselessElseFixer.php
  src/Cache/SignatureInterface.php
  src/Console/Command/DescribeCommand.php
  src/Fixer/Basic/NonPrintableCharacterFixer.php
  src/Fixer/Phpdoc/PhpdocOrderFixer.php
  src/Fixer/Phpdoc/PhpdocSummaryFixer.php
  src/FixerFactory.php
  src/Tokenizer/Transformers.php
  tests/Fixtures/Integration/set/@PSR2.test-in.php
  tests/Fixtures/Integration/set/@PSR2.test-out.php
  tests/Fixtures/Integration/set/@PSR2_whitespaces.test-in.php
  tests/Fixtures/Integration/set/@PSR2_whitespaces.test-out.php
  tests/Test/AbstractFixerTestCase.php
  tests/Test/AbstractIntegrationTestCase.php
  tests/Tokenizer/Transformer/BraceClassInstantiationTransformerTest.php
Labels: cleanup

#4337 PhpUnitTestCaseStaticMethodCallsFixer - prepare for PHPUnit 8
  src/Fixer/PhpUnit/PhpUnitTestCaseStaticMethodCallsFixer.php
Labels: RTM, feature

#4245 LineEndingFixer - BracesFixer - Priority
  src/Fixer/Basic/BracesFixer.php
  src/Fixer/ControlStructure/NoAlternativeSyntaxFixer.php
  src/Fixer/Whitespace/ArrayIndentationFixer.php
  tests/AutoReview/FixerFactoryTest.php
  tests/Fixtures/Integration/priority/line_ending,braces.test
  tests/Fixtures/Integration/priority/line_ending,braces.test-in.php
  tests/Fixtures/Integration/priority/line_ending,braces.test-out.php
Labels: tests / CI

#4103 NoExtraBlankLinesFixer - fix candidate detection
  src/Fixer/Whitespace/NoExtraBlankLinesFixer.php
  tests/Fixer/Whitespace/NoExtraBlankLinesFixerTest.php
Labels: bug

#4288 Add Gitlab Reporter
  src/Report/GitlabReporter.php
  tests/Console/ConfigurationResolverTest.php
  tests/Report/GitlabReporterTest.php
  tests/Report/ReporterFactoryTest.php
  tests/TextDiffTest.php
Labels: I/O, RTM, feature, waiting review

#4360 Add gitlab as output format in the README/help doc.
  README.rst
  src/Console/Command/HelpCommand.php
Labels: documentation

#4325 Use lowercase mikey179/vfsStream in composer.json
  composer.json
Labels: RTM, cleanup

#4368 Fixed TypeShortNameResolverTest::testResolver
  tests/Tokenizer/Resolver/TypeShortNameResolverTest.php
Labels: RTM, tests / CI

#4366 Unset the auxillary variable $a
  php-cs-fixer
Labels: RTM, cleanup

#4365 Fix output escaping of diff for text format when line is not changed
  src/Differ/DiffConsoleFormatter.php
  tests/Fixtures/FixCommand/TextDiffTestInput.php
  tests/TextDiffTest.php
Labels: I/O, bug

#3942 SimpleToComplexStringVariableFixer - Introduction
  README.rst
  src/Console/Output/ErrorOutput.php
  src/DocBlock/Tag.php
  src/Fixer/ControlStructure/NoBreakCommentFixer.php
  src/Fixer/PhpUnit/PhpUnitInternalClassFixer.php
  src/Fixer/PhpUnit/PhpUnitNoExpectationAnnotationFixer.php
  src/Fixer/PhpUnit/PhpUnitTestAnnotationFixer.php
  src/Fixer/StringNotation/SimpleToComplexStringVariableFixer.php
  src/RuleSet.php
  tests/AutoReview/FixerFactoryTest.php
  tests/AutoReview/ProjectCodeTest.php
  tests/Console/Output/ErrorOutputTest.php
  tests/Fixer/Alias/NoAliasFunctionsFixerTest.php
  tests/Fixer/ClassNotation/ProtectedToPrivateFixerTest.php
  tests/Fixer/ConstantNotation/NativeConstantInvocationFixerTest.php
  tests/Fixer/PhpUnit/PhpUnitStrictFixerTest.php
  tests/Fixer/StringNotation/ExplicitStringVariableFixerTest.php
  tests/Fixer/StringNotation/SimpleToComplexStringVariableFixerTest.php
  tests/Fixtures/Integration/priority/explicit_string_variable,simple_to_complex_string_variable.test
  tests/Smoke/CiIntegrationTest.php
  tests/Smoke/InstallViaComposerTest.php
  tests/Smoke/StdinTest.php
  tests/Test/AbstractFixerTestCase.php
Labels: feature, waiting review

#4336 Collect coverage with PCOV
  .travis.yml
  composer.json
Labels: RTM, tests / CI

#4370 PhpUnitConstructFixer - Fix handle different casing
  src/Fixer/PhpUnit/PhpUnitConstructFixer.php
  tests/Fixer/PhpUnit/PhpUnitConstructFixerTest.php
Labels: bug

#4379 ExplicitStringVariableFixer - add test case for variable as an array key
  src/Fixer/StringNotation/ExplicitStringVariableFixer.php
  tests/Fixer/StringNotation/ExplicitStringVariableFixerTest.php
Labels: RTM, bug

#4380 PHP7.4 - Add "str_split" => "mb_str_split" mapping.
  src/Fixer/Alias/MbStrFunctionsFixer.php
  tests/Fixer/Alias/MbStrFunctionsFixerTest.php
Labels: 7.4, enhancement

#4381 PHP7.4 - Add support for magic methods (un)serialize.
  src/Fixer/Casing/MagicMethodCasingFixer.php
  tests/Fixer/Casing/MagicMethodCasingFixerTest.php
Labels: 7.4, enhancement
