Repository PHP-CS-Fixer/PHP-CS-Fixer, pull requests merged in 2019-12, with the labels that each got.

#4682 Fix handling array type declaration in properties
  src/Fixer/ClassNotation/ClassAttributesSeparationFixer.php
  src/Fixer/ClassNotation/SingleClassElementPerStatementFixer.php
  tests/Fixer/ClassNotation/ClassAttributesSeparationFixerTest.php
  tests/Fixer/ClassNotation/NoNullPropertyInitializationFixerTest.php
  tests/Fixer/ClassNotation/OrderedClassElementsFixerTest.php
  tests/Fixer/ClassNotation/ProtectedToPrivateFixerTest.php
  tests/Fixer/ClassNotation/SingleClassElementPerStatementFixerTest.php
  tests/Fixer/Naming/NoHomoglyphNamesFixerTest.php
  tests/Fixer/Phpdoc/PhpdocToCommentFixerTest.php
  tests/Tokenizer/TokensAnalyzerTest.php
Labels: RTM, kind/bug

#4688 TokensAnalyzer::isConstantInvocation - Fix detection for fully qualified return type
  src/Tokenizer/TokensAnalyzer.php
  tests/Tokenizer/TokensAnalyzerTest.php
Labels: RTM, kind/bug

#4661 ExplicitStringVariableFixer - variables pair if one is already explicit
  src/Fixer/StringNotation/ExplicitStringVariableFixer.php
  tests/Fixer/StringNotation/ExplicitStringVariableFixerTest.php
Labels: RTM, kind/bug

#4678 TokensAnalyzer::isConstantInvocation - fix for importing multiple classes with single "use"
  src/Tokenizer/TokensAnalyzer.php
  tests/Tokenizer/TokensAnalyzerTest.php
Labels: RTM, kind/bug

#4690 PhpdocVarAnnotationCorrectOrderFixer - fix for multiline `@var` without type
  src/Fixer/Phpdoc/PhpdocVarAnnotationCorrectOrderFixer.php
  tests/Fixer/Phpdoc/PhpdocVarAnnotationCorrectOrderFixerTest.php
Labels: RTM, kind/bug

#4693 Increase Travis CI Git clone depth
  .travis.yml
Labels: topic/tests

#4689 DeclareStrictTypesFixer - fix for "strict_types" set to "0"
  src/Fixer/Strict/DeclareStrictTypesFixer.php
  tests/Fixer/Strict/DeclareStrictTypesFixerTest.php
Labels: RTM, kind/bug

#4697 Remove deprecated no_short_echo_tag rule
  README.rst
  UPGRADE-v3.md
  src/Fixer/Alias/NoMixedEchoPrintFixer.php
  src/Fixer/PhpTag/NoShortEchoTagFixer.php
  tests/AutoReview/FixerFactoryTest.php
  tests/Fixer/PhpTag/NoShortEchoTagFixerTest.php
  tests/Fixtures/Integration/priority/no_mixed_echo_print,no_short_echo_tag.test
Labels: RTM, kind/cleanup
