Repository PHP-CS-Fixer/PHP-CS-Fixer, pull requests merged in 2020-03, with the labels that each got.

#4857 Fixed the unit tests
  tests/Fixer/PhpUnit/PhpUnitNoExpectationAnnotationFixerTest.php
Labels: topic/tests

#4784 Travis CI - Use multiple keyservers
  dev-tools/install.sh
Labels: topic/tests

#4644 Docs: add info about "-vv..."
  README.rst
  src/Console/Command/HelpCommand.php
Labels: kind/enhancement, topic/documentation

#4715 Enhancement: Install ergebnis/composer-normalize via Phive
  .travis.yml
  dev-tools/composer.json
  dev-tools/install.sh
  dev-tools/phive.xml
Labels: kind/enhancement

#4865 Use latest xcode image
  .circleci/config.yml
Labels: kind/enhancement, topic/tests

#4871 NoExtraBlankLinesFixer - handle cases on same line
  src/Fixer/Whitespace/NoExtraBlankLinesFixer.php
  tests/Fixer/Whitespace/NoExtraBlankLinesFixerTest.php
  tests/Tokenizer/Analyzer/CommentsAnalyzerTest.php
Labels: RTM, kind/bug

#4872 Update RuleSet SF and PHP-CS-Fixer with new config for `no_extra_blan…
  README.rst
  src/RuleSet.php
  tests/Fixtures/Integration/set/@PHP74Migration-risky.test
  tests/Fixtures/Integration/set/@PHP74Migration-risky.test-in.php
  tests/Fixtures/Integration/set/@PHP74Migration-risky.test-out.php
  tests/Fixtures/Integration/set/@PHP74Migration.test
  tests/Fixtures/Integration/set/@PHP74Migration.test-in.php
  tests/Fixtures/Integration/set/@PHP74Migration.test-out.php
  tests/RuleSetTest.php
Labels: kind/enhancement
