Repository PHP-CS-Fixer/PHP-CS-Fixer, pull requests merged in 2020-05, with the labels that each got.

#4931 DX: add test to ensure each target version in PhpUnitTargetVersion has its set in RuleSet
  tests/RuleSetTest.php
Labels: RTM, topic/tests

#4944 Fix grammar
  README.rst
  src/Console/Command/ReadmeCommand.php
Labels: topic/documentation

#4934 YodaStyleFixer - fix for conditions weird are
  src/Fixer/ControlStructure/YodaStyleFixer.php
  tests/Fixer/ControlStructure/YodaStyleFixerTest.php
Labels: kind/bug

#4940 Reject empty path
  src/Console/ConfigurationResolver.php
  tests/Console/ConfigurationResolverTest.php
Labels: kind/enhancement, topic/I/O

#4946 Allow "const" option on PHP <7.1
  src/Fixer/ClassNotation/VisibilityRequiredFixer.php
  tests/Fixer/ClassNotation/VisibilityRequiredFixerTest.php
Labels: kind/enhancement

#4949 Fixed build readme on Windows fails if using Git Bash (Mintty)
  CONTRIBUTING.md
Labels: topic/documentation

#4904 Increase PHPStan level to 8 with strict rules
  dev-tools/composer.json
  phpstan-baseline.neon
  phpstan.neon
Labels: RTM, topic/tests

#4929 YodaStyleFixer - handling equals empty array
  src/Fixer/ControlStructure/YodaStyleFixer.php
  tests/AutoReview/ProjectCodeTest.php
  tests/Fixer/ControlStructure/YodaStyleFixerTest.php
Labels: kind/bug

#4930 DX: ensure PhpUnitNamespacedFixer handles all classes
  tests/Fixer/PhpUnit/PhpUnitNamespacedFixerTest.php
Labels: topic/tests

#4954 Config - Trim path
  src/Console/ConfigurationResolver.php
  tests/Console/ConfigurationResolverTest.php
Labels: RTM, kind/enhancement, topic/I/O

#4957 DX: Check trailing spaces in project files only
  check_trailing_spaces.sh
Labels: kind/enhancement, topic/tests

#4958 OrderedImportsFixer - fix for trailing comma in group
  src/Fixer/Import/OrderedImportsFixer.php
  tests/Fixer/Import/OrderedImportsFixerTest.php
Labels: RTM, kind/bug

#4959 BlankLineBeforeStatementFixer - handle comment case
  src/Fixer/Whitespace/BlankLineBeforeStatementFixer.php
  tests/AutoReview/ComposerTest.php
  tests/Fixer/Whitespace/BlankLineBeforeStatementFixerTest.php
Labels: RTM, kind/bug

#4962 MethodArgumentSpaceFixer - must run after MethodChainingIndentationFixer
  src/Fixer/FunctionNotation/MethodArgumentSpaceFixer.php
  src/Fixer/Whitespace/MethodChainingIndentationFixer.php
  tests/AutoReview/FixerFactoryTest.php
  tests/Fixtures/Integration/priority/method_chaining_indentation,method_argument_space.test
Labels: kind/bug

#4908 PhpUnitExpectationFixer - update for Phpunit 8.4
  README.rst
  src/Fixer/PhpUnit/PhpUnitExpectationFixer.php
  src/Fixer/PhpUnit/PhpUnitTargetVersion.php
  src/RuleSet.php
  tests/Fixer/PhpUnit/PhpUnitExpectationFixerTest.php
  tests/RuleSetTest.php
Labels: RTM, kind/feature

#4947 NativeConstantInvocation - Add "PHP_INT_SIZE" to SF rule set
  src/RuleSet.php
Labels: RTM, kind/feature

#4964 Fix PHPStan baseline
  phpstan-baseline.neon
Labels: RTM, topic/tests

#4965 Fix PHPStan baseline
  phpstan-baseline.neon
Labels: RTM, topic/tests

#4975 Revert PHPStan level to 5
  dev-tools/composer.json
  phpstan-baseline.neon
  phpstan.neon
Labels: topic/tests

#4974 Minor: Fix typo
  tests/Fixer/PhpUnit/PhpUnitTestAnnotationFixerTest.php
Labels: RTM

#4976 Add instructions for PHPStan
  CONTRIBUTING.md
Labels: RTM, topic/documentation

#4982 Remove PHIVE
  .travis.yml
  dev-tools/.gitignore
  dev-tools/composer.json
  dev-tools/install.sh
  dev-tools/phive.xml
Labels: RTM, kind/cleanup, topic/tests

#4980 Introduce new issue templates
  .github/ISSUE_TEMPLATE
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/rule_request.md
  .github/ISSUE_TEMPLATE/support_question.md
Labels: RTM

#4948 Added describe command to readme
  README.rst
  src/Console/Command/HelpCommand.php
Labels: RTM, kind/enhancement, topic/documentation

#4973 DX: test "isRisky" method in fixer tests, not as auto review
  README.rst
  src/Fixer/FunctionNotation/PhpdocToReturnTypeFixer.php
  src/Fixer/Phpdoc/PhpdocAddMissingParamAnnotationFixer.php
  tests/AutoReview/FixerTest.php
  tests/Fixer/ConstantNotation/NativeConstantInvocationFixerTest.php
  tests/Fixer/FunctionNotation/NativeFunctionInvocationFixerTest.php
  tests/Test/AbstractFixerTestCase.php
Labels: RTM, kind/enhancement, topic/tests

#4981 Prevent error in CTTest::testConstants (for PHP8)
  tests/Tokenizer/CTTest.php
Labels: RTM, topic/tests

#4978 ArrayIndentationFixer - must run after MethodArgumentSpaceFixer
  src/Fixer/FunctionNotation/MethodArgumentSpaceFixer.php
  src/Fixer/Operator/BinaryOperatorSpacesFixer.php
  src/Fixer/Whitespace/ArrayIndentationFixer.php
  tests/AutoReview/FixerFactoryTest.php
  tests/Fixtures/Integration/misc/array_indentation,method_argument_space,method_chaining_indentation.test
  tests/Fixtures/Integration/priority/method_argument_space,array_indentation.test
Labels: RTM, kind/bug

#4919 PhpUnitTestAnnotationFixer - fix function starting with "test" and having lowercase letter after
  src/Fixer/PhpUnit/PhpUnitTestAnnotationFixer.php
  tests/Fixer/PhpUnit/PhpUnitTestAnnotationFixerTest.php
Labels: RTM, kind/bug
