Repository PHP-CS-Fixer/PHP-CS-Fixer, pull requests merged in 2020-11, with the labels that each got.

#5095 Annotation - fix for Windows line endings
  src/DocBlock/Annotation.php
  tests/DocBlock/AnnotationTest.php
  tests/Fixer/Phpdoc/PhpdocTypesFixerTest.php
Labels: kind/bug

#5221 NoSuperfluousPhpdocTagsFixer - fix for single line PHPDoc
  src/Fixer/Phpdoc/NoSuperfluousPhpdocTagsFixer.php
  tests/Fixer/Phpdoc/NoSuperfluousPhpdocTagsFixerTest.php
Labels: kind/bug

#5225 TernaryOperatorSpacesFixer - fix for alternative control structures
  src/Fixer/Operator/TernaryOperatorSpacesFixer.php
  tests/Fixer/Operator/TernaryOperatorSpacesFixerTest.php
Labels: kind/bug

#5232 PHP8 - throw expression support
  src/AbstractNoUselessElseFixer.php
  src/Fixer/ControlStructure/NoBreakCommentFixer.php
  src/Fixer/ControlStructure/NoSuperfluousElseifFixer.php
  src/Fixer/ControlStructure/NoUselessElseFixer.php
  tests/Fixer/ControlStructure/NoBreakCommentFixerTest.php
  tests/Fixer/ControlStructure/NoSuperfluousElseifFixerTest.php
  tests/Fixer/ControlStructure/NoUselessElseFixerTest.php
  tests/Fixer/ControlStructure/YodaStyleFixerTest.php
  tests/Fixer/Whitespace/NoExtraBlankLinesFixerTest.php
Labels: RTM, topic/PHP8

#5233 DX: simplify check_file_permissions.sh
  dev-tools/check_file_permissions.sh
Labels: kind/cleanup, topic/tests

#5235 ArrayIndentationFixer - fix for nested arrays
  src/Fixer/Whitespace/ArrayIndentationFixer.php
  tests/Fixer/Whitespace/ArrayIndentationFixerTest.php
Labels: RTM, kind/bug

#5239 PHP8 - Allow trailing comma in parameter list support
  tests/Fixer/ClassNotation/NoPhp4ConstructorFixerTest.php
  tests/Fixer/ClassNotation/SelfAccessorFixerTest.php
  tests/Fixer/FunctionNotation/FunctionDeclarationFixerTest.php
  tests/Tokenizer/Analyzer/FunctionsAnalyzerTest.php
  tests/Tokenizer/TokensAnalyzerTest.php
Labels: RTM, topic/PHP8, topic/tests

#5240 PHP8 - Allow trailing comma in parameter list support
  tests/Fixer/FunctionNotation/LambdaNotUsedImportFixerTest.php
  tests/Fixer/FunctionNotation/NullableTypeDeclarationForDefaultNullValueFixerTest.php
  tests/Fixer/FunctionNotation/RegularCallableCallFixerTest.php
Labels: RTM, topic/PHP8, topic/tests

#5252 Update RuleSets
  doc/ruleSets/PhpCsFixer.rst
  doc/ruleSets/Symfony.rst
  doc/rules/language_construct/single_space_after_construct.rst
  src/RuleSet/Sets/PHP80MigrationRiskySet.php
  src/RuleSet/Sets/PhpCsFixerSet.php
  src/RuleSet/Sets/SymfonySet.php
Labels: kind/enhancement

#5236 Improve handling of unavailable code samples
  dev-tools/doc.php
  src/Console/Command/DocumentationCommand.php
  src/Documentation/DocumentationGenerator.php
Labels: kind/enhancement

#5255 Tests: do not skip documentation test
  tests/AutoReview/DocumentationTest.php
Labels: topic/documentation, topic/tests

#5248 NoBreakCommentFixer - fix throw detect
  src/Fixer/ControlStructure/NoBreakCommentFixer.php
  tests/Fixer/ControlStructure/NoBreakCommentFixerTest.php
Labels: RTM, kind/bug

#5253 IO - fix cache info message
  .gitattributes
  src/Console/ConfigurationResolver.php
  tests/Console/ConfigurationResolverTest.php
  tests/Console/TestToolInfo.php
  tests/Smoke/InstallViaComposerTest.php
Labels: RTM, kind/bug, topic/I/O

#5263 PHP8 support
  .composer-require-checker.json
  doc/rules/alias/random_api_migration.rst
  src/Fixer/Alias/RandomApiMigrationFixer.php
  src/Tokenizer/Token.php
  src/Tokenizer/TokensAnalyzer.php
  tests/AutoReview/DocumentationTest.php
  tests/Fixer/Casing/LowercaseKeywordsFixerTest.php
  tests/Fixer/ClassNotation/SelfAccessorFixerTest.php
  tests/Fixer/ControlStructure/YodaStyleFixerTest.php
  tests/Fixer/Operator/NewWithBracesFixerTest.php
  tests/Test/AbstractTransformerTestCase.php
  tests/Tokenizer/Analyzer/FunctionsAnalyzerTest.php
  tests/Tokenizer/Transformer/BraceClassInstantiationTransformerTest.php
Labels: RTM, kind/enhancement, topic/PHP8

#5254 PHP8 - mixed type support
  src/Fixer/Casing/NativeFunctionTypeDeclarationCasingFixer.php
  src/Fixer/FunctionNotation/PhpdocToReturnTypeFixer.php
  tests/Fixer/Casing/NativeFunctionTypeDeclarationCasingFixerTest.php
  tests/Fixer/FunctionNotation/FunctionTypehintSpaceFixerTest.php
  tests/Fixer/FunctionNotation/PhpdocToReturnTypeFixerTest.php
  tests/Fixer/FunctionNotation/ReturnTypeDeclarationFixerTest.php
  tests/Fixer/Whitespace/NoSpacesInsideParenthesisFixerTest.php
Labels: RTM, kind/enhancement, topic/PHP8

#5250 SwitchAnalyzer - fix for semicolon after case/default
  src/Tokenizer/Analyzer/SwitchAnalyzer.php
  tests/Tokenizer/Analyzer/SwitchAnalyzerTest.php
Labels: RTM, kind/bug

#5261 Do not update Composer twice
  .travis.yml
Labels: topic/release, topic/tests

#5266 PhpUnitTestCaseStaticMethodCallsFixer - PHPUnit 9.x support
  src/Fixer/PhpUnit/PhpUnitTestCaseStaticMethodCallsFixer.php
Labels: RTM, kind/enhancement

#5267 Improve InstallViaComposerTest
  tests/Smoke/InstallViaComposerTest.php
Labels: RTM, kind/enhancement, topic/tests

#5251 PHP8 - match support
  doc/rules/language_construct/single_space_after_construct.rst
  src/Fixer/LanguageConstruct/SingleSpaceAfterConstructFixer.php
  tests/Fixer/LanguageConstruct/SingleSpaceAfterConstructFixerTest.php
Labels: RTM, kind/enhancement, topic/PHP8

#5264 CleanNamespaceFixer - Introduction
  doc/ruleSets/PHP80Migration.rst
  doc/ruleSets/Symfony.rst
  doc/rules/index.rst
  doc/rules/namespace_notation/clean_namespace.rst
  src/Fixer/NamespaceNotation/CleanNamespaceFixer.php
  src/RuleSet/Sets/PHP80MigrationSet.php
  src/RuleSet/Sets/SymfonySet.php
  tests/Fixer/NamespaceNotation/CleanNamespaceFixerTest.php
Labels: RTM, kind/feature, topic/PHP8

#5274 TernaryToNullCoalescingFixer - concat precedence fix
  phpstan.neon
  src/Fixer/Alias/PowToExponentiationFixer.php
  src/Fixer/Operator/TernaryToNullCoalescingFixer.php
  tests/Fixer/Alias/PowToExponentiationFixerTest.php
  tests/Fixer/Operator/TernaryToNullCoalescingFixerTest.php
  tests/Indicator/PhpUnitTestCaseIndicatorTest.php
Labels: kind/bug

#5276 PHP8 - add NoUnreachableDefaultArgumentValueFixer to risky set
  doc/ruleSets/PHP80MigrationRisky.rst
  doc/ruleSets/SymfonyRisky.rst
  doc/rules/class_notation/no_php4_constructor.rst
  doc/rules/function_notation/no_unreachable_default_argument_value.rst
  src/RuleSet/Sets/PHP80MigrationRiskySet.php
  src/RuleSet/Sets/SymfonyRiskySet.php
Labels: kind/enhancement, topic/PHP8

#5273 Fix PHPDoc line span fixer when property has array typehint
  src/Fixer/Phpdoc/PhpdocLineSpanFixer.php
  tests/Fixer/Phpdoc/PhpdocLineSpanFixerTest.php
Labels: kind/bug

#5275 remove not supported verbose options
  doc/usage.rst
  src/Console/Command/HelpCommand.php
Labels: RTM, kind/enhancement, topic/documentation

#5277 PHP8 - Constructor Property Promotion support
  src/Tokenizer/CT.php
  src/Tokenizer/Token.php
  src/Tokenizer/Transformer/ConstructorPromotionTransformer.php
  tests/Fixer/Casing/LowercaseKeywordsFixerTest.php
  tests/Fixer/ClassNotation/NoNullPropertyInitializationFixerTest.php
  tests/Fixer/ClassNotation/VisibilityRequiredFixerTest.php
  tests/Test/AbstractTransformerTestCase.php
  tests/Tokenizer/Transformer/ConstructorPromotionTransformerTest.php
Labels: kind/enhancement, topic/PHP8

#5278 PHP8 constructor property promotion support
  src/Fixer/LanguageConstruct/SingleSpaceAfterConstructFixer.php
  tests/Fixer/LanguageConstruct/SingleSpaceAfterConstructFixerTest.php
Labels: topic/PHP8

#5292 Disable blank issue template and expose community chat
  .github/ISSUE_TEMPLATE/config.yml
Labels: topic/documentation

#5293 Add documentation to "yoda_style" sniff to convert Yoda style to non-Yoda style
  doc/rules/control_structure/yoda_style.rst
  doc/rules/index.rst
  src/Fixer/ControlStructure/YodaStyleFixer.php
Labels: kind/enhancement, topic/documentation

#5308 Only run yamllint when a YAML file is changed
  .github/workflows/yaml.yml
  tests/AutoReview/CiConfigurationTest.php
Labels: kind/enhancement, topic/tests
