Repository PHP-CS-Fixer/PHP-CS-Fixer, pull requests merged in 2020-12, with the labels that each got.

#5302 SingleLineCommentStyleFixer - do not fix possible attributes (PHP8)
  src/Fixer/Comment/SingleLineCommentStyleFixer.php
  tests/Fixer/Comment/SingleLineCommentStyleFixerTest.php
Labels: RTM, kind/enhancement, topic/PHP8

#5311 OrderedClassElementsFixer - PHPUnit Bridge support
  src/Fixer/ClassNotation/OrderedClassElementsFixer.php
  tests/Fixer/ClassNotation/OrderedClassElementsFixerTest.php
Labels: kind/enhancement

#5280 NoUselessSprintfFixer - Introduction
  doc/ruleSets/SymfonyRisky.rst
  doc/rules/function_notation/no_useless_sprintf.rst
  doc/rules/index.rst
  src/Fixer/Casing/NativeFunctionCasingFixer.php
  src/Fixer/Comment/CommentToPhpdocFixer.php
  src/Fixer/FunctionNotation/MethodArgumentSpaceFixer.php
  src/Fixer/FunctionNotation/NoUselessSprintfFixer.php
  src/Fixer/Whitespace/NoExtraBlankLinesFixer.php
  src/Fixer/Whitespace/NoSpacesInsideParenthesisFixer.php
  src/RuleSet/Sets/SymfonyRiskySet.php
  tests/AutoReview/FixerFactoryTest.php
  tests/Fixer/FunctionNotation/NoUselessSprintfFixerTest.php
  tests/Fixtures/Integration/priority/no_useless_sprintf,method_argument_space.test
  tests/Fixtures/Integration/priority/no_useless_sprintf,no_extra_blank_lines.test
  tests/Fixtures/Integration/priority/no_useless_sprintf,no_spaces_inside_parenthesis.test
Labels: RTM, kind/feature

#5284 PHP8 - Attribute support
  doc/ruleSets/SymfonyRisky.rst
  doc/rules/basic/non_printable_character.rst
  doc/rules/language_construct/single_space_after_construct.rst
  src/Fixer/ClassNotation/ClassAttributesSeparationFixer.php
  src/Fixer/ClassNotation/OrderedTraitsFixer.php
  src/Fixer/LanguageConstruct/SingleSpaceAfterConstructFixer.php
  src/Fixer/NamespaceNotation/CleanNamespaceFixer.php
  src/Fixer/PhpTag/EchoTagSyntaxFixer.php
  src/RuleSet/Sets/SymfonyRiskySet.php
  tests/AutoReview/DocumentationTest.php
  tests/Fixer/ClassNotation/ClassAttributesSeparationFixerTest.php
  tests/Fixer/FunctionNotation/RegularCallableCallFixerTest.php
  tests/Fixer/LanguageConstruct/SingleSpaceAfterConstructFixerTest.php
Labels: kind/enhancement, topic/PHP8

#5325 NoBreakCommentFixer - better throw handling
  src/Fixer/ControlStructure/NoBreakCommentFixer.php
  tests/Fixer/ControlStructure/NoBreakCommentFixerTest.php
Labels: kind/bug

#5328 Fixed deprecation message version
  src/Console/ConfigurationResolver.php
Labels: kind/enhancement

#5332 Fix file missing for php8
  box.json.dist
Labels: kind/bug, topic/release

#5330 DX: cleanup Github Actions configs
  .editorconfig
  .github/workflows/ci.yml
  .github/workflows/sca.yml
  .github/workflows/yaml.yml
Labels: RTM, kind/cleanup, topic/tests

#5327 StaticLambdaFixer - fix for arrow function used in class with $this
  src/Fixer/FunctionNotation/StaticLambdaFixer.php
  tests/Fixer/FunctionNotation/StaticLambdaFixerTest.php
Labels: kind/bug

#5319 Clean ups
  doc/rules/language_construct/single_space_after_construct.rst
  src/Fixer/FunctionNotation/NoUselessSprintfFixer.php
  src/Fixer/LanguageConstruct/SingleSpaceAfterConstructFixer.php
  src/Fixer/Semicolon/NoEmptyStatementFixer.php
  tests/AutoReview/FixerFactoryTest.php
  tests/Fixer/LanguageConstruct/SingleSpaceAfterConstructFixerTest.php
  tests/Fixtures/Integration/priority/no_useless_sprintf,no_empty_statement.test
  tests/Test/AbstractFixerTestCase.php
  tests/Tokenizer/Analyzer/GotoLabelAnalyzerTest.php
Labels: RTM, kind/cleanup

#5344 Update docs: do not use deprecated create method
  .php_cs.dist
  doc/config.rst
  doc/usage.rst
Labels: RTM, topic/documentation

#5356 RuleSet description fixes
  doc/ruleSets/PHPUnit30MigrationRisky.rst
  doc/ruleSets/PHPUnit32MigrationRisky.rst
  doc/ruleSets/PHPUnit35MigrationRisky.rst
  doc/ruleSets/PHPUnit43MigrationRisky.rst
  doc/ruleSets/PHPUnit48MigrationRisky.rst
  doc/ruleSets/PHPUnit50MigrationRisky.rst
  doc/ruleSets/PHPUnit52MigrationRisky.rst
  doc/ruleSets/PHPUnit54MigrationRisky.rst
  doc/ruleSets/PHPUnit55MigrationRisky.rst
  doc/ruleSets/PHPUnit56MigrationRisky.rst
  doc/ruleSets/PHPUnit57MigrationRisky.rst
  doc/ruleSets/PHPUnit60MigrationRisky.rst
  doc/ruleSets/PHPUnit75MigrationRisky.rst
  doc/ruleSets/PSR1.rst
  doc/ruleSets/PSR2.rst
  doc/ruleSets/Symfony.rst
  doc/ruleSets/SymfonyRisky.rst
  src/RuleSet/Sets/PHPUnit30MigrationRiskySet.php
  src/RuleSet/Sets/PHPUnit32MigrationRiskySet.php
  src/RuleSet/Sets/PHPUnit35MigrationRiskySet.php
  src/RuleSet/Sets/PHPUnit43MigrationRiskySet.php
  src/RuleSet/Sets/PHPUnit48MigrationRiskySet.php
  src/RuleSet/Sets/PHPUnit50MigrationRiskySet.php
  src/RuleSet/Sets/PHPUnit52MigrationRiskySet.php
  src/RuleSet/Sets/PHPUnit54MigrationRiskySet.php
  src/RuleSet/Sets/PHPUnit55MigrationRiskySet.php
  src/RuleSet/Sets/PHPUnit56MigrationRiskySet.php
  src/RuleSet/Sets/PHPUnit57MigrationRiskySet.php
  src/RuleSet/Sets/PHPUnit60MigrationRiskySet.php
  src/RuleSet/Sets/PHPUnit75MigrationRiskySet.php
  src/RuleSet/Sets/PSR1Set.php
  src/RuleSet/Sets/PSR2Set.php
  src/RuleSet/Sets/SymfonyRiskySet.php
  src/RuleSet/Sets/SymfonySet.php
  tests/RuleSet/Sets/AbstractSetTest.php
Labels: RTM, topic/documentation

#5345 CleanNamespaceFixer - preserve traling comments
  src/Fixer/NamespaceNotation/CleanNamespaceFixer.php
  tests/Fixer/NamespaceNotation/CleanNamespaceFixerTest.php
Labels: kind/bug

#5348 PsrAutoloadingFixer - fix for class without namespace
  src/Fixer/Basic/PsrAutoloadingFixer.php
  tests/Fixer/Basic/Psr4FixerTest.php
  tests/Fixer/Basic/PsrAutoloadingFixerTest.php
Labels: RTM, kind/bug

#5353 Fix typo in issue template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: kind/cleanup

#5355 OrderedTraitsFixer - mark as risky
  doc/rules/class_notation/ordered_traits.rst
  doc/rules/index.rst
  src/Fixer/ClassNotation/OrderedTraitsFixer.php
Labels: RTM, kind/bug

#5360 DX: clean up detectIndent methods
  dev-tools/install.sh
  src/Fixer/Basic/BracesFixer.php
  src/Fixer/ControlStructure/NoBreakCommentFixer.php
  src/Fixer/Import/SingleImportPerStatementFixer.php
  src/Fixer/PhpUnit/PhpUnitExpectationFixer.php
  src/Fixer/PhpUnit/PhpUnitInternalClassFixer.php
  src/Fixer/PhpUnit/PhpUnitNoExpectationAnnotationFixer.php
  src/Fixer/PhpUnit/PhpUnitSizeClassFixer.php
  src/Fixer/PhpUnit/PhpUnitTestAnnotationFixer.php
  src/Fixer/Phpdoc/PhpdocLineSpanFixer.php
  src/Fixer/Whitespace/HeredocIndentationFixer.php
  src/Tokenizer/Analyzer/WhitespacesAnalyzer.php
  tests/Fixer/Import/SingleImportPerStatementFixerTest.php
  tests/Tokenizer/Analyzer/WhitespacesAnalyzerTest.php
Labels: kind/cleanup

#5359 Add application version to "fix" out put when verbosity flag is set
  src/Console/Command/DescribeCommand.php
  src/Console/Command/FixCommand.php
  src/Console/Command/SelfUpdateCommand.php
  tests/Console/Command/SelfUpdateCommandTest.php
  tests/Smoke/CiIntegrationTest.php
Labels: topic/I/O

#5362 SingleSpaceAfterConstructFixer: Do not adjust whitespace before multiple multi-line extends
  src/Fixer/LanguageConstruct/SingleSpaceAfterConstructFixer.php
  tests/Fixer/LanguageConstruct/SingleSpaceAfterConstructFixerTest.php
Labels: RTM, kind/bug

#5363 Added missing self return type to ConfigInterface::registerCustomFixers()
  src/ConfigInterface.php
Labels: kind/enhancement

#5371 Update documentation about PHP_CS_FIXER_IGNORE_ENV
  doc/usage.rst
  php-cs-fixer
Labels: topic/documentation

#5364 DX: Do not display runtime twice on 3.0 line
  src/Console/Command/FixCommand.php
  tests/Smoke/CiIntegrationTest.php
Labels: kind/cleanup

#5329 DX: collect coverage with Github Actions
  .github/workflows/ci.yml
  .travis.yml
  composer.json
Labels: kind/enhancement

#5383 DX: fail PHPUnit tests on warning
  phpunit.xml.dist
  tests/Fixer/FunctionNotation/RegularCallableCallFixerTest.php
Labels: kind/enhancement, topic/tests

#5385 SingleLineCommentStyleFixer- run before NoUselessReturnFixer
  src/Fixer/Comment/SingleLineCommentStyleFixer.php
  src/Fixer/ReturnNotation/NoUselessReturnFixer.php
  tests/AutoReview/FixerFactoryTest.php
  tests/Fixtures/Integration/priority/no_useless_return,single_line_comment_style.test
Labels: kind/bug

#5380 PhpdocOrderByValueFixer - Allow sorting of throws annotations by value
  doc/rules/phpdoc/phpdoc_order_by_value.rst
  src/Fixer/Phpdoc/PhpdocOrderByValueFixer.php
  tests/Fixer/Phpdoc/PhpdocOrderByValueFixerTest.php
Labels: RTM, kind/enhancement

#5387 SingleSpaceAfterConstructFixer - do not touch multi line implements
  src/Fixer/LanguageConstruct/SingleSpaceAfterConstructFixer.php
  tests/Fixer/LanguageConstruct/SingleSpaceAfterConstructFixerTest.php
Labels: kind/bug

#5386 DX: remove incorrect priority relations
  src/Fixer/Phpdoc/PhpdocNoAccessFixer.php
  src/Fixer/Phpdoc/PhpdocNoPackageFixer.php
  src/Fixer/Phpdoc/PhpdocOrderFixer.php
  tests/AutoReview/FixerFactoryTest.php
Labels: kind/cleanup

#5404 NullableTypeTransformer - constructor property promotion support
  src/Tokenizer/Transformer/NullableTypeTransformer.php
  tests/Fixer/Operator/TernaryOperatorSpacesFixerTest.php
  tests/Tokenizer/Transformer/NullableTypeTransformerTest.php
Labels: kind/enhancement, topic/PHP8

#5391 PhpdocOrderByValueFixer - Add additional annotations to sort
  doc/rules/phpdoc/phpdoc_order_by_value.rst
  src/Fixer/Phpdoc/PhpdocOrderByValueFixer.php
  tests/Fixer/Phpdoc/PhpdocOrderByValueFixerTest.php
Labels: kind/enhancement

#5392 PhpdocScalarFixer - Fix description
  doc/rules/phpdoc/phpdoc_scalar.rst
  src/Fixer/Phpdoc/PhpdocScalarFixer.php
Labels: RTM, kind/enhancement, topic/documentation

#5397 NoExtraBlankLinesFixer - PHP8 throw support
  src/Fixer/Whitespace/NoExtraBlankLinesFixer.php
  tests/Fixer/Whitespace/NoExtraBlankLinesFixerTest.php
Labels: RTM, kind/enhancement, topic/PHP8

#5407 TokensAnalyzer::getClassyElements - return trait imports
  src/Tokenizer/TokensAnalyzer.php
  tests/Tokenizer/TokensAnalyzerTest.php
Labels: kind/enhancement

#5406 SingleSpaceAfterConstructFixer - Attributes, comments and PHPDoc support
  doc/rules/language_construct/single_space_after_construct.rst
  src/Fixer/LanguageConstruct/SingleSpaceAfterConstructFixer.php
  tests/Fixer/LanguageConstruct/SingleSpaceAfterConstructFixerTest.php
Labels: kind/bug, kind/enhancement

#5405 TypeAlternationTransformer - add support for PHP8
  src/Fixer/ClassNotation/VisibilityRequiredFixer.php
  src/Tokenizer/Analyzer/ClassyAnalyzer.php
  src/Tokenizer/Transformer/TypeAlternationTransformer.php
  src/Tokenizer/Transformer/TypeColonTransformer.php
  tests/AutoReview/TransformerTest.php
  tests/Test/AbstractIntegrationTestCase.php
  tests/Tokenizer/Analyzer/ClassyAnalyzerTest.php
  tests/Tokenizer/Transformer/TypeAlternationTransformerTest.php
Labels: kind/enhancement, topic/PHP8

#5410 minors
  src/Fixer/Alias/SetTypeToCastFixer.php
  src/Tokenizer/TokensAnalyzer.php
  tests/Fixer/ControlStructure/NoSuperfluousElseifFixerTest.php
  tests/Fixer/ControlStructure/NoUselessElseFixerTest.php
  tests/Fixer/FunctionNotation/FopenFlagOrderFixerTest.php
  tests/Fixer/FunctionNotation/FopenFlagsFixerTest.php
  tests/RuleSet/RuleSetsTest.php
Labels: kind/enhancement

#5411 bump year in LICENSE file
  LICENSE
Labels: RTM, kind/enhancement, topic/documentation
