Repository PHP-CS-Fixer/PHP-CS-Fixer, pull requests merged in 2020-06, with the labels that each got.

#4985 Fix tests with Symfony 5.1
  .travis.yml
  composer.json
  dev-tools/install.sh
  php-cs-fixer
  src/Console/Application.php
  tests/Fixer/CastNotation/LowercaseCastFixerTest.php
  tests/Fixer/CastNotation/ShortScalarCastFixerTest.php
  tests/Fixer/Comment/HeaderCommentFixerTest.php
  tests/Fixer/ControlStructure/YodaStyleFixerTest.php
  tests/Fixer/LanguageConstruct/IsNullFixerTest.php
  tests/Fixer/Operator/BinaryOperatorSpacesFixerTest.php
  tests/Fixer/Phpdoc/PhpdocAddMissingParamAnnotationFixerTest.php
Labels: topic/tests

#4961 Assert all project source files are monolithic.
  tests/AutoReview/ProjectCodeTest.php
Labels: RTM, kind/enhancement, topic/tests

#4987 PhpdocAnnotationWithoutDotFixer - handle unicode characters using mb_*
  composer.json
  src/Fixer/Phpdoc/PhpdocAnnotationWithoutDotFixer.php
  tests/Fixer/Phpdoc/PhpdocAnnotationWithoutDotFixerTest.php
Labels: kind/enhancement

#4963 PhpdocToReturnTypeFixer - fix for breaking PHP syntax for type having reserved name
  src/Fixer/FunctionNotation/PhpdocToReturnTypeFixer.php
  tests/Fixer/FunctionNotation/PhpdocToReturnTypeFixerTest.php
Labels: RTM, kind/bug

#4994 FinalInternalClassFixer - must run before ProtectedToPrivateFixer
  src/Fixer/ClassNotation/FinalInternalClassFixer.php
  src/Fixer/ClassNotation/ProtectedToPrivateFixer.php
  src/Fixer/PhpUnit/PhpUnitInternalClassFixer.php
  tests/AutoReview/FixerFactoryTest.php
  tests/Fixtures/Integration/priority/final_internal_class,protected_to_private.test
Labels: kind/bug

#4996 NoEmptyCommentFixer - handle multiline comments
  src/Fixer/Comment/NoEmptyCommentFixer.php
  tests/Fixer/Comment/NoEmptyCommentFixerTest.php
Labels: kind/bug

#4999 BlankLineBeforeStatementFixer - better comment handling
  src/Fixer/Whitespace/BlankLineBeforeStatementFixer.php
  tests/Fixer/Whitespace/BlankLineBeforeStatementFixerTest.php
Labels: kind/bug

#5008 Enhancement: Social justification applied
  README.rst
  src/Console/Command/HelpCommand.php
  src/Fixer/ClassNotation/FinalInternalClassFixer.php
  src/Fixer/ControlStructure/NoUnneededCurlyBracesFixer.php
  src/Fixer/FunctionNotation/PhpdocToReturnTypeFixer.php
  src/Fixer/FunctionNotation/VoidReturnFixer.php
  tests/Fixer/ClassNotation/FinalInternalClassFixerTest.php
  tests/Fixer/FunctionNotation/PhpdocToReturnTypeFixerTest.php
Labels: RTM, kind/enhancement

#5009 NoEmptyCommentFixer - better handle comments sequence
  src/Fixer/Comment/NoEmptyCommentFixer.php
  tests/Fixer/Comment/NoEmptyCommentFixerTest.php
Labels: RTM, kind/bug

#5010 SimplifiedNullReturnFixer - must run before VoidReturnFixer
  src/Fixer/FunctionNotation/VoidReturnFixer.php
  src/Fixer/ReturnNotation/SimplifiedNullReturnFixer.php
  tests/AutoReview/FixerFactoryTest.php
  tests/Fixtures/Integration/priority/simplified_null_return,void_return.test
Labels: RTM, kind/bug

#5011 SingleClassElementPerStatementFixer - must run before ClassAttributesSeparationFixer
  src/Fixer/ClassNotation/ClassAttributesSeparationFixer.php
  src/Fixer/ClassNotation/SingleClassElementPerStatementFixer.php
  tests/AutoReview/FixerFactoryTest.php
  tests/Fixtures/Integration/priority/single_class_element_per_statement,class_attributes_separation.test
Labels: kind/bug

#5012 StrictParamFixer - must run before NativeFunctionInvocationFixer
  src/Fixer/FunctionNotation/NativeFunctionInvocationFixer.php
  src/Fixer/Strict/StrictParamFixer.php
  tests/AutoReview/FixerFactoryTest.php
  tests/Fixtures/Integration/priority/strict_param,native_function_invocation.test
Labels: kind/bug

#5014 PhpdocToParamTypeFixer - fix for void as param
  src/Fixer/FunctionNotation/PhpdocToParamTypeFixer.php
  tests/Fixer/FunctionNotation/PhpdocToParamTypeFixerTest.php
Labels: kind/bug

#5024 DX: add missing non-default code samples
  src/Fixer/DoctrineAnnotation/DoctrineAnnotationSpacesFixer.php
  src/Fixer/FunctionNotation/PhpdocToReturnTypeFixer.php
  src/Fixer/PhpUnit/PhpUnitInternalClassFixer.php
  src/Fixer/PhpUnit/PhpUnitNamespacedFixer.php
  src/Fixer/PhpUnit/PhpUnitTestCaseStaticMethodCallsFixer.php
  src/Fixer/Phpdoc/GeneralPhpdocAnnotationRemoveFixer.php
  src/Fixer/Phpdoc/PhpdocScalarFixer.php
  src/Fixer/Phpdoc/PhpdocTypesFixer.php
  tests/AutoReview/FixerTest.php
Labels: topic/documentation

#5023 Fix issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/rule_request.md
  .github/ISSUE_TEMPLATE/support_question.md
Labels: topic/documentation

#4920 Enhancement: Use DocBlock itself to make it multi-line
  src/Fixer/PhpUnit/PhpUnitInternalClassFixer.php
Labels: kind/refactoring

#5029 SingleLineAfterImportsFixer - fix for line after import already added using CRLF
  src/Fixer/Import/SingleLineAfterImportsFixer.php
  tests/Fixer/Import/SingleLineAfterImportsFixerTest.php
Labels: kind/bug

#5018 PhpdocScalarFixer - fix for comment with Windows line endings
  src/DocBlock/Annotation.php
  tests/DocBlock/AnnotationTest.php
  tests/Fixer/Phpdoc/PhpdocScalarFixerTest.php
Labels: kind/bug
