Repository PHP-CS-Fixer/PHP-CS-Fixer, pull requests merged in 2020-09, with the labels that each got.

#5105 ClassKeywordRemoveFixer - fix for fully qualified class
  src/Fixer/LanguageConstruct/ClassKeywordRemoveFixer.php
  tests/Fixer/LanguageConstruct/ClassKeywordRemoveFixerTest.php
Labels: kind/bug

#5106 Symfony's finder already ignores vcs and dot files by default
  src/Finder.php
Labels: kind/cleanup

#5132 Do not allow assignments in if statements
  phpmd.xml
  src/Console/ConfigurationResolver.php
  src/Fixer/Alias/PowToExponentiationFixer.php
Labels: RTM, kind/enhancement

#5137 DoctrineAnnotationSpacesFixer - fix for typed properties
  src/AbstractDoctrineAnnotationFixer.php
  tests/Fixer/DoctrineAnnotation/DoctrineAnnotationSpacesFixerTest.php
Labels: kind/bug

#5139 revert some unneeded exclusions
  .travis.yml
  composer.json
Labels: RTM

#4005 GroupImportFixer - introduction
  README.rst
  src/Fixer/Import/GroupImportFixer.php
  src/FixerFactory.php
  tests/Fixer/Import/GroupImportFixerTest.php
Labels: RTM, kind/feature

#5093 LambdaNotUsedImportFixer - add heredoc test
  tests/Fixer/FunctionNotation/LambdaNotUsedImportFixerTest.php
Labels: kind/enhancement
