Repository PHP-CS-Fixer/PHP-CS-Fixer, pull requests merged in 2020-07, with the labels that each got.

#5017 PhpdocTrimConsecutiveBlankLineSeparationFixer - must run after AlignMultilineCommentFixer
  src/Fixer/Phpdoc/AlignMultilineCommentFixer.php
  src/Fixer/Phpdoc/PhpdocAlignFixer.php
  src/Fixer/Phpdoc/PhpdocTrimConsecutiveBlankLineSeparationFixer.php
  tests/AutoReview/FixerFactoryTest.php
  tests/Fixtures/Integration/priority/align_multiline_comment,phpdoc_trim_consecutive_blank_line_separation.test
Labels: kind/bug

#5033 VoidReturnFixer - must run after NoSuperfluousPhpdocTagsFixer
  src/Fixer/FunctionNotation/VoidReturnFixer.php
  src/Fixer/Phpdoc/NoEmptyPhpdocFixer.php
  src/Fixer/Phpdoc/NoSuperfluousPhpdocTagsFixer.php
  src/Fixer/Phpdoc/PhpdocNoEmptyReturnFixer.php
  tests/AutoReview/FixerFactoryTest.php
  tests/Fixtures/Integration/priority/no_superfluous_phpdoc_tags,void_return.test
Labels: kind/bug

#5035 PhpdocToParamTypeFixer - Rename attribute
  src/Fixer/FunctionNotation/PhpdocToParamTypeFixer.php
Labels: RTM, kind/enhancement

#5040 LinebreakAfterOpeningTagFixer - do not change code if linebreak already present
  src/Fixer/PhpTag/LinebreakAfterOpeningTagFixer.php
  tests/Fixer/PhpTag/LinebreakAfterOpeningTagFixerTest.php
Labels: kind/bug

#5048 Allow composer/semver ^2.0 and ^3.0
  composer.json
Labels: kind/enhancement

#5038 HelpCommandTest - toString nested array
  src/Console/Command/HelpCommand.php
  tests/Console/Command/HelpCommandTest.php
Labels: kind/bug

#5006 PhpdocToParamTypeFixer - fix for breaking PHP syntax for type having reserved name
  src/AbstractPhpdocToTypeDeclarationFixer.php
  src/Fixer/FunctionNotation/PhpdocToParamTypeFixer.php
  src/Fixer/FunctionNotation/PhpdocToReturnTypeFixer.php
  tests/Fixer/FunctionNotation/PhpdocToParamTypeFixerTest.php
Labels: kind/bug

#4903 Docs: extend regular_callable_call rule docs
  README.rst
  src/Fixer/FunctionNotation/RegularCallableCallFixer.php
Labels: topic/documentation

#4942 OrderedClassElementsFixer - added support for abstract method sorting
  README.rst
  src/Fixer/ClassNotation/OrderedClassElementsFixer.php
  tests/Fixer/ClassNotation/OrderedClassElementsFixerTest.php
Labels: kind/feature

#4953 Add support for custom differ
  src/Console/ConfigurationResolver.php
  tests/Console/ConfigurationResolverTest.php
  tests/Fixtures/FakeDiffer.php
Labels: kind/enhancement, topic/I/O
