Repository PHP-CS-Fixer/PHP-CS-Fixer, pull requests merged in 2021-12, with the labels that each got.

#6139 PhpdocLineSpanFixer - must run before NoSuperfluousPhpdocTagsFixer
  src/Fixer/Phpdoc/NoSuperfluousPhpdocTagsFixer.php
  src/Fixer/Phpdoc/PhpdocLineSpanFixer.php
  tests/AutoReview/FixerFactoryTest.php
  tests/Fixtures/Integration/priority/phpdoc_line_span,no_superfluous_phpdoc_tags.test
Labels: kind/bug

#6147 DX: update composer-normalize
  composer.json
  dev-tools/composer.json
Labels: topic/tests

#6146 PHP 8.1: add new_in_initializers to PHP 8.1 integration test
  tests/Fixtures/Integration/misc/PHP8_1.test
Labels: topic/PHP8.1

#6156 DX: drop hack for Prophecy incompatibility
  composer.json
  tests/Linter/ProcessLintingResultTest.php
Labels: RTM, topic/tests

#6152 PHP8.1 support
  .github/workflows/ci.yml
  .php-cs-fixer.php-highest.php
  php-cs-fixer
  tests/AutoReview/CiConfigurationTest.php
  tests/Smoke/CiIntegrationTest.php
Labels: RTM, topic/PHP8.1

#6160 NonPrintableCharacterFixer - fix for when removing non-printable character break PHP syntax
  src/Fixer/Basic/NonPrintableCharacterFixer.php
  tests/Fixer/Basic/NonPrintableCharacterFixerTest.php
Labels: kind/bug

#4571 BlankLineBeforeStatementFixer - can now add blank lines before doc-comments
  .gitattributes
  doc/list.rst
  doc/ruleSets/PhpCsFixer.rst
  doc/rules/whitespace/blank_line_before_statement.rst
  src/Console/Report/FixReport/JunitReporter.php
  src/Fixer/PhpTag/BlankLineAfterOpeningTagFixer.php
  src/Fixer/Whitespace/BlankLineBeforeStatementFixer.php
  src/RuleSet/Sets/PhpCsFixerSet.php
  tests/Fixer/Alias/NoAliasFunctionsFixerTest.php
  tests/Fixer/Whitespace/BlankLineBeforeStatementFixerTest.php
  tests/Tokenizer/TokensTest.php
Labels: kind/feature

#6171 Fix tests and CS
  .github/workflows/ci.yml
  src/Tokenizer/Tokens.php
  src/Tokenizer/Transformer/ReturnRefTransformer.php
  tests/Fixer/ClassNotation/VisibilityRequiredFixerTest.php
  tests/Tokenizer/TokensTest.php
Labels: topic/tests

#5953 GetClassToClassKeywordFixer - introduction
  doc/list.rst
  doc/ruleSets/PHP80MigrationRisky.rst
  doc/rules/index.rst
  doc/rules/language_construct/get_class_to_class_keyword.rst
  src/Fixer/FunctionNotation/NoSpacesAfterFunctionNameFixer.php
  src/Fixer/LanguageConstruct/GetClassToClassKeywordFixer.php
  src/Fixer/Semicolon/MultilineWhitespaceBeforeSemicolonsFixer.php
  src/Fixer/Whitespace/NoSpacesInsideParenthesisFixer.php
  src/RuleSet/Sets/PHP80MigrationRiskySet.php
  tests/AutoReview/FixerFactoryTest.php
  tests/Fixer/LanguageConstruct/GetClassToClassKeywordFixerTest.php
  tests/Fixtures/Integration/priority/get_class_to_class_keyword,multiline_whitespace_before_semicolons.test
  tests/Fixtures/Integration/priority/no_spaces_after_function_name,get_class_to_class_keyword.test
  tests/Fixtures/Integration/priority/no_spaces_inside_parenthesis,get_class_to_class_keyword.test
Labels: RTM

#6181 UseTransformer - Trait import in enum fix (PHP8.1)
  src/Tokenizer/Transformer/UseTransformer.php
  tests/Fixer/Import/NoUnusedImportsFixerTest.php
  tests/Tokenizer/Transformer/UseTransformerTest.php
Labels: kind/bug

#6177 DX: chmod +x for benchmark.sh file
  benchmark.sh
Labels: kind/enhancement, RTM

#6180 gitlab reporter - add fixed severity to match format
  src/Console/Report/FixReport/GitlabReporter.php
  tests/Console/Report/FixReport/GitlabReporterTest.php
Labels: RTM, topic/I/O

#6183 Simplify DiffConsoleFormatter
  src/Differ/DiffConsoleFormatter.php
Labels: kind/cleanup

#6184 Do not support array of patterns in Preg methods
  src/Preg.php
  tests/PregTest.php
Labels: kind/enhancement

#6185 Upgrade PHPStan
  .github/workflows/sca.yml
  dev-tools/composer.json
Labels: kind/enhancement

#6198 DX: format dot files
  .php-cs-fixer.dist.php
  .php-cs-fixer.php-highest.php
  .php-cs-fixer.php-lowest.php
  dev-tools/install.sh
Labels: kind/enhancement, kind/cleanup

#6200 DX: Composer's branch-alias leftovers cleanup
  dev-tools/composer-alias-update.php
  tests/AutoReview/ComposerTest.php
Labels: kind/cleanup
