Repository PHP-CS-Fixer/PHP-CS-Fixer, pull requests merged in 2021-10, with the labels that each got.

#6037 PhpdocLineSpanFixer - do not crash on trait imports
  src/Fixer/Phpdoc/PhpdocLineSpanFixer.php
  tests/Fixer/Phpdoc/PhpdocLineSpanFixerTest.php
Labels: kind/bug

#6047 StringLengthToEmptyFixer - introduction
  doc/list.rst
  doc/ruleSets/SymfonyRisky.rst
  doc/rules/index.rst
  doc/rules/string_notation/string_length_to_empty.rst
  src/AbstractFunctionReferenceFixer.php
  src/DocBlock/DocBlock.php
  src/Fixer/Alias/MbStrFunctionsFixer.php
  src/Fixer/Alias/ModernizeStrposFixer.php
  src/Fixer/Alias/PowToExponentiationFixer.php
  src/Fixer/Alias/RandomApiMigrationFixer.php
  src/Fixer/CastNotation/ModernizeTypesCastingFixer.php
  src/Fixer/FunctionNotation/FunctionDeclarationFixer.php
  src/Fixer/LanguageConstruct/DirConstantFixer.php
  src/Fixer/Operator/BinaryOperatorSpacesFixer.php
  src/Fixer/StringNotation/StringLengthToEmptyFixer.php
  src/Fixer/Whitespace/NoExtraBlankLinesFixer.php
  src/Fixer/Whitespace/NoSpacesInsideParenthesisFixer.php
  src/Fixer/Whitespace/NoTrailingWhitespaceFixer.php
  src/RuleSet/Sets/SymfonyRiskySet.php
  tests/AutoReview/FixerFactoryTest.php
  tests/Fixer/StringNotation/StringLengthToEmptyFixerTest.php
  tests/Fixtures/Integration/priority/no_spaces_inside_parenthesis,string_length_to_empty.test
  tests/Fixtures/Integration/priority/string_length_to_empty,no_extra_blank_lines.test
  tests/Fixtures/Integration/priority/string_length_to_empty,no_trailing_whitespace.test
Labels: kind/feature

#6085 Dx: reuse WhitespacesAnalyzer::detectIndent
  src/Fixer/Whitespace/HeredocIndentationFixer.php
Labels: kind/cleanup, RTM

#6087 AbstractProxyFixer - more tests
  src/FixerFactory.php
  tests/AbstractProxyFixerTest.php
  tests/Fixer/Phpdoc/PhpdocNoAccessFixerTest.php
  tests/Fixer/Phpdoc/PhpdocNoPackageFixerTest.php
  tests/Fixtures/Test/AbstractFixerTest/SimpleFixer.php
  tests/Fixtures/Test/AbstractProxyFixerTest/SimpleFixer.php
  tests/Fixtures/Test/AbstractProxyFixerTest/SimpleWhitespacesAwareFixer.php
Labels: kind/cleanup, topic/tests

#6089 TokensAnalyzer.php - Fix T_ENCAPSED_AND_WHITESPACE handling in isBina…
  src/AbstractPhpdocTypesFixer.php
  src/Fixer/ClassNotation/NoPhp4ConstructorFixer.php
  src/Fixer/Import/OrderedImportsFixer.php
  src/Fixer/PhpUnit/PhpUnitNamespacedFixer.php
  src/Fixer/PhpUnit/PhpUnitSizeClassFixer.php
  src/Fixer/PhpUnit/PhpUnitTestAnnotationFixer.php
  src/Fixer/PhpUnit/PhpUnitTestClassRequiresCoversFixer.php
  src/Fixer/Phpdoc/GeneralPhpdocAnnotationRemoveFixer.php
  src/Fixer/Phpdoc/PhpdocAnnotationWithoutDotFixer.php
  src/Fixer/Phpdoc/PhpdocNoEmptyReturnFixer.php
  src/Fixer/Phpdoc/PhpdocOrderFixer.php
  src/Tokenizer/TokensAnalyzer.php
  src/Utils.php
  tests/DocBlock/AnnotationTest.php
  tests/DocBlock/DocBlockTest.php
  tests/FixerDefinition/FileSpecificCodeSampleTest.php
  tests/RuleSet/RuleSetTest.php
  tests/RuleSet/RuleSetsTest.php
  tests/Test/AbstractFixerTestCase.php
  tests/Test/AbstractTransformerTestCase.php
  tests/Tokenizer/Analyzer/Analysis/NamespaceAnalysisTest.php
  tests/Tokenizer/Analyzer/Analysis/NamespaceUseAnalysisTest.php
  tests/Tokenizer/Analyzer/Analysis/TypeAnalysisTest.php
  tests/Tokenizer/Analyzer/ArgumentsAnalyzerTest.php
  tests/Tokenizer/TokensAnalyzerTest.php
  tests/Tokenizer/TokensTest.php
  tests/ToolInfoTest.php
Labels: kind/bug, RTM
