Repository PHP-CS-Fixer/PHP-CS-Fixer, pull requests merged in 2021-06, with the labels that each got.

#5741 Fix constant invocation detection cases
  src/Tokenizer/TokensAnalyzer.php
  tests/Fixer/ConstantNotation/NativeConstantInvocationFixerTest.php
  tests/Tokenizer/TokensAnalyzerTest.php
Labels: kind/bug

#5756 Fix rule sets descriptions
  doc/ruleSets/PHP74MigrationRisky.rst
  doc/ruleSets/PHPUnit84MigrationRisky.rst
  src/RuleSet/Sets/PHP74MigrationRiskySet.php
  src/RuleSet/Sets/PHPUnit84MigrationRiskySet.php
  tests/RuleSet/Sets/AbstractSetTest.php
Labels: kind/bug

#5688 ArrayIndentationFixer - fix for really long arrays
  src/Fixer/Whitespace/ArrayIndentationFixer.php
  tests/Fixtures/Integration/misc/huge_array.test
  tests/Fixtures/Integration/misc/huge_array.test-out.php
Labels: kind/bug

#5750 Test all const are in uppercase
  tests/AutoReview/ProjectCodeTest.php
Labels: topic/tests

#5717 Run migration rules on PHP 8
  .github/workflows/ci.yml
  src/Cache/Directory.php
  src/Cache/FileCacheManager.php
  src/Console/Output/ProcessOutput.php
  src/FileRemoval.php
  src/Fixer/PhpUnit/PhpUnitSizeClassFixer.php
  src/Linter/ProcessLinter.php
  src/Runner/Runner.php
Labels: kind/enhancement

#5761 Fix links in custom rules documentation
  doc/custom_rules.rst
Labels: topic/documentation

#5738 TokensAnalyzer - fix for union types
  src/Tokenizer/TokensAnalyzer.php
  tests/Fixer/Operator/BinaryOperatorSpacesFixerTest.php
  tests/Fixtures/Integration/misc/PHP8_0.test
  tests/Tokenizer/TokensAnalyzerTest.php
Labels: kind/bug

#5779 SingleLineThrowFixer - fix for throw in match
  src/Fixer/FunctionNotation/SingleLineThrowFixer.php
  tests/Fixer/FunctionNotation/SingleLineThrowFixerTest.php
Labels: kind/bug

#5777 DX: update PHPStan
  dev-tools/composer.json
  phpstan.neon
  src/Fixer/Whitespace/ArrayIndentationFixer.php
Labels: kind/enhancement

#5774 FunctionsAnalyzer::isTheSameClassCall - fix for $this with double colon following
  src/Tokenizer/Analyzer/FunctionsAnalyzer.php
  tests/Fixer/PhpUnit/PhpUnitTestCaseStaticMethodCallsFixerTest.php
  tests/Tokenizer/Analyzer/FunctionsAnalyzerTest.php
Labels: kind/bug

#5769 Fix priority between `phpdoc_to_property_type` and `no_superfluous_phpdoc_tags`
  src/Fixer/FunctionNotation/PhpdocToPropertyTypeFixer.php
  src/Fixer/Phpdoc/NoSuperfluousPhpdocTagsFixer.php
  tests/AutoReview/FixerFactoryTest.php
  tests/Fixtures/Integration/priority/phpdoc_to_property_type,no_superfluous_phpdoc_tags.test
Labels: kind/bug

#5771 doc(config): change set's name
  doc/config.rst
Labels: topic/documentation

#5752 NoNullPropertyInitializationFixer - fix static properties as well
  doc/rules/class_notation/no_null_property_initialization.rst
  src/Fixer/ClassNotation/NoNullPropertyInitializationFixer.php
  tests/Fixer/ClassNotation/NoNullPropertyInitializationFixerTest.php
Labels: kind/enhancement

#5748 Updated the link to netbeans plugins page
  README.md
Labels: topic/documentation

#5781 ClassDefinition - fix for anonymous class with trailing comma
  src/Fixer/ClassNotation/ClassDefinitionFixer.php
  tests/Fixer/ClassNotation/ClassDefinitionFixerTest.php
Labels: kind/bug
