Repository PHP-CS-Fixer/PHP-CS-Fixer, pull requests merged in 2021-09, with the labels that each got.

#5938 NoAliasFunctionsFixer - remove dir -> getdir mapping
  src/Fixer/Alias/NoAliasFunctionsFixer.php
Labels: kind/bug, RTM

#5942 TokensAnalyzer - isConstantInvocation PHP 8 issue
  src/Fixer/Import/NoUnusedImportsFixer.php
  src/Tokenizer/TokensAnalyzer.php
  tests/Fixer/Import/NoUnusedImportsFixerTest.php
  tests/Tokenizer/TokensAnalyzerTest.php
Labels: kind/bug, topic/PHP8

#5941 TokensAnalyzer - isAnonymousClass bug on PHP8
  src/Runner/Runner.php
  src/Tokenizer/TokensAnalyzer.php
  tests/Fixtures/Integration/misc/PHP8_0.test
  tests/Tokenizer/TokensAnalyzerTest.php
Labels: kind/bug, topic/PHP8

#5943 NoUnusedImportsFixer - use in attribute
  src/Fixer/Import/NoUnusedImportsFixer.php
  tests/Fixer/Import/NoUnusedImportsFixerTest.php
Labels: kind/bug, topic/PHP8

#5932 Extract ControlStructureContinuationPositionFixer from BracesFixer
  doc/rules/control_structure/control_structure_continuation_position.rst
  doc/rules/index.rst
  src/Fixer/Basic/BracesFixer.php
  src/Fixer/ControlStructure/ControlStructureContinuationPositionFixer.php
  tests/Fixer/ControlStructure/ControlStructureContinuationPositionFixerTest.php
Labels: kind/refactoring

#5925 DX: ProjectCodeTest - fix detection by testExpectedInputOrder
  tests/AutoReview/ProjectCodeTest.php
  tests/Fixer/FunctionNotation/NullableTypeDeclarationForDefaultNullValueFixerTest.php
  tests/Fixer/ListNotation/ListSyntaxFixerTest.php
  tests/Test/TestCaseUtils.php
Labels: kind/enhancement, topic/tests

#5952 ClassAttributesSeparationFixer - Re-add omitted `only_if_meta` option
  doc/rules/class_notation/class_attributes_separation.rst
  src/Fixer/ClassNotation/ClassAttributesSeparationFixer.php
Labels: topic/documentation, RTM

#5773 NoAlternativeSyntaxFixer - Add option to not fix non-monolithic PHP code
  doc/rules/control_structure/no_alternative_syntax.rst
  src/Console/WarningsDetector.php
  src/Fixer/ControlStructure/NoAlternativeSyntaxFixer.php
  tests/Fixer/ControlStructure/NoAlternativeSyntaxFixerTest.php
Labels: kind/feature

#5961 Remove duplicated method
  src/Fixer/ControlStructure/ControlStructureContinuationPositionFixer.php
Labels: kind/cleanup

#5963 DX: extract config for special CI jobs
  .github/workflows/ci.yml
  .php-cs-fixer.php-highest.php
  .php-cs-fixer.php-lowest.php
Labels: kind/refactoring

#5754 ModernizeStrposFixer - introduction
  .github/workflows/ci.yml
  .php-cs-fixer.php-highest.php
  doc/ruleSets/PHP80MigrationRisky.rst
  doc/rules/alias/modernize_strpos.rst
  doc/rules/index.rst
  src/Fixer/Alias/ModernizeStrposFixer.php
  src/Fixer/LanguageConstruct/SingleSpaceAfterConstructFixer.php
  src/Fixer/Operator/BinaryOperatorSpacesFixer.php
  src/Fixer/Operator/NotOperatorWithSpaceFixer.php
  src/Fixer/Operator/NotOperatorWithSuccessorSpaceFixer.php
  src/Fixer/Whitespace/NoExtraBlankLinesFixer.php
  src/Fixer/Whitespace/NoSpacesInsideParenthesisFixer.php
  src/Fixer/Whitespace/NoTrailingWhitespaceFixer.php
  src/RuleSet/Sets/PHP80MigrationRiskySet.php
  tests/AutoReview/FixerFactoryTest.php
  tests/Fixer/Alias/ModernizeStrposFixerTest.php
  tests/Fixtures/Integration/priority/modernize_strpos,binary_operator_spaces.test
  tests/Fixtures/Integration/priority/modernize_strpos,no_extra_blank_lines.test
  tests/Fixtures/Integration/priority/modernize_strpos,no_spaces_inside_parenthesis.test
  tests/Fixtures/Integration/priority/modernize_strpos,no_trailing_whitespace.test
  tests/Fixtures/Integration/priority/modernize_strpos,not_operator_with_space.test
  tests/Fixtures/Integration/priority/modernize_strpos,not_operator_with_successor_space.test
  tests/Fixtures/Integration/priority/modernize_strpos,single_space_after_construct.test
Labels: kind/feature

#5967 PHP8.1 - type "never" support
  src/DocBlock/TypeExpression.php
  src/Fixer/Casing/NativeFunctionTypeDeclarationCasingFixer.php
  src/Fixer/FunctionNotation/PhpdocToPropertyTypeFixer.php
  src/Tokenizer/Analyzer/Analysis/TypeAnalysis.php
  src/Tokenizer/Analyzer/ClassyAnalyzer.php
  tests/DocBlock/TypeExpressionTest.php
  tests/Fixer/Casing/NativeFunctionTypeDeclarationCasingFixerTest.php
  tests/Fixer/FunctionNotation/PhpdocToPropertyTypeFixerTest.php
  tests/Fixtures/Integration/misc/PHP8_1.test
  tests/Tokenizer/Analyzer/Analysis/TypeAnalysisTest.php
  tests/Tokenizer/Analyzer/ClassyAnalyzerTest.php
Labels: kind/enhancement

#5970 IntegerLiteralCaseFixer - introduction
  doc/ruleSets/Symfony.rst
  doc/rules/casing/integer_literal_case.rst
  doc/rules/index.rst
  src/Fixer/Basic/EncodingFixer.php
  src/Fixer/Casing/IntegerLiteralCaseFixer.php
  src/RuleSet/Sets/SymfonySet.php
  tests/Fixer/Casing/IntegerLiteralCaseFixerTest.php
Labels: kind/feature, RTM

#5971 PHP8.1 - Explicit octal integer literal notation
  doc/ruleSets/PHP81Migration.rst
  doc/ruleSets/index.rst
  doc/rules/array_notation/array_syntax.rst
  doc/rules/array_notation/no_whitespace_before_comma_in_array.rst
  doc/rules/array_notation/normalize_index_brace.rst
  doc/rules/basic/octal_notation.rst
  doc/rules/cast_notation/no_unset_cast.rst
  doc/rules/cast_notation/short_scalar_cast.rst
  doc/rules/class_notation/visibility_required.rst
  doc/rules/control_structure/trailing_comma_in_multiline.rst
  doc/rules/function_notation/method_argument_space.rst
  doc/rules/index.rst
  doc/rules/list_notation/list_syntax.rst
  doc/rules/namespace_notation/clean_namespace.rst
  doc/rules/operator/ternary_to_null_coalescing.rst
  doc/rules/whitespace/heredoc_indentation.rst
  src/Fixer/Basic/OctalNotationFixer.php
  src/Fixer/ControlStructure/EmptyLoopConditionFixer.php
  src/RuleSet/Sets/PHP81MigrationSet.php
  tests/Fixer/Basic/OctalNotationFixerTest.php
  tests/Fixtures/Integration/misc/PHP8_1.test
  tests/Fixtures/Integration/set/@PHP81Migration.test
  tests/Fixtures/Integration/set/@PHP81Migration.test-in.php
  tests/Fixtures/Integration/set/@PHP81Migration.test-out.php
  tests/RuleSet/Sets/PHP81MigrationSetTest.php
Labels: kind/feature

#5977 LowercaseStaticReference - SingleClassElementPerStatement - union types
  src/Fixer/Casing/LowercaseStaticReferenceFixer.php
  src/Fixer/ClassNotation/SingleClassElementPerStatementFixer.php
  tests/Fixer/Casing/LowercaseStaticReferenceFixerTest.php
  tests/Fixer/ClassNotation/SingleClassElementPerStatementFixerTest.php
Labels: kind/bug

#5984 RegularCallableCallFixer must run before NativeFunctionInvocationFixer
  src/Fixer/FunctionNotation/NativeFunctionInvocationFixer.php
  src/Fixer/FunctionNotation/RegularCallableCallFixer.php
  tests/AutoReview/FixerFactoryTest.php
  tests/Fixtures/Integration/priority/regular_callable_call,native_function_invocation.test
Labels: kind/bug

#5986 CurlyBraceTransformer - count T_CURLY_OPEN itself as level as well
  src/Tokenizer/Transformer/CurlyBraceTransformer.php
  tests/Tokenizer/Transformer/CurlyBraceTransformerTest.php
Labels: kind/bug

#5989 NoAliasFunctionsFixer - Correct mapping
  src/Fixer/Alias/NoAliasFunctionsFixer.php
  tests/Fixer/Alias/NoAliasFunctionsFixerTest.php
Labels: kind/bug

#6004 SwitchContinueToBreakFixer - Fix candidate check
  src/Fixer/ControlStructure/NoBreakCommentFixer.php
  src/Fixer/ControlStructure/SwitchCaseSemicolonToColonFixer.php
  src/Fixer/ControlStructure/SwitchCaseSpaceFixer.php
  src/Fixer/ControlStructure/SwitchContinueToBreakFixer.php
  tests/Fixer/ControlStructure/NoBreakCommentFixerTest.php
  tests/Fixer/ControlStructure/SwitchContinueToBreakFixerTest.php
  tests/Fixer/ControlStructure/YodaStyleFixerTest.php
  tests/Fixer/Whitespace/BlankLineBeforeStatementFixerTest.php
  tests/Tokenizer/Analyzer/ReferenceAnalyzerTest.php
  tests/Tokenizer/Transformer/FirstClassCallableTransformerTest.php
Labels: kind/bug

#6005 CommentsAnalyzer - before static call
  src/Tokenizer/Analyzer/CommentsAnalyzer.php
  tests/Tokenizer/Analyzer/CommentsAnalyzerTest.php
Labels: kind/bug

#5997 NoSuperfluousPhpdocTagsFixer - Add union types support
  src/Fixer/Phpdoc/NoSuperfluousPhpdocTagsFixer.php
  tests/Fixer/Phpdoc/NoSuperfluousPhpdocTagsFixerTest.php
Labels: kind/enhancement

#6006 SCA/utilize PHP8.1
  src/Cache/Cache.php
  src/Cache/FileCacheManager.php
  src/Console/Application.php
  src/Console/Command/DescribeCommand.php
  src/Console/ConfigurationResolver.php
  src/Console/WarningsDetector.php
  src/DocBlock/DocBlock.php
  src/Documentation/DocumentationGenerator.php
  src/Fixer/Basic/NonPrintableCharacterFixer.php
  src/Fixer/ClassNotation/FinalInternalClassFixer.php
  src/Fixer/Comment/NoEmptyCommentFixer.php
  src/Fixer/Comment/SingleLineCommentStyleFixer.php
  src/Fixer/ConstantNotation/NativeConstantInvocationFixer.php
  src/Fixer/ControlStructure/NoAlternativeSyntaxFixer.php
  src/Fixer/ControlStructure/NoUnneededCurlyBracesFixer.php
  src/Fixer/FunctionNotation/NativeFunctionInvocationFixer.php
  src/Fixer/Import/OrderedImportsFixer.php
  src/Fixer/Phpdoc/GeneralPhpdocAnnotationRemoveFixer.php
  src/Fixer/Phpdoc/PhpdocAddMissingParamAnnotationFixer.php
  src/Fixer/Phpdoc/PhpdocAnnotationWithoutDotFixer.php
  src/Fixer/Phpdoc/PhpdocInlineTagNormalizerFixer.php
  src/Fixer/Phpdoc/PhpdocReturnSelfReferenceFixer.php
  src/Fixer/Phpdoc/PhpdocTypesOrderFixer.php
  src/Fixer/Whitespace/SingleBlankLineAtEofFixer.php
  src/RuleSet/RuleSet.php
  src/Tokenizer/Analyzer/CommentsAnalyzer.php
  src/Tokenizer/Tokens.php
  src/Tokenizer/TokensAnalyzer.php
  src/Utils.php
  tests/AutoReview/ProjectCodeTest.php
  tests/Fixer/ControlStructure/NoUnneededControlParenthesesFixerTest.php
  tests/RuleSet/RuleSetTest.php
  tests/RuleSet/Sets/AbstractSetTest.php
  tests/Test/AbstractTransformerTestCase.php
Labels: kind/cleanup

#5996 Fix URL to Doctrine Annotations documentation
  doc/ruleSets/DoctrineAnnotation.rst
  src/RuleSet/Sets/DoctrineAnnotationSet.php
Labels: topic/documentation

#6007 YodaStyleFixer - PHP8 named arguments support
  src/Fixer/ControlStructure/YodaStyleFixer.php
  tests/Fixer/ControlStructure/YodaStyleFixerTest.php
Labels: kind/bug

#6011 NoSuperfluousPhpdocTagsFixer - Remove superfluous annotation `@abstract` and `@final`
  src/DocBlock/Annotation.php
  src/DocBlock/DocBlock.php
  src/DocBlock/Line.php
  src/DocBlock/Tag.php
  src/DocBlock/TagComparator.php
  src/Fixer/Phpdoc/NoSuperfluousPhpdocTagsFixer.php
  tests/Fixer/Phpdoc/NoSuperfluousPhpdocTagsFixerTest.php
Labels: kind/enhancement

#6018 PhpdocLineSpan - Allow certain types to be ignored
  doc/rules/phpdoc/phpdoc_line_span.rst
  src/Fixer/Phpdoc/PhpdocLineSpanFixer.php
  tests/Fixer/Phpdoc/PhpdocLineSpanFixerTest.php
Labels: kind/enhancement

#6021 Linter/*Exception - Tag as final
  src/Linter/LintingException.php
  src/Linter/UnavailableLinterException.php
Labels: kind/cleanup, RTM

#6020 RegularCallableCallFixer - case insensitive fixing
  src/Fixer/FunctionNotation/RegularCallableCallFixer.php
  tests/Fixer/FunctionNotation/RegularCallableCallFixerTest.php
Labels: kind/bug, RTM

#6019 Improve test coverage
  src/DocBlock/TypeExpression.php
  tests/AbstractFixerTest.php
  tests/AutoReview/FixerFactoryTest.php
  tests/AutoReview/ProjectCodeTest.php
  tests/Differ/UnifiedDifferTest.php
  tests/Doctrine/Annotation/TokensTest.php
  tests/FixerFactoryTest.php
  tests/Fixtures/Test/AbstractFixerTest/SimpleFixer.php
  tests/Fixtures/TestRuleSet.php
  tests/Linter/ProcessLinterTest.php
  tests/RuleSet/AbstractMigrationSetDescriptionTest.php
  tests/RuleSet/AbstractRuleSetDescriptionTest.php
  tests/Test/AbstractFixerTestCase.php
  tests/UtilsTest.php
Labels: topic/tests

#5962 DX: Add return types
  src/Fixer/Phpdoc/NoSuperfluousPhpdocTagsFixer.php
  tests/Console/Command/SelfUpdateCommandTest.php
  tests/FixerConfiguration/FixerConfigurationResolverTest.php
  tests/Test/AbstractTransformerTestCase.php
Labels: kind/cleanup

#6023 OrderedClassElementsFixer - PHP8.1 readonly properties support
  doc/rules/class_notation/ordered_class_elements.rst
  src/Fixer/ClassNotation/OrderedClassElementsFixer.php
  tests/Fixer/ClassNotation/OrderedClassElementsFixerTest.php
Labels: kind/enhancement, topic/PHP8.1

#6028 BinaryOperatorSpacesFixer - list all operators in doc
  doc/rules/operator/binary_operator_spaces.rst
  src/Fixer/Operator/BinaryOperatorSpacesFixer.php
Labels: topic/documentation

#6027 MbStrFunctionsFixer - more details about risky
  doc/rules/alias/mb_str_functions.rst
  src/Fixer/Alias/MbStrFunctionsFixer.php
Labels: topic/documentation, RTM

#6030 SingleSpaceAfterConstructFixer - Add `switch` support
  doc/rules/language_construct/single_space_after_construct.rst
  src/Fixer/LanguageConstruct/SingleSpaceAfterConstructFixer.php
  tests/Fixer/LanguageConstruct/SingleSpaceAfterConstructFixerTest.php
Labels: kind/enhancement

#6031 NoSpaceAroundDoubleColonFixer - introduction
  doc/ruleSets/PSR2.rst
  doc/rules/index.rst
  doc/rules/operator/no_space_around_double_colon.rst
  src/Fixer/Operator/NoSpaceAroundDoubleColonFixer.php
  src/RuleSet/Sets/PSR2Set.php
  tests/Fixer/Operator/NoSpaceAroundDoubleColonFixerTest.php
  tests/RuleSet/RuleSetTest.php
Labels: kind/feature

#6029 PhpUnitDedicateAssertFixer - add "assertStringContainsString" and "as…
  src/Fixer/Alias/ModernizeStrposFixer.php
  src/Fixer/PhpUnit/PhpUnitDedicateAssertFixer.php
  tests/AutoReview/FixerFactoryTest.php
  tests/Fixer/PhpUnit/PhpUnitDedicateAssertFixerTest.php
  tests/Fixtures/Integration/priority/modernize_strpos,php_unit_dedicate_assert.test
Labels: kind/enhancement, topic/PHP8.1

#4834 AssignNullCoalescingToCoalesceEqualFixer - introduction
  doc/ruleSets/PHP74Migration.rst
  doc/rules/index.rst
  doc/rules/operator/assign_null_coalescing_to_coalesce_equal.rst
  src/Fixer/Operator/AssignNullCoalescingToCoalesceEqualFixer.php
  src/Fixer/Operator/BinaryOperatorSpacesFixer.php
  src/Fixer/Operator/TernaryToNullCoalescingFixer.php
  src/Fixer/Whitespace/NoWhitespaceInBlankLineFixer.php
  src/RuleSet/Sets/PHP74MigrationSet.php
  tests/AutoReview/FixerFactoryTest.php
  tests/Fixer/Operator/AssignNullCoalescingToCoalesceEqualFixerTest.php
  tests/Fixtures/Integration/priority/assign_null_coalescing_to_coalesce_equal,binary_operator_spaces.test
  tests/Fixtures/Integration/priority/assign_null_coalescing_to_coalesce_equal,no_whitespace_in_blank_line.test
  tests/Fixtures/Integration/priority/ternary_to_null_coalescing,assign_null_coalescing_to_coalesce_equal.test
Labels: kind/feature, topic/PHP8

#6034 7.0|7.1 - cleanup tests
  tests/Fixer/Basic/NonPrintableCharacterFixerTest.php
  tests/Fixer/Casing/ConstantCaseFixerTest.php
  tests/Fixer/Casing/LowercaseStaticReferenceFixerTest.php
  tests/Fixer/Casing/NativeFunctionTypeDeclarationCasingFixerTest.php
  tests/Fixer/ClassNotation/NoNullPropertyInitializationFixerTest.php
  tests/Fixer/ClassNotation/SelfAccessorFixerTest.php
  tests/Fixer/ClassNotation/SingleClassElementPerStatementFixerTest.php
  tests/Fixer/ClassNotation/VisibilityRequiredFixerTest.php
  tests/Fixer/ConstantNotation/NativeConstantInvocationFixerTest.php
  tests/Fixer/ControlStructure/NoUselessElseFixerTest.php
  tests/Fixer/ControlStructure/SwitchContinueToBreakFixerTest.php
  tests/Fixer/FunctionNotation/CombineNestedDirnameFixerTest.php
  tests/Fixer/FunctionNotation/LambdaNotUsedImportFixerTest.php
  tests/Fixer/FunctionNotation/NoUnreachableDefaultArgumentValueFixerTest.php
  tests/Fixer/FunctionNotation/NoUselessSprintfFixerTest.php
  tests/Fixer/FunctionNotation/NullableTypeDeclarationForDefaultNullValueFixerTest.php
  tests/Fixer/FunctionNotation/PhpdocToParamTypeFixerTest.php
  tests/Fixer/FunctionNotation/PhpdocToReturnTypeFixerTest.php
  tests/Fixer/FunctionNotation/SingleLineThrowFixerTest.php
  tests/Fixer/FunctionNotation/VoidReturnFixerTest.php
  tests/Fixer/Import/FullyQualifiedStrictTypesFixerTest.php
  tests/Fixer/Import/GroupImportFixerTest.php
  tests/Fixer/Import/SingleImportPerStatementFixerTest.php
  tests/Fixer/LanguageConstruct/SingleSpaceAfterConstructFixerTest.php
  tests/Fixer/ListNotation/ListSyntaxFixerTest.php
  tests/Fixer/NamespaceNotation/CleanNamespaceFixerTest.php
  tests/Fixer/Operator/BinaryOperatorSpacesFixerTest.php
  tests/Fixer/Operator/IncrementStyleFixerTest.php
  tests/Fixer/Operator/OperatorLinebreakFixerTest.php
  tests/Fixer/Phpdoc/PhpdocAddMissingParamAnnotationFixerTest.php
  tests/Fixer/Phpdoc/PhpdocLineSpanFixerTest.php
  tests/Fixer/Phpdoc/PhpdocToCommentFixerTest.php
  tests/Fixer/ReturnNotation/SimplifiedNullReturnFixerTest.php
  tests/Fixer/StringNotation/ExplicitStringVariableFixerTest.php
  tests/Fixer/Whitespace/CompactNullableTypehintFixerTest.php
  tests/Tokenizer/Analyzer/ClassyAnalyzerTest.php
  tests/Tokenizer/Analyzer/CommentsAnalyzerTest.php
  tests/Tokenizer/Analyzer/ControlCaseStructuresAnalyzerTest.php
  tests/Tokenizer/Analyzer/ReferenceAnalyzerTest.php
  tests/Tokenizer/TokensAnalyzerTest.php
  tests/Tokenizer/TokensTest.php
  tests/Tokenizer/Transformer/AttributeTransformerTest.php
  tests/Tokenizer/Transformer/NullableTypeTransformerTest.php
  tests/Tokenizer/Transformer/SquareBraceTransformerTest.php
Labels: topic/tests

#6035 Documentation generation split up and add list.
  doc/list.rst
  doc/rules/index.rst
  src/Console/Command/DocumentationCommand.php
  src/Documentation/DocumentationLocator.php
  src/Documentation/FixerDocumentGenerator.php
  src/Documentation/ListDocumentGenerator.php
  src/Documentation/RstUtils.php
  src/Documentation/RuleSetDocumentationGenerator.php
  src/Utils.php
  tests/AutoReview/DocumentationTest.php
  tests/AutoReview/ProjectCodeTest.php
Labels: topic/documentation
