Repository PHP-CS-Fixer/PHP-CS-Fixer, pull requests merged in 2021-01, with the labels that each got.

#5412 3.0 - cleanup
  UPGRADE-v3.md
  doc/ruleSets/PHP70MigrationRisky.rst
  doc/ruleSets/SymfonyRisky.rst
  doc/rules/basic/non_printable_character.rst
  doc/rules/constant_notation/native_constant_invocation.rst
  doc/rules/function_notation/native_function_invocation.rst
  src/Fixer/Basic/NonPrintableCharacterFixer.php
  src/Fixer/ConstantNotation/NativeConstantInvocationFixer.php
  src/Fixer/FunctionNotation/NativeFunctionInvocationFixer.php
  src/RuleSet/Sets/PHP70MigrationRiskySet.php
  src/RuleSet/Sets/SymfonyRiskySet.php
  src/Tokenizer/TokensAnalyzer.php
  tests/Fixer/Basic/NonPrintableCharacterFixerTest.php
  tests/Fixer/ConstantNotation/NativeConstantInvocationFixerTest.php
  tests/Fixer/FunctionNotation/NativeFunctionInvocationFixerTest.php
  tests/Tokenizer/TokensAnalyzerTest.php
Labels: kind/BC break, kind/cleanup, topic/documentation

#5417 Further BC cleanup for 3.0
  src/RuleSet.php
  src/RuleSet/RuleSet.php
  tests/AutoReview/ProjectCodeTest.php
Labels: kind/BC break, kind/cleanup

#5423 DX: PHPUnit - disable verbose by default
  phpunit.xml.dist
Labels: topic/tests

#5429 DX: Drop speedtrap PHPUnit listener
  composer.json
  phpunit.xml.dist
Labels: topic/tests

#5418 Drop src/Test namespace
  .composer-require-checker.json
  .gitattributes
  .github/workflows/sca.yml
  UPGRADE-v3.md
  composer.json
  phpstan.neon
  src/Test/AbstractFixerTestCase.php
  src/Test/AbstractIntegrationTestCase.php
  src/Test/IntegrationCase.php
  tests/AutoReview/ProjectCodeTest.php
  tests/Smoke/InstallViaComposerTest.php
  tests/Test/IntegrationCaseTest.php
  tests/Test/IsIdenticalConstraint.php
  tests/TestCase.php
Labels: kind/BC break, kind/cleanup

#5436 Drop mapping of strings to boolean option other than yes/no
  doc/usage.rst
  src/Console/Command/HelpCommand.php
  src/Console/ConfigurationResolver.php
  tests/Console/Command/FixCommandTest.php
  tests/Console/ConfigurationResolverTest.php
Labels: kind/BC break

#5433 PhpUnitTestCaseStaticMethodCallsFixer - fix for abstract static method
  src/Fixer/PhpUnit/PhpUnitTestCaseStaticMethodCallsFixer.php
  tests/Fixer/PhpUnit/PhpUnitTestCaseStaticMethodCallsFixerTest.php
Labels: kind/bug

#5414 TypeAlternationTransformer - T_FN support
  src/Tokenizer/Analyzer/ArgumentsAnalyzer.php
  src/Tokenizer/Analyzer/FunctionsAnalyzer.php
  src/Tokenizer/Transformer/TypeAlternationTransformer.php
  tests/Tokenizer/Analyzer/FunctionsAnalyzerTest.php
  tests/Tokenizer/Transformer/TypeAlternationTransformerTest.php
Labels: kind/enhancement, topic/PHP8

#5453 SingleSpaceAfterConstructFixer - better handling of closing parenthesis and brace
  src/Fixer/LanguageConstruct/SingleSpaceAfterConstructFixer.php
  tests/Fixer/LanguageConstruct/SingleSpaceAfterConstructFixerTest.php
Labels: topic/PHP8

#5454 NullableTypeDeclarationForDefaultNullValueFixer - support property promotion via constructor
  src/Tokenizer/Analyzer/ArgumentsAnalyzer.php
  tests/Fixer/FunctionNotation/NullableTypeDeclarationForDefaultNullValueFixerTest.php
  tests/Tokenizer/Analyzer/ArgumentsAnalyzerTest.php
Labels: topic/PHP8

#5455 PhpdocToCommentFixer - add support for attributes
  src/Tokenizer/Analyzer/CommentsAnalyzer.php
  tests/Fixer/Phpdoc/PhpdocToCommentFixerTest.php
  tests/Tokenizer/Analyzer/CommentsAnalyzerTest.php
Labels: topic/PHP8

#5462 NullableTypeDeclarationForDefaultNullValueFixer - support union types
  src/Fixer/FunctionNotation/NullableTypeDeclarationForDefaultNullValueFixer.php
  tests/Fixer/FunctionNotation/NullableTypeDeclarationForDefaultNullValueFixerTest.php
Labels: kind/bug, topic/PHP8

#5479 ArraySyntaxFixer, ListSyntaxFixer - change default syntax to short
  UPGRADE-v3.md
  doc/ruleSets/PHP54Migration.rst
  doc/ruleSets/PHP71Migration.rst
  doc/ruleSets/Symfony.rst
  doc/rules/array_notation/array_syntax.rst
  doc/rules/list_notation/list_syntax.rst
  src/Fixer/ArrayNotation/ArraySyntaxFixer.php
  src/Fixer/ListNotation/ListSyntaxFixer.php
  src/RuleSet/Sets/PHP54MigrationSet.php
  src/RuleSet/Sets/PHP71MigrationSet.php
  src/RuleSet/Sets/SymfonySet.php
  tests/Fixer/ArrayNotation/ArraySyntaxFixerTest.php
  tests/Fixer/ListNotation/ListSyntaxFixerTest.php
Labels: kind/BC break, kind/enhancement

#5480 Tokens::findBlockEnd - drop deprecated argument
  src/Tokenizer/Tokens.php
  tests/Tokenizer/TokensTest.php
Labels: kind/BC break

#5477 Drop diff-format
  UPGRADE-v3.md
  doc/usage.rst
  src/Console/Command/FixCommand.php
  src/Console/Command/HelpCommand.php
  src/Console/ConfigurationResolver.php
  tests/Console/ConfigurationResolverTest.php
Labels: kind/BC break
