Repository PHP-CS-Fixer/PHP-CS-Fixer, pull requests merged in 2021-02, with the labels that each got.

#5485 ClassAttributesSeparationFixer - drop deprecated flat list configuration
  UPGRADE-v3.md
  src/Fixer/ClassNotation/ClassAttributesSeparationFixer.php
  tests/Fixer/ClassNotation/ClassAttributesSeparationFixerTest.php
Labels: kind/BC break

#5491 Support php8 static return type for NoSuperfluousPhpdocTagsFixer
  src/Fixer/Phpdoc/NoSuperfluousPhpdocTagsFixer.php
  tests/Fixer/Phpdoc/NoSuperfluousPhpdocTagsFixerTest.php
Labels: kind/enhancement

#5484 NullableTypeDeclarationForDefaultNullValueFixer - handle mixed pseudotype
  src/Fixer/FunctionNotation/NullableTypeDeclarationForDefaultNullValueFixer.php
  tests/Fixer/FunctionNotation/NullableTypeDeclarationForDefaultNullValueFixerTest.php
Labels: kind/bug
