Repository PHP-CS-Fixer/PHP-CS-Fixer, pull requests merged in 2021-11, with the labels that each got.

#6107 Drop support of PHPUnit v7 dependency
  composer.json
Labels: topic/tests

#6109 Add return type to `DummyTestSplFileInfo::getRealPath()`
  tests/Differ/DummyTestSplFileInfo.php
Labels: topic/tests

#6116 CI: remove installation of mbstring polyfill in build script, it's required dependency now
  dev-tools/build.sh
Labels: RTM, topic/tests

#6117 SingleSpaceAfterConstruct - handle before destructuring close brace
  src/Fixer/LanguageConstruct/SingleSpaceAfterConstructFixer.php
  tests/Fixer/LanguageConstruct/SingleSpaceAfterConstructFixerTest.php
Labels: kind/bug, RTM

#6119 OrderedClassElementsFixer - PHPUnit assert(Pre|Post)Conditions methods support
  src/Fixer/ClassNotation/OrderedClassElementsFixer.php
  tests/Fixer/ClassNotation/OrderedClassElementsFixerTest.php
Labels: kind/feature, RTM

#6122 NoMultilineWhitespaceAroundDoubleArrowFixer - must run before MethodArgumentSpaceFixer
  src/Fixer/ArrayNotation/NoMultilineWhitespaceAroundDoubleArrowFixer.php
  src/Fixer/FunctionNotation/MethodArgumentSpaceFixer.php
  tests/AutoReview/FixerFactoryTest.php
  tests/Fixtures/Integration/priority/no_multiline_whitespace_around_double_arrow,method_argument_space.test
Labels: kind/bug, RTM

#6127 Remove 2nd parameter to XdebugHandler constructor
  php-cs-fixer
Labels: kind/cleanup, RTM

#6121 Use Tokens::ensureWhitespaceAtIndex to simplify code
  src/Fixer/Comment/HeaderCommentFixer.php
  src/Fixer/Comment/NoTrailingWhitespaceInCommentFixer.php
  src/Fixer/ControlStructure/NoBreakCommentFixer.php
  src/Fixer/FunctionNotation/MethodArgumentSpaceFixer.php
  src/Fixer/Import/NoUnusedImportsFixer.php
  src/Fixer/LanguageConstruct/SingleSpaceAfterConstructFixer.php
  src/Fixer/Operator/NotOperatorWithSuccessorSpaceFixer.php
  src/Fixer/Semicolon/NoSinglelineWhitespaceBeforeSemicolonsFixer.php
  src/Fixer/Whitespace/NoTrailingWhitespaceFixer.php
  src/Fixer/Whitespace/NoWhitespaceInBlankLineFixer.php
Labels: kind/cleanup, RTM

#6130 StrictParamFixer - must run before MethodArgumentSpaceFixer
  src/Fixer/FunctionNotation/MethodArgumentSpaceFixer.php
  src/Fixer/Strict/StrictParamFixer.php
  tests/AutoReview/FixerFactoryTest.php
  tests/Fixtures/Integration/priority/strict_param,method_argument_space.test
Labels: kind/bug, RTM

#6137 NewWithBracesFixer - must run before ClassDefinitionFixer
  src/Fixer/ClassNotation/ClassDefinitionFixer.php
  src/Fixer/Operator/NewWithBracesFixer.php
  tests/AutoReview/FixerFactoryTest.php
  tests/Fixtures/Integration/priority/new_with_braces,class_definition.test
Labels: kind/bug
