Repository PHP-CS-Fixer/PHP-CS-Fixer, pull requests merged in 2021-05, with the labels that each got.

#4591 Refactor conversion of PHPDoc to type declarations
  doc/rules/function_notation/phpdoc_to_param_type.rst
  src/AbstractPhpdocToTypeDeclarationFixer.php
  src/DocBlock/Annotation.php
  src/DocBlock/DocBlock.php
  src/DocBlock/TypeExpression.php
  src/Fixer/FunctionNotation/PhpdocToParamTypeFixer.php
  src/Fixer/FunctionNotation/PhpdocToReturnTypeFixer.php
  src/Fixer/Phpdoc/NoSuperfluousPhpdocTagsFixer.php
  src/Tokenizer/Analyzer/NamespaceUsesAnalyzer.php
  src/Tokenizer/Analyzer/NamespacesAnalyzer.php
  tests/DocBlock/AnnotationTest.php
  tests/DocBlock/TypeExpressionTest.php
  tests/Fixer/FunctionNotation/PhpdocToParamTypeFixerTest.php
  tests/Fixer/FunctionNotation/PhpdocToReturnTypeFixerTest.php
  tests/Tokenizer/Analyzer/NamespaceUsesAnalyzerTest.php
  tests/Tokenizer/Analyzer/NamespacesAnalyzerTest.php
Labels: kind/bug, kind/enhancement, kind/refactoring

#4592 PhpdocToPropertyTypeFixer - introduction
  doc/rules/function_notation/phpdoc_to_property_type.rst
  doc/rules/function_notation/phpdoc_to_return_type.rst
  doc/rules/index.rst
  src/AbstractPhpdocToTypeDeclarationFixer.php
  src/Fixer/Comment/CommentToPhpdocFixer.php
  src/Fixer/FunctionNotation/PhpdocToParamTypeFixer.php
  src/Fixer/FunctionNotation/PhpdocToPropertyTypeFixer.php
  src/Fixer/FunctionNotation/PhpdocToReturnTypeFixer.php
  src/Fixer/Phpdoc/AlignMultilineCommentFixer.php
  src/Fixer/Phpdoc/PhpdocAlignFixer.php
  src/Fixer/Phpdoc/PhpdocIndentFixer.php
  src/Fixer/Phpdoc/PhpdocScalarFixer.php
  src/Fixer/Phpdoc/PhpdocToCommentFixer.php
  src/Fixer/Phpdoc/PhpdocTypesFixer.php
  tests/Fixer/FunctionNotation/PhpdocToPropertyTypeFixerTest.php
  tests/Fixer/FunctionNotation/PhpdocToReturnTypeFixerTest.php
  tests/Test/AbstractFixerTestCase.php
Labels: kind/feature

#5669 Remove TrailingCommaInMultilineArrayFixer
  UPGRADE-v3.md
  doc/rules/array_notation/trailing_comma_in_multiline_array.rst
  doc/rules/index.rst
  src/Fixer/ArrayNotation/TrailingCommaInMultilineArrayFixer.php
  tests/Fixer/ArrayNotation/TrailingCommaInMultilineArrayFixerTest.php
  tests/Fixtures/Integration/misc/PHP7_4.test
Labels: kind/BC break

#5670 PhpUnitNamespacedFixer - do not try to fix constant
  src/Fixer/PhpUnit/PhpUnitNamespacedFixer.php
  tests/Fixer/PhpUnit/PhpUnitNamespacedFixerTest.php
Labels: kind/bug

#5671 PhpdocToParamTypeFixer - do not change function call
  src/Fixer/FunctionNotation/PhpdocToParamTypeFixer.php
  tests/Fixer/FunctionNotation/PhpdocToParamTypeFixerTest.php
Labels: kind/bug

#5673 GroupImportFixer - Fix failing case
  src/Fixer/Import/GroupImportFixer.php
  tests/Fixer/Import/GroupImportFixerTest.php
Labels: kind/bug

#5710 [typo] add correct backquotes
  doc/usage.rst
Labels: topic/documentation

#5697 StrictParamFixer - fix for method definition
  src/Fixer/Strict/StrictParamFixer.php
  tests/Fixer/Strict/StrictParamFixerTest.php
Labels: kind/bug

#5689 Calculate code coverage on PHP 8
  .github/workflows/ci.yml
Labels: kind/enhancement

#5680 DX: benchmark.sh - ensure deps are updated to enable script working across less-similar branches
  benchmark.sh
Labels: kind/enhancement

#5679 PhpUnitNamespacedFixer - do not try to fix constant usage
  src/Fixer/PhpUnit/PhpUnitNamespacedFixer.php
  tests/Fixer/PhpUnit/PhpUnitNamespacedFixerTest.php
Labels: kind/bug

#5694 DX: fail on risky tests
  phpunit.xml.dist
Labels: kind/enhancement

#5702 CommentToPhpdocFixer - fix for single line comments starting with more than 2 slashes
  src/Fixer/Comment/CommentToPhpdocFixer.php
  tests/Fixer/Comment/CommentToPhpdocFixerTest.php
Labels: kind/bug

#5703 DateTimeImmutableFixer - fix for method definition
  src/Fixer/ClassUsage/DateTimeImmutableFixer.php
  tests/Fixer/ClassUsage/DateTimeImmutableFixerTest.php
Labels: kind/bug

#5687 FinalInternalClassFixer - fix for annotation with space after "@"
  src/Fixer/ClassNotation/FinalInternalClassFixer.php
  tests/Fixer/ClassNotation/FinalInternalClassFixerTest.php
Labels: kind/bug

#5681 RegularCallableCallFixer - fix for function name with escaped slash
  src/Fixer/FunctionNotation/RegularCallableCallFixer.php
  tests/Fixer/FunctionNotation/RegularCallableCallFixerTest.php
Labels: kind/bug

#5678 UseArrowFunctionsFixer - fix for return without value
  src/Fixer/FunctionNotation/UseArrowFunctionsFixer.php
  tests/Fixer/FunctionNotation/UseArrowFunctionsFixerTest.php
Labels: kind/bug

#5395 PhpdocTagTypeFixer: Do not modify array shapes
  src/Fixer/Phpdoc/PhpdocTagTypeFixer.php
  tests/Fixer/Phpdoc/PhpdocTagTypeFixerTest.php
Labels: kind/bug

#4914 Improve PHPDoc types support
  src/DocBlock/TypeExpression.php
  tests/DocBlock/AnnotationTest.php
  tests/DocBlock/TypeExpressionTest.php
  tests/Fixer/Phpdoc/NoSuperfluousPhpdocTagsFixerTest.php
Labels: kind/enhancement

#5721 Fix reStructuredText markup
  doc/custom_rules.rst
Labels: RTM, topic/documentation

#5725 Update LICENSE
  LICENSE
Labels: RTM, kind/enhancement

#5731 CI - Fix checkbashisms installation
  dev-tools/install.sh
Labels: topic/tests

#5730 Fix transforming deprecations into exceptions
  src/AbstractFixer.php
  src/Config.php
  src/Console/ConfigurationResolver.php
  src/Fixer/ClassNotation/ClassAttributesSeparationFixer.php
  src/Fixer/FunctionNotation/MethodArgumentSpaceFixer.php
  src/Fixer/Operator/AlignDoubleArrowFixerHelper.php
  src/Fixer/Operator/AlignEqualsFixerHelper.php
  src/Fixer/Operator/BinaryOperatorSpacesFixer.php
  src/Fixer/Whitespace/BlankLineBeforeStatementFixer.php
  src/Fixer/Whitespace/NoExtraBlankLinesFixer.php
  src/FixerConfiguration/FixerConfigurationResolver.php
  src/FixerConfiguration/FixerConfigurationResolverRootless.php
  src/FixerDefinition/FixerDefinition.php
  src/RuleSet/RuleSet.php
  src/Test/AbstractFixerTestCase.php
  src/Test/AbstractIntegrationTestCase.php
  src/Test/AccessibleObject.php
  src/Test/IntegrationCase.php
  src/Tokenizer/Token.php
  src/Tokenizer/Tokens.php
  src/Utils.php
  tests/Fixer/Operator/BinaryOperatorSpacesFixerTest.php
  tests/UtilsTest.php
Labels: kind/bug

#5740 DX: more type-related docblocks
  src/Config.php
  src/Console/Command/DescribeCommand.php
  src/Console/Command/DocumentationCommand.php
  src/Console/Command/FixCommand.php
  src/Console/Command/HelpCommand.php
  src/Console/Command/ListFilesCommand.php
  src/Console/Command/ListSetsCommand.php
  src/Console/Command/SelfUpdateCommand.php
  src/Console/ConfigurationResolver.php
  src/Doctrine/Annotation/Tokens.php
  src/Documentation/DocumentationGenerator.php
  src/Fixer/ArrayNotation/ArraySyntaxFixer.php
  src/Fixer/Basic/EncodingFixer.php
  src/Fixer/DoctrineAnnotation/DoctrineAnnotationArrayAssignmentFixer.php
  src/Fixer/DoctrineAnnotation/DoctrineAnnotationBracesFixer.php
  src/Fixer/DoctrineAnnotation/DoctrineAnnotationIndentationFixer.php
  src/Fixer/DoctrineAnnotation/DoctrineAnnotationSpacesFixer.php
  src/Fixer/FunctionNotation/FunctionDeclarationFixer.php
  src/Fixer/ListNotation/ListSyntaxFixer.php
  src/Fixer/Operator/ConcatSpaceFixer.php
  src/Fixer/PhpTag/FullOpeningTagFixer.php
  src/Fixer/Phpdoc/AlignMultilineCommentFixer.php
  src/Fixer/Phpdoc/PhpdocAnnotationWithoutDotFixer.php
  src/Fixer/Phpdoc/PhpdocReturnSelfReferenceFixer.php
  src/FixerConfiguration/AllowedValueSubset.php
  src/FixerDefinition/FixerDefinition.php
  src/WhitespacesFixerConfig.php
Labels: RTM, kind/enhancement

#5727 SingleSpaceAfterConstructFixer - Add support for `namespace`
  doc/rules/language_construct/single_space_after_construct.rst
  src/Fixer/LanguageConstruct/SingleSpaceAfterConstructFixer.php
  tests/Fixer/LanguageConstruct/SingleSpaceAfterConstructFixerTest.php
Labels: kind/enhancement

#5718 VoidReturnFixer - do not break syntax with magic methods
  src/Fixer/FunctionNotation/VoidReturnFixer.php
  tests/Fixer/FunctionNotation/VoidReturnFixerTest.php
Labels: kind/bug

#5746 Config - Improve deprecation message with details
  src/Config.php
  tests/ConfigTest.php
Labels: RTM, topic/documentation
