Repository PHP-CS-Fixer/PHP-CS-Fixer, pull requests merged in 2021-03, with the labels that each got.

#5550 TypeAlternationTransformer - fix for typed static properties
  src/Tokenizer/Transformer/TypeAlternationTransformer.php
  tests/Tokenizer/Transformer/TypeAlternationTransformerTest.php
Labels: kind/bug

#5552 DX: test relation between function_declaration and method_argument_space
  src/Fixer/FunctionNotation/FunctionDeclarationFixer.php
  src/Fixer/FunctionNotation/MethodArgumentSpaceFixer.php
  tests/AutoReview/FixerFactoryTest.php
  tests/Fixtures/Integration/priority/function_declaration,method_argument_space.test
Labels: kind/bug

#4085 Priority: AlignMultilineComment should run before every PhpdocFixer
  src/AbstractNoUselessElseFixer.php
  src/Fixer/Alias/NoAliasFunctionsFixer.php
  src/Fixer/Alias/PowToExponentiationFixer.php
  src/Fixer/Basic/BracesFixer.php
  src/Fixer/ClassNotation/SingleTraitInsertPerStatementFixer.php
  src/Fixer/Comment/CommentToPhpdocFixer.php
  src/Fixer/ControlStructure/ElseifFixer.php
  src/Fixer/ControlStructure/NoAlternativeSyntaxFixer.php
  src/Fixer/ControlStructure/NoUnneededCurlyBracesFixer.php
  src/Fixer/FunctionNotation/CombineNestedDirnameFixer.php
  src/Fixer/FunctionNotation/ImplodeCallFixer.php
  src/Fixer/FunctionNotation/MethodArgumentSpaceFixer.php
  src/Fixer/FunctionNotation/NoUselessSprintfFixer.php
  src/Fixer/FunctionNotation/PhpdocToParamTypeFixer.php
  src/Fixer/FunctionNotation/PhpdocToReturnTypeFixer.php
  src/Fixer/LanguageConstruct/DirConstantFixer.php
  src/Fixer/Phpdoc/AlignMultilineCommentFixer.php
  src/Fixer/Phpdoc/GeneralPhpdocAnnotationRemoveFixer.php
  src/Fixer/Phpdoc/GeneralPhpdocTagRenameFixer.php
  src/Fixer/Phpdoc/NoBlankLinesAfterPhpdocFixer.php
  src/Fixer/Phpdoc/NoEmptyPhpdocFixer.php
  src/Fixer/Phpdoc/NoSuperfluousPhpdocTagsFixer.php
  src/Fixer/Phpdoc/PhpdocAddMissingParamAnnotationFixer.php
  src/Fixer/Phpdoc/PhpdocAlignFixer.php
  src/Fixer/Phpdoc/PhpdocAnnotationWithoutDotFixer.php
  src/Fixer/Phpdoc/PhpdocInlineTagFixer.php
  src/Fixer/Phpdoc/PhpdocInlineTagNormalizerFixer.php
  src/Fixer/Phpdoc/PhpdocLineSpanFixer.php
  src/Fixer/Phpdoc/PhpdocNoAccessFixer.php
  src/Fixer/Phpdoc/PhpdocNoAliasTagFixer.php
  src/Fixer/Phpdoc/PhpdocNoEmptyReturnFixer.php
  src/Fixer/Phpdoc/PhpdocNoPackageFixer.php
  src/Fixer/Phpdoc/PhpdocNoUselessInheritdocFixer.php
  src/Fixer/Phpdoc/PhpdocOrderByValueFixer.php
  src/Fixer/Phpdoc/PhpdocOrderFixer.php
  src/Fixer/Phpdoc/PhpdocReturnSelfReferenceFixer.php
  src/Fixer/Phpdoc/PhpdocSeparationFixer.php
  src/Fixer/Phpdoc/PhpdocSingleLineVarSpacingFixer.php
  src/Fixer/Phpdoc/PhpdocSummaryFixer.php
  src/Fixer/Phpdoc/PhpdocTagCasingFixer.php
  src/Fixer/Phpdoc/PhpdocTagTypeFixer.php
  src/Fixer/Phpdoc/PhpdocTrimConsecutiveBlankLineSeparationFixer.php
  src/Fixer/Phpdoc/PhpdocTrimFixer.php
  src/Fixer/Phpdoc/PhpdocTypesOrderFixer.php
  src/Fixer/Phpdoc/PhpdocVarAnnotationCorrectOrderFixer.php
  src/Fixer/Phpdoc/PhpdocVarWithoutNameFixer.php
  src/Fixer/Semicolon/NoEmptyStatementFixer.php
  src/Fixer/Whitespace/ArrayIndentationFixer.php
  src/Fixer/Whitespace/LineEndingFixer.php
  src/Fixer/Whitespace/MethodChainingIndentationFixer.php
  tests/AutoReview/FixerFactoryTest.php
  tests/Fixtures/Integration/misc/issue_3879.test
Labels: kind/bug

#5464 NativeFunctionInvocationFixer - PHP 8 attributes
  src/Tokenizer/Analyzer/FunctionsAnalyzer.php
  tests/Fixer/FunctionNotation/NativeFunctionInvocationFixerTest.php
  tests/Tokenizer/Analyzer/FunctionsAnalyzerTest.php
Labels: kind/bug

#5421 PsrAutoloadingFixer - Fix PSR autoloading outside configured directory
  src/Fixer/Basic/PsrAutoloadingFixer.php
  tests/Fixer/Basic/PsrAutoloadingFixerTest.php
Labels: kind/bug

#5488 Do not distribute documentation
  .gitattributes
Labels: topic/release

#5563 Priority fix: SingleSpaceAfterConstructFixer must run before BracesFixer
  src/Fixer/Basic/BracesFixer.php
  src/Fixer/LanguageConstruct/SingleSpaceAfterConstructFixer.php
  tests/AutoReview/FixerFactoryTest.php
  tests/Fixtures/Integration/priority/single_space_after_construct,braces.test
Labels: kind/bug

#5562 Fix table row rendering for default values of array_syntax and list_syntax
  UPGRADE-v3.md
Labels: topic/documentation

#5560 PSR2: require visibility only for properties and methods
  doc/ruleSets/PSR2.rst
  doc/rules/class_notation/visibility_required.rst
  src/RuleSet/Sets/PSR2Set.php
  tests/Fixtures/Integration/set/@PSR2.test-in.php
  tests/Fixtures/Integration/set/@PSR2.test-out.php
  tests/RuleSet/RuleSetTest.php
Labels: kind/bug
