Repository PHP-CS-Fixer/PHP-CS-Fixer, pull requests merged in 2022-02, with the labels that each got.

#6243 PhpdocTypesOrderFixer - fix for intersection types
  src/DocBlock/Annotation.php
  src/DocBlock/TypeExpression.php
  src/Fixer/Phpdoc/PhpdocTypesOrderFixer.php
  tests/DocBlock/AnnotationTest.php
  tests/DocBlock/TypeExpressionTest.php
  tests/Fixer/Phpdoc/PhpdocTypesOrderFixerTest.php
Labels: kind/bug

#6265 NullableTypeDeclarationForDefaultNullValueFixer - handle "readonly" a…
  src/Fixer/FunctionNotation/NullableTypeDeclarationForDefaultNullValueFixer.php
  tests/Fixer/FunctionNotation/NullableTypeDeclarationForDefaultNullValueFixerTest.php
Labels: kind/bug

#6266 SimplifiedIfReturnFixer - handle statement in loop without braces
  src/Fixer/ControlStructure/SimplifiedIfReturnFixer.php
  tests/Fixer/ControlStructure/SimplifiedIfReturnFixerTest.php
Labels: kind/bug, RTM

#6267 NoUnneededImportAliasFixer - Introduction
  doc/list.rst
  doc/ruleSets/Symfony.rst
  doc/rules/import/no_unneeded_import_alias.rst
  doc/rules/index.rst
  src/Fixer/Import/NoUnneededImportAliasFixer.php
  src/Fixer/Import/SingleImportPerStatementFixer.php
  src/RuleSet/Sets/SymfonySet.php
  tests/AutoReview/FixerFactoryTest.php
  tests/Fixer/Import/NoUnneededImportAliasFixerTest.php
  tests/Fixtures/Integration/priority/no_unneeded_import_alias,no_singleline_whitespace_before_semicolons.test
Labels: kind/feature

#6262 ClassReferenceNameCasingFixer - introduction
  doc/list.rst
  doc/ruleSets/Symfony.rst
  doc/rules/casing/class_reference_name_casing.rst
  doc/rules/index.rst
  src/DocBlock/TypeExpression.php
  src/Fixer/Casing/ClassReferenceNameCasingFixer.php
  src/Fixer/ConstantNotation/NativeConstantInvocationFixer.php
  src/Fixer/FunctionNotation/NativeFunctionInvocationFixer.php
  src/Fixer/Import/GlobalNamespaceImportFixer.php
  src/RuleSet/Sets/SymfonySet.php
  src/Tokenizer/Analyzer/Analysis/NamespaceAnalysis.php
  src/Tokenizer/Analyzer/FunctionsAnalyzer.php
  tests/Fixer/Casing/ClassReferenceNameCasingFixerTest.php
  tests/Tokenizer/Analyzer/Analysis/NamespaceAnalysisTest.php
Labels: kind/feature

#6277 Add `is_scalar`, `sizeof`, `ini_get` in list of compiled functions
  src/Fixer/FunctionNotation/NativeFunctionInvocationFixer.php
  tests/Fixer/PhpTag/NoClosingTagFixerTest.php
  tests/Fixer/Semicolon/NoEmptyStatementFixerTest.php
  tests/Fixer/Semicolon/SemicolonAfterInstructionFixerTest.php
  tests/Tokenizer/TokensTest.php
Labels: kind/enhancement

#6274 SingleLineCommentSpacingFixer - Introduction
  doc/list.rst
  doc/ruleSets/Symfony.rst
  doc/rules/comment/single_line_comment_spacing.rst
  doc/rules/index.rst
  src/Fixer/Comment/SingleLineCommentSpacingFixer.php
  src/Fixer/Phpdoc/PhpdocToCommentFixer.php
  src/RuleSet/Sets/SymfonySet.php
  tests/AutoReview/FixerFactoryTest.php
  tests/Fixer/Comment/SingleLineCommentSpacingFixerTest.php
  tests/Fixtures/Integration/priority/phpdoc_to_comment,single_line_comment_spacing.test
  tests/Test/AbstractIntegrationCaseFactory.php
Labels: kind/feature

#6283 ClassReferenceNameCasingFixer - detect imports
  src/Fixer/Casing/ClassReferenceNameCasingFixer.php
  tests/Fixer/Casing/ClassReferenceNameCasingFixerTest.php
Labels: kind/bug

#6280 Fix bunch of enum issus
  doc/list.rst
  doc/rules/class_notation/class_attributes_separation.rst
  doc/rules/class_notation/class_definition.rst
  doc/rules/class_notation/no_unneeded_final_method.rst
  doc/rules/index.rst
  src/AbstractDoctrineAnnotationFixer.php
  src/Fixer/Basic/BracesFixer.php
  src/Fixer/ClassNotation/ClassAttributesSeparationFixer.php
  src/Fixer/ClassNotation/ClassDefinitionFixer.php
  src/Fixer/ClassNotation/NoNullPropertyInitializationFixer.php
  src/Fixer/ClassNotation/NoUnneededFinalMethodFixer.php
  src/Fixer/ClassNotation/OrderedClassElementsFixer.php
  src/Fixer/ClassNotation/ProtectedToPrivateFixer.php
  src/Fixer/PhpUnit/PhpUnitDedicateAssertInternalTypeFixer.php
  src/Fixer/Phpdoc/PhpdocReturnSelfReferenceFixer.php
  src/Fixer/Phpdoc/PhpdocVarWithoutNameFixer.php
  src/Tokenizer/Token.php
  src/Tokenizer/TokensAnalyzer.php
  tests/Fixer/Basic/PsrAutoloadingFixerTest.php
  tests/Fixer/Casing/MagicMethodCasingFixerTest.php
  tests/Fixer/ClassNotation/ClassAttributesSeparationFixerTest.php
  tests/Fixer/ClassNotation/ClassDefinitionFixerTest.php
  tests/Fixer/ClassNotation/NoBlankLinesAfterClassOpeningFixerTest.php
  tests/Fixer/ClassNotation/NoUnneededFinalMethodFixerTest.php
  tests/Fixer/ClassNotation/ProtectedToPrivateFixerTest.php
  tests/Fixer/ClassNotation/SingleClassElementPerStatementFixerTest.php
  tests/Fixer/ClassNotation/VisibilityRequiredFixerTest.php
  tests/Fixer/Comment/HeaderCommentFixerTest.php
  tests/Fixer/Import/GlobalNamespaceImportFixerTest.php
  tests/Fixer/Phpdoc/NoSuperfluousPhpdocTagsFixerTest.php
  tests/Fixer/Phpdoc/PhpdocLineSpanFixerTest.php
  tests/Fixer/Phpdoc/PhpdocReturnSelfReferenceFixerTest.php
  tests/Fixer/Phpdoc/PhpdocToCommentFixerTest.php
  tests/Fixer/Phpdoc/PhpdocVarWithoutNameFixerTest.php
  tests/Fixer/Semicolon/NoEmptyStatementFixerTest.php
  tests/Tokenizer/Analyzer/CommentsAnalyzerTest.php
  tests/Tokenizer/Analyzer/FunctionsAnalyzerTest.php
  tests/Tokenizer/TokenTest.php
  tests/Tokenizer/TokensAnalyzerTest.php
Labels: kind/bug, topic/PHP8.1

#6300 OrderedClassElementsFixer - handle enums
  doc/list.rst
  doc/rules/class_notation/ordered_class_elements.rst
  doc/rules/index.rst
  src/Fixer/ClassNotation/OrderedClassElementsFixer.php
  tests/Fixer/ClassNotation/OrderedClassElementsFixerTest.php
Labels: kind/enhancement, RTM, topic/PHP8.1

#6301 BracesFixer - handle enums
  src/Fixer/Basic/BracesFixer.php
  tests/Fixer/Basic/BracesFixerTest.php
Labels: kind/enhancement, RTM, braces related, topic/PHP8.1

#6302 Bump checkbashisms version
  dev-tools/install.sh
Labels: kind/enhancement, RTM

#6303 PHP8 - Utilize "get_debug_type"
  src/Fixer/Alias/RandomApiMigrationFixer.php
  src/Fixer/ConstantNotation/NativeConstantInvocationFixer.php
  src/Fixer/FunctionNotation/NativeFunctionInvocationFixer.php
  src/Runner/FileFilterIterator.php
  src/Tokenizer/Token.php
  tests/Fixer/Alias/RandomApiMigrationFixerTest.php
  tests/Fixer/ConstantNotation/NativeConstantInvocationFixerTest.php
  tests/Fixer/FunctionNotation/NativeFunctionInvocationFixerTest.php
Labels: kind/cleanup

#6295 PhpUnitTestCaseIndicator - Check if PHPUnit-test class extends anothe…
  src/Indicator/PhpUnitTestCaseIndicator.php
  tests/Fixer/PhpUnit/PhpUnitInternalClassFixerTest.php
  tests/Fixer/PhpUnit/PhpUnitSizeClassFixerTest.php
  tests/Fixtures/Integration/priority/php_unit_test_annotation,no_empty_phpdoc.test
  tests/Fixtures/Integration/priority/php_unit_test_annotation,php_unit_method_casing.test
  tests/Fixtures/Integration/priority/php_unit_test_annotation,phpdoc_trim.test
  tests/Indicator/PhpUnitTestCaseIndicatorTest.php
Labels: kind/enhancement
