Repository PHP-CS-Fixer/PHP-CS-Fixer, pull requests merged in 2022-09, with the labels that each got.

#6606 DX: Update GitHub Actions
  .github/workflows/ci.yml
Labels: RTM

#6447 feature: NoUselessConcatOperatorFixer - Introduction
  .php-cs-fixer.dist.php
  doc/list.rst
  doc/ruleSets/Symfony.rst
  doc/rules/index.rst
  doc/rules/operator/no_useless_concat_operator.rst
  src/Fixer/Alias/BacktickToShellExecFixer.php
  src/Fixer/Alias/EregToPregFixer.php
  src/Fixer/Alias/SetTypeToCastFixer.php
  src/Fixer/FunctionNotation/DateTimeCreateFromFormatCallFixer.php
  src/Fixer/FunctionNotation/RegularCallableCallFixer.php
  src/Fixer/Operator/NoUselessConcatOperatorFixer.php
  src/Fixer/PhpUnit/PhpUnitDedicateAssertInternalTypeFixer.php
  src/Fixer/StringNotation/EscapeImplicitBackslashesFixer.php
  src/Fixer/StringNotation/NoBinaryStringFixer.php
  src/Fixer/StringNotation/SingleQuoteFixer.php
  src/RuleSet/Sets/SymfonySet.php
  tests/AutoReview/FixerFactoryTest.php
  tests/Fixer/Operator/NoUselessConcatOperatorFixerTest.php
  tests/Fixer/PhpUnit/PhpUnitDedicateAssertInternalTypeFixerTest.php
  tests/Fixtures/Integration/priority/no_binary_string,no_useless_concat_operator.test
  tests/Fixtures/Integration/priority/no_useless_concat_operator,date_time_create_from_format_call.test
  tests/Fixtures/Integration/priority/no_useless_concat_operator,ereg_to_preg.test
  tests/Fixtures/Integration/priority/no_useless_concat_operator,php_unit_dedicate_assert_internal_type.test
  tests/Fixtures/Integration/priority/no_useless_concat_operator,regular_callable_call.test
  tests/Fixtures/Integration/priority/no_useless_concat_operator,set_type_to_cast.test
  tests/Fixtures/Integration/priority/single_quote,no_useless_concat_operator.test
Labels: kind/feature

#6621 feature: Add `@PHP82Migration` ruleset
  doc/list.rst
  doc/ruleSets/PHP82Migration.rst
  doc/ruleSets/index.rst
  doc/rules/array_notation/array_syntax.rst
  doc/rules/array_notation/no_whitespace_before_comma_in_array.rst
  doc/rules/array_notation/normalize_index_brace.rst
  doc/rules/basic/octal_notation.rst
  doc/rules/cast_notation/no_unset_cast.rst
  doc/rules/cast_notation/short_scalar_cast.rst
  doc/rules/class_notation/visibility_required.rst
  doc/rules/control_structure/trailing_comma_in_multiline.rst
  doc/rules/function_notation/method_argument_space.rst
  doc/rules/list_notation/list_syntax.rst
  doc/rules/namespace_notation/clean_namespace.rst
  doc/rules/operator/assign_null_coalescing_to_coalesce_equal.rst
  doc/rules/operator/ternary_to_null_coalescing.rst
  doc/rules/string_notation/simple_to_complex_string_variable.rst
  doc/rules/whitespace/heredoc_indentation.rst
  src/RuleSet/Sets/PHP82MigrationSet.php
  tests/Fixtures/Integration/misc/PHP8_2.test
  tests/Fixtures/Integration/set/@PHP82Migration.test
  tests/Fixtures/Integration/set/@PHP82Migration.test-in.php
  tests/Fixtures/Integration/set/@PHP82Migration.test-out.php
  tests/RuleSet/Sets/PHP82MigrationSetTest.php
Labels: topic/PHP8.2

#5792 feature: NoSuperfluousPhpdocTagsFixer - support untyped and empty annotations in phpdoc
  src/DocBlock/TypeExpression.php
  src/Fixer/Phpdoc/NoSuperfluousPhpdocTagsFixer.php
  tests/DocBlock/AnnotationTest.php
  tests/DocBlock/TypeExpressionTest.php
  tests/Fixer/Phpdoc/NoSuperfluousPhpdocTagsFixerTest.php
  tests/Fixtures/Integration/misc/PHP8_0.test
Labels: kind/enhancement
