Repository PHP-CS-Fixer/PHP-CS-Fixer, pull requests merged in 2022-01, with the labels that each got.

#6209 OrderedClassElementsFixer - PHP8.0 support abstract private methods in traits
  doc/list.rst
  doc/rules/class_notation/ordered_class_elements.rst
  src/Fixer/ClassNotation/OrderedClassElementsFixer.php
  tests/Fixer/ClassNotation/OrderedClassElementsFixerTest.php
Labels: kind/bug, RTM

#6210 NullableTypeDeclarationForDefaultNullValueFixer - fix tests
  tests/Fixer/FunctionNotation/NullableTypeDeclarationForDefaultNullValueFixerTest.php
Labels: kind/bug, RTM

#6205 DX: bump PHPUnit to v9, PHPUnit bridge to v6 and Prophecy-PHPUnit to v2
  composer.json
  tests/TestCase.php
Labels: kind/cleanup

#6224 ArgumentsAnalyzer - support PHP8.1 readonly
  src/Fixer/FunctionNotation/NullableTypeDeclarationForDefaultNullValueFixer.php
  src/Tokenizer/Analyzer/ArgumentsAnalyzer.php
  tests/Fixer/FunctionNotation/NullableTypeDeclarationForDefaultNullValueFixerTest.php
  tests/Tokenizer/Analyzer/ArgumentsAnalyzerTest.php
Labels: kind/bug, RTM

#6229 Simplify Tokens::isMonolithicPhp tests
  tests/Tokenizer/TokensTest.php
Labels: kind/cleanup, topic/tests

#6232 Use expectNotToPerformAssertions where applicable
  tests/AutoReview/ProjectCodeTest.php
  tests/AutoReview/TransformerTest.php
  tests/RuleSet/RuleSetTest.php
  tests/Test/AbstractFixerTestCase.php
  tests/Test/AbstractTransformerTestCase.php
Labels: topic/tests

#6237 DX: Application - better display version when displaying gitSha
  src/Console/Application.php
  tests/Smoke/PharTest.php
Labels: RTM

#6063 PhpdocTypesOrderFixer - Improve nested types support
  src/DocBlock/TypeExpression.php
  src/Fixer/Phpdoc/PhpdocTypesOrderFixer.php
  tests/DocBlock/TypeExpressionTest.php
  tests/Fixer/Phpdoc/PhpdocTypesOrderFixerTest.php
Labels: kind/bug, kind/enhancement, RTM
