Repository PHP-CS-Fixer/PHP-CS-Fixer, pull requests merged in 2022-10, with the labels that each got.

#6623 feature: [PHP8.2] Support for new standalone types (`null`, `true`, `false`)
  src/Fixer/Casing/NativeFunctionTypeDeclarationCasingFixer.php
  tests/Fixer/Casing/NativeFunctionTypeDeclarationCasingFixerTest.php
  tests/Fixtures/Integration/misc/PHP8_2.test
Labels: topic/PHP8.2

#6661 bug: IsNullFixer - handle casting
  src/Fixer/LanguageConstruct/IsNullFixer.php
  tests/Fixer/LanguageConstruct/IsNullFixerTest.php
Labels: kind/bug

#6667 bug: BracesFixer - Fix unexpected extra blank line
  src/Fixer/Whitespace/StatementIndentationFixer.php
  tests/Fixer/Basic/BracesFixerTest.php
Labels: kind/bug

#6666 docs: Use case insensitive sorting for options
  doc/list.rst
  doc/rules/alias/no_alias_functions.rst
  src/FixerConfiguration/AllowedValueSubset.php
  tests/FixerConfiguration/AllowedValueSubsetTest.php
Labels: topic/documentation
