Repository PHP-CS-Fixer/PHP-CS-Fixer, pull requests merged in 2022-03, with the labels that each got.

#6327 bump polyfills
  composer.json
Labels: RTM

#6333 BinaryOperatorSpacesFixer - Fix for alignment in `elseif`
  src/Fixer/Operator/BinaryOperatorSpacesFixer.php
  tests/Fixer/Operator/BinaryOperatorSpacesFixerTest.php
Labels: kind/bug

#6328 DX: .gitignore ASC file
  .gitignore
  php-cs-fixer.phar.asc
Labels: kind/enhancement

#6286 DateTimeCreateFromFormatCallFixer - Introduction
  doc/list.rst
  doc/rules/function_notation/date_time_create_from_format_call.rst
  doc/rules/index.rst
  src/Fixer/FunctionNotation/DateTimeCreateFromFormatCallFixer.php
  tests/Fixer/FunctionNotation/DateTimeCreateFromFormatCallFixerTest.php
Labels: kind/feature

#6331 ClassReferenceNameCasingFixer - Fix false hits
  src/Fixer/Casing/ClassReferenceNameCasingFixer.php
  tests/Fixer/Casing/ClassReferenceNameCasingFixerTest.php
Labels: kind/bug

#6312 TypesSpacesFixer - add option for CS of catching multiple types of exceptions
  doc/list.rst
  doc/rules/whitespace/types_spaces.rst
  src/Fixer/Whitespace/TypesSpacesFixer.php
  tests/Fixer/Whitespace/TypesSpacesFixerTest.php
Labels: kind/feature
