Repository PHP-CS-Fixer/PHP-CS-Fixer, pull requests merged in 2022-11, with the labels that each got.

#6677 bug: TrailingCommaInMultilineFixer - do not add trailing comma when there is no break line after last element
  src/Fixer/ArrayNotation/NoMultilineWhitespaceAroundDoubleArrowFixer.php
  src/Fixer/ControlStructure/TrailingCommaInMultilineFixer.php
  tests/AutoReview/FixerFactoryTest.php
  tests/Fixer/ControlStructure/TrailingCommaInMultilineFixerTest.php
  tests/Fixtures/Integration/priority/no_multiline_whitespace_around_double_arrow,trailing_comma_in_multiline.test
Labels: kind/bug

#6674 minor: displaying number of checked files
  docker-compose.override.yaml.dist
  src/Console/Command/FixCommand.php
  src/Console/Report/FixReport/ReportSummary.php
  src/Console/Report/FixReport/TextReporter.php
  tests/Console/Report/FixReport/AbstractReporterTestCase.php
  tests/Console/Report/FixReport/ReportSummaryTest.php
  tests/Console/Report/FixReport/TextReporterTest.php
  tests/Smoke/CiIntegrationTest.php
  tests/Smoke/StdinTest.php
Labels: kind/enhancement

#6679 docs: Fix docs for disabled rules in rulesets
  doc/ruleSets/PhpCsFixer.rst
  doc/ruleSets/SymfonyRisky.rst
  src/Documentation/RuleSetDocumentationGenerator.php
Labels: topic/documentation

#6687 bug: Fix priority between `modernize_types_casting` and `no_unneeded_control_parentheses`
  src/Fixer/CastNotation/ModernizeTypesCastingFixer.php
  src/Fixer/ControlStructure/NoUnneededControlParenthesesFixer.php
  tests/AutoReview/FixerFactoryTest.php
  tests/Fixtures/Integration/priority/modernize_types_casting,no_unneeded_control_parentheses.test
Labels: kind/bug, RTM

#6689 docs: Update installation recommended commands for `mkdir` argument (`-p` insteadof `--parents`).
  README.md
Labels: topic/documentation, RTM

#6590 bug: Align all the arrows inside the same array
  src/Fixer/Operator/BinaryOperatorSpacesFixer.php
  tests/Fixer/Operator/BinaryOperatorSpacesFixerTest.php
Labels: kind/bug
