Repository PHP-CS-Fixer/PHP-CS-Fixer, pull requests merged in 2022-05, with the labels that each got.

#6377 ModernizeStrposFixer - fix leading backslash with yoda
  src/Fixer/Alias/ModernizeStrposFixer.php
  tests/Fixer/Alias/ModernizeStrposFixerTest.php
Labels: kind/enhancement, RTM

#5960 Extract StatementIndentationFixer from BracesFixer
  doc/list.rst
  doc/rules/index.rst
  doc/rules/whitespace/statement_indentation.rst
  src/Console/Command/FixCommand.php
  src/Fixer/Basic/BracesFixer.php
  src/Fixer/ClassNotation/ClassAttributesSeparationFixer.php
  src/Fixer/FunctionNotation/MethodArgumentSpaceFixer.php
  src/Fixer/Indentation.php
  src/Fixer/Whitespace/ArrayIndentationFixer.php
  src/Fixer/Whitespace/HeredocIndentationFixer.php
  src/Fixer/Whitespace/StatementIndentationFixer.php
  src/Tokenizer/Analyzer/AlternativeSyntaxAnalyzer.php
  tests/AutoReview/FixerFactoryTest.php
  tests/AutoReview/ProjectCodeTest.php
  tests/Fixer/Basic/BracesFixerTest.php
  tests/Fixer/Basic/NonPrintableCharacterFixerTest.php
  tests/Fixer/PhpUnit/PhpUnitExpectationFixerTest.php
  tests/Fixer/Whitespace/StatementIndentationFixerTest.php
  tests/Fixtures/Integration/misc/PHP7_3.test
  tests/Fixtures/Integration/misc/braces,method_argument_space.test
  tests/Fixtures/Integration/priority/class_attributes_separation,statement_indentation.test
  tests/Fixtures/Integration/priority/statement_indentation,heredoc_indentation.test
  tests/Tokenizer/Analyzer/AlternativeSyntaxAnalyzerTest.php
Labels: kind/refactoring

#6406 DX: integrate PRLint
  .github/prlint.json
Labels: RTM
