Repository PHP-CS-Fixer/PHP-CS-Fixer, pull requests merged in 2023-04, with the labels that each got.

#6873 bug: ControlStructureBracesFixer - handle closing tag
  src/Fixer/ControlStructure/ControlStructureBracesFixer.php
  tests/Fixer/ControlStructure/ControlStructureBracesFixerTest.php
Labels: kind/bug

#6860 DX: make data providers static for fixer's tests
  tests/AbstractDoctrineAnnotationFixerTestCase.php
  tests/Fixer/Alias/NoAliasFunctionsFixerTest.php
  tests/Fixer/Basic/EncodingFixerTest.php
  tests/Fixer/CastNotation/LowercaseCastFixerTest.php
  tests/Fixer/CastNotation/ShortScalarCastFixerTest.php
  tests/Fixer/ClassNotation/ClassDefinitionFixerTest.php
  tests/Fixer/ClassNotation/FinalPublicMethodForAbstractClassFixerTest.php
  tests/Fixer/ClassNotation/ProtectedToPrivateFixerTest.php
  tests/Fixer/ControlStructure/ControlStructureContinuationPositionFixerTest.php
  tests/Fixer/ControlStructure/NoBreakCommentFixerTest.php
  tests/Fixer/ControlStructure/NoUselessElseFixerTest.php
  tests/Fixer/DoctrineAnnotation/DoctrineAnnotationArrayAssignmentFixerTest.php
  tests/Fixer/DoctrineAnnotation/DoctrineAnnotationBracesFixerTest.php
  tests/Fixer/DoctrineAnnotation/DoctrineAnnotationIndentationFixerTest.php
  tests/Fixer/DoctrineAnnotation/DoctrineAnnotationSpacesFixerTest.php
  tests/Fixer/FunctionNotation/NullableTypeDeclarationForDefaultNullValueFixerTest.php
  tests/Fixer/ListNotation/ListSyntaxFixerTest.php
  tests/Fixer/Operator/IncrementStyleFixerTest.php
  tests/Fixer/PhpUnit/PhpUnitConstructFixerTest.php
  tests/Fixer/PhpUnit/PhpUnitStrictFixerTest.php
  tests/Fixer/Whitespace/ArrayIndentationFixerTest.php
  tests/Fixer/Whitespace/IndentationTypeFixerTest.php
  tests/Fixer/Whitespace/LineEndingFixerTest.php
  tests/Test/AbstractFixerTestCase.php
Labels: kind/enhancement, RTM

#6898 bug: Fix FullyQualifiedStrictTypesFixer common prefix bug
  src/Fixer/Import/FullyQualifiedStrictTypesFixer.php
  tests/Fixer/Import/FullyQualifiedStrictTypesFixerTest.php
Labels: RTM

#6900 bug: PhpUnitMockShortWillReturnFixer - fix for trailing commas
  src/Fixer/PhpUnit/PhpUnitMockShortWillReturnFixer.php
  tests/Fixer/PhpUnit/PhpUnitMockShortWillReturnFixerTest.php
  tests/Fixtures/Integration/misc/php_unit_mock_short_will_return,trailing_comma_in_multiline.test
Labels: kind/bug

#6899 bug: NoBreakCommentFixer - fix for nested match
  src/Fixer/ControlStructure/NoBreakCommentFixer.php
  tests/Fixer/ControlStructure/NoBreakCommentFixerTest.php
Labels: kind/bug

#6796 feature: Parse parenthesized & conditional phpdoc type
  src/DocBlock/TypeExpression.php
  src/FixerConfiguration/AliasedFixerOptionBuilder.php
  src/FixerConfiguration/FixerOption.php
  src/FixerConfiguration/FixerOptionBuilder.php
  src/FixerConfiguration/FixerOptionInterface.php
  tests/DocBlock/TypeExpressionTest.php
  tests/Fixer/Phpdoc/PhpdocAlignFixerTest.php
  tests/FixerConfiguration/AliasedFixerOptionTest.php
Labels: kind/enhancement

#6863 bug: VoidReturnFixer - fix for intervening attributes
  src/Fixer/FunctionNotation/VoidReturnFixer.php
  tests/Fixer/FunctionNotation/VoidReturnFixerTest.php
Labels: kind/bug

#6907 DX: make data providers static with straight-forward changes
  tests/AutoReview/DocumentationTest.php
  tests/AutoReview/ProjectCodeTest.php
  tests/AutoReview/TransformerTest.php
  tests/Console/Command/SelfUpdateCommandTest.php
  tests/Console/ConfigurationResolverTest.php
  tests/Console/Output/ErrorOutputTest.php
  tests/Tokenizer/CTTest.php
  tests/Tokenizer/TokenTest.php
  tests/Tokenizer/TokensTest.php
Labels: kind/enhancement

#6840 minor: Use single Dockerfile with multiple build targets
  .editorconfig
  Dockerfile
  docker-compose.yaml
  docker/php-7.4/xdebug.ini
  docker/php-8.0/Dockerfile
  docker/php-8.0/xdebug.ini
  docker/php-8.1/Dockerfile
  docker/php-8.1/xdebug.ini
  docker/php-8.2/Dockerfile
  docker/xdebug.ini
Labels: RTM

#6908 DX: use force option for php_unit_data_provider_static in PHPUnit 10.0 migration set
  doc/ruleSets/PHPUnit100MigrationRisky.rst
  doc/rules/php_unit/php_unit_data_provider_static.rst
  src/RuleSet/Sets/PHPUnit100MigrationRiskySet.php
  tests/Console/Report/FixReport/AbstractReporterTestCase.php
  tests/Console/Report/FixReport/CheckstyleReporterTest.php
  tests/Console/Report/FixReport/GitlabReporterTest.php
  tests/Console/Report/FixReport/JsonReporterTest.php
  tests/Console/Report/FixReport/JunitReporterTest.php
  tests/Console/Report/FixReport/TextReporterTest.php
  tests/Console/Report/FixReport/XmlReporterTest.php
  tests/Console/Report/ListSetsReport/AbstractReporterTestCase.php
  tests/Console/Report/ListSetsReport/JsonReporterTest.php
  tests/Console/Report/ListSetsReport/TextReporterTest.php
  tests/Fixer/Basic/PsrAutoloadingFixerTest.php
Labels: kind/enhancement

#6913 bug: StatementIndentationFixer - fix for multiline arguments starting with "new" keyword
  src/Tokenizer/Transformer/BraceClassInstantiationTransformer.php
  tests/Fixer/Whitespace/StatementIndentationFixerTest.php
  tests/Tokenizer/Transformer/BraceClassInstantiationTransformerTest.php
Labels: kind/bug

#6914 bug: StatementIndentationFixer - fix for multiline arguments starting with "new" keyword preceded by class instantiation
  src/Tokenizer/Transformer/BraceClassInstantiationTransformer.php
  tests/Fixer/Whitespace/StatementIndentationFixerTest.php
  tests/Tokenizer/Transformer/BraceClassInstantiationTransformerTest.php
Labels: kind/bug

#6921 minor: PhpdocAlignFixer - support cases with type and variable separated with no space
  src/Fixer/Phpdoc/PhpdocAlignFixer.php
  tests/Fixer/Phpdoc/PhpdocAlignFixerTest.php
Labels: kind/enhancement

#6922 bug: PhpdocTypesFixer - handle types with no space between type and variable
  src/DocBlock/Annotation.php
  src/Fixer/Phpdoc/PhpdocAnnotationWithoutDotFixer.php
  src/Fixer/Phpdoc/PhpdocTypesFixer.php
  src/Fixer/Phpdoc/PhpdocTypesOrderFixer.php
  tests/AutoReview/FixerFactoryTest.php
  tests/DocBlock/AnnotationTest.php
  tests/Fixer/Phpdoc/PhpdocTypesFixerTest.php
  tests/Fixer/Phpdoc/PhpdocTypesOrderFixerTest.php
  tests/Fixtures/Integration/priority/phpdoc_annotation_without_dot,phpdoc_types.test
  tests/Fixtures/Integration/priority/phpdoc_annotation_without_dot,phpdoc_types_order.test
Labels: kind/bug

#6917 DX: fix GitHub Actions errors and warnings
  .github/workflows/ci.yml
  .github/workflows/sca.yml
  .github/workflows/yaml.yml
  dev-tools/build.sh
Labels: kind/enhancement

#6924 feature: PhpUnitInternalClassFixer - add empty line before PHPDoc
  doc/rules/php_unit/php_unit_internal_class.rst
  doc/rules/php_unit/php_unit_size_class.rst
  src/Fixer/AbstractPhpUnitFixer.php
  src/Fixer/PhpUnit/PhpUnitInternalClassFixer.php
  src/Fixer/PhpUnit/PhpUnitSizeClassFixer.php
  src/Fixer/PhpUnit/PhpUnitTestClassRequiresCoversFixer.php
  tests/Fixer/PhpUnit/PhpUnitInternalClassFixerTest.php
  tests/Fixtures/Integration/priority/php_unit_internal_class,final_internal_class.test
Labels: kind/feature

#6920 bug: NoExtraBlankLinesFixer - fix for attribute in abstract function
  src/Fixer/Whitespace/NoExtraBlankLinesFixer.php
  tests/Fixer/Whitespace/NoExtraBlankLinesFixerTest.php
Labels: kind/bug

#6919 docs: improve code samples for MultilineWhitespaceBeforeSemicolonsFixer
  doc/rules/semicolon/multiline_whitespace_before_semicolons.rst
  src/Fixer/Semicolon/MultilineWhitespaceBeforeSemicolonsFixer.php
Labels: kind/enhancement

#6916 DX: add cache related tests
  tests/Console/ConfigurationResolverTest.php
  tests/Smoke/PharTest.php
Labels: kind/enhancement

#6918 bug: StatementIndentationFixer - fix comments at the end of if/elseif/else blocks
  src/Fixer/Whitespace/StatementIndentationFixer.php
  tests/Fixer/Basic/BracesFixerTest.php
  tests/Fixer/Whitespace/StatementIndentationFixerTest.php
Labels: kind/bug

#6925 DX: refactor PhpdocAlignFixerTest
  tests/Fixer/Phpdoc/PhpdocAlignFixerTest.php
Labels: kind/enhancement
