Repository PHP-CS-Fixer/PHP-CS-Fixer, pull requests merged in 2023-07, with the labels that each got.

#7023 bug: ordered imports fixer top group only
  src/Fixer/Import/OrderedImportsFixer.php
  tests/Fixer/Import/OrderedImportsFixerTest.php
Labels: kind/bug

#7109 feature: Create cache path if it does not exist
  src/Cache/FileHandler.php
  tests/Cache/FileHandlerTest.php
Labels: kind/feature, topic/I/O

#7113 DX: exclude Dockerfile from dist
  .gitattributes
Labels: kind/enhancement

#7122 feature: `BlankLineBetweenImportGroupsFixer` - keep indent
  src/Fixer/Whitespace/BlankLineBetweenImportGroupsFixer.php
  tests/Fixer/Whitespace/BlankLineBetweenImportGroupsFixerTest.php
Labels: kind/feature

#7123 bug: `FinalPublicMethodForAbstractClassFixer` - fix for readonly classes
  src/Fixer/ClassNotation/FinalPublicMethodForAbstractClassFixer.php
  tests/Fixer/ClassNotation/FinalPublicMethodForAbstractClassFixerTest.php
Labels: kind/bug

#7126 DX: do not allow linebreak at the beginning of code sample
  doc/rules/operator/no_space_around_double_colon.rst
  src/Fixer/Operator/NoSpaceAroundDoubleColonFixer.php
  tests/Test/AbstractFixerTestCase.php
Labels: kind/enhancement

#6883 DX: Use ParaUnit to speed up tests
  .github/workflows/ci.yml
  composer.json
Labels: topic/tests

#7135 DX: fix PHPDoc types issues
  src/Console/Command/DescribeCommand.php
  src/Console/Command/DocumentationCommand.php
  src/Console/Command/FixCommand.php
  src/Console/Command/HelpCommand.php
  src/Console/Command/ListFilesCommand.php
  src/Console/Command/ListSetsCommand.php
  src/Console/Command/SelfUpdateCommand.php
  src/Console/Report/FixReport/JunitReporter.php
  tests/Fixer/FunctionNotation/MethodArgumentSpaceFixerTest.php
Labels: kind/enhancement

#7136 DX: fix function calls
  src/StdinFileInfo.php
  tests/AutoReview/DocumentationTest.php
  tests/AutoReview/TransformerTest.php
  tests/Console/Command/SelfUpdateCommandTest.php
  tests/Fixer/FunctionNotation/VoidReturnFixerTest.php
  tests/Fixer/PhpUnit/PhpUnitNamespacedFixerTest.php
  tests/Fixer/PhpUnit/PhpUnitStrictFixerTest.php
  tests/Tokenizer/CTTest.php
Labels: kind/enhancement

#7138 DX: remove `empty` calls
  src/Console/Output/ErrorOutput.php
  src/Error/ErrorsManager.php
  src/Fixer/AbstractPhpUnitFixer.php
  src/Fixer/ClassNotation/NoPhp4ConstructorFixer.php
  src/Fixer/Import/OrderedImportsFixer.php
  src/Fixer/PhpUnit/PhpUnitConstructFixer.php
  src/Fixer/PhpUnit/PhpUnitNamespacedFixer.php
  src/Fixer/Phpdoc/PhpdocAlignFixer.php
  src/Runner/Runner.php
  src/Tokenizer/Token.php
Labels: kind/enhancement

#7139 DX: improve `Tokens` checking for found tokens
  src/Tokenizer/Tokens.php
  tests/Tokenizer/TokensTest.php
Labels: kind/enhancement

#7144 DX: use strict assertions
  tests/Test/AbstractFixerTestCase.php
  tests/Test/Assert/AssertTokensTrait.php
  tests/Tokenizer/TokensTest.php
Labels: kind/enhancement

#7145 DX: make `array_search` call strict
  tests/Test/AbstractFixerTestCase.php
Labels: kind/enhancement

#7143 DX: add phpstan/phpstan-strict-rules
  dev-tools/composer.json
  dev-tools/composer.lock
  dev-tools/phpstan/baseline.php
  phpstan.dist.neon
Labels: kind/enhancement

#7147 DX: Use relative fixture path as integration test case's name
  tests/Test/AbstractIntegrationTestCase.php
Labels: topic/tests

#7148 DX: Copy-pasteable `class::getPriority` for phpDoc diffs
  tests/AutoReview/FixerFactoryTest.php
Labels: topic/tests

#7146 DX: unify `Preg::match()` in logical conditions
  dev-tools/phpstan/baseline.php
  src/AbstractPhpdocToTypeDeclarationFixer.php
  src/Differ/UnifiedDiffer.php
  src/DocBlock/Annotation.php
  src/DocBlock/Line.php
  src/DocBlock/TypeExpression.php
  src/Fixer/ArrayNotation/WhitespaceAfterCommaInArrayFixer.php
  src/Fixer/Basic/CurlyBracesPositionFixer.php
  src/Fixer/Basic/NoMultipleStatementsPerLineFixer.php
  src/Fixer/Basic/OctalNotationFixer.php
  src/Fixer/Basic/PsrAutoloadingFixer.php
  src/Fixer/Casing/IntegerLiteralCaseFixer.php
  src/Fixer/ClassNotation/FinalInternalClassFixer.php
  src/Fixer/ClassNotation/SingleTraitInsertPerStatementFixer.php
  src/Fixer/Comment/CommentToPhpdocFixer.php
  src/Fixer/Comment/NoEmptyCommentFixer.php
  src/Fixer/Comment/SingleLineCommentSpacingFixer.php
  src/Fixer/Comment/SingleLineCommentStyleFixer.php
  src/Fixer/ControlStructure/NoBreakCommentFixer.php
  src/Fixer/ControlStructure/SwitchContinueToBreakFixer.php
  src/Fixer/FunctionNotation/SingleLineThrowFixer.php
  src/Fixer/Indentation.php
  src/Fixer/LanguageConstruct/NullableTypeDeclarationFixer.php
  src/Fixer/NamespaceNotation/BlankLineAfterNamespaceFixer.php
  src/Fixer/Operator/BinaryOperatorSpacesFixer.php
  src/Fixer/Operator/NoUselessConcatOperatorFixer.php
  src/Fixer/Operator/OperatorLinebreakFixer.php
  src/Fixer/PhpUnit/PhpUnitNamespacedFixer.php
  src/Fixer/PhpUnit/PhpUnitNoExpectationAnnotationFixer.php
  src/Fixer/PhpUnit/PhpUnitTestAnnotationFixer.php
  src/Fixer/Phpdoc/AlignMultilineCommentFixer.php
  src/Fixer/Phpdoc/GeneralPhpdocTagRenameFixer.php
  src/Fixer/Phpdoc/NoSuperfluousPhpdocTagsFixer.php
  src/Fixer/Phpdoc/PhpdocAddMissingParamAnnotationFixer.php
  src/Fixer/Phpdoc/PhpdocAnnotationWithoutDotFixer.php
  src/Fixer/Phpdoc/PhpdocOrderByValueFixer.php
  src/Fixer/Phpdoc/PhpdocParamOrderFixer.php
  src/Fixer/Phpdoc/PhpdocSeparationFixer.php
  src/Fixer/Whitespace/MethodChainingIndentationFixer.php
  src/Fixer/Whitespace/NoExtraBlankLinesFixer.php
  src/Fixer/Whitespace/NoTrailingWhitespaceFixer.php
  src/Fixer/Whitespace/StatementIndentationFixer.php
  src/Fixer/Whitespace/TypesSpacesFixer.php
  src/FixerNameValidator.php
  src/Indicator/PhpUnitTestCaseIndicator.php
  src/Preg.php
  src/RuleSet/AbstractMigrationSetDescription.php
  src/Tokenizer/Tokens.php
  tests/AutoReview/CiConfigurationTest.php
  tests/AutoReview/ProjectCodeTest.php
  tests/PregTest.php
  tests/Test/AbstractFixerTestCase.php
Labels: kind/enhancement

#7149 DX: use booleans in conditions
  dev-tools/phpstan/baseline.php
  src/Console/Report/FixReport/ReporterFactory.php
  src/Console/Report/ListSetsReport/ReporterFactory.php
  src/Documentation/FixerDocumentGenerator.php
  src/FileReader.php
  src/Fixer/ClassNotation/ClassDefinitionFixer.php
  src/Fixer/ClassNotation/FinalInternalClassFixer.php
  src/Fixer/Comment/HeaderCommentFixer.php
  src/Fixer/ControlStructure/ControlStructureBracesFixer.php
  src/Fixer/ControlStructure/IncludeFixer.php
  src/Fixer/ControlStructure/YodaStyleFixer.php
  src/Fixer/Phpdoc/PhpdocAddMissingParamAnnotationFixer.php
  src/Fixer/Phpdoc/PhpdocAlignFixer.php
  src/Fixer/Phpdoc/PhpdocParamOrderFixer.php
  src/FixerFactory.php
  src/Runner/Runner.php
  src/Tokenizer/Analyzer/ArgumentsAnalyzer.php
  src/Tokenizer/Transformers.php
  tests/AutoReview/ProjectCodeTest.php
  tests/DocBlock/TypeExpressionTest.php
  tests/Fixer/Basic/EncodingFixerTest.php
Labels: kind/enhancement

#7153 DX: add proper test for `SelfAccessorFixer` must run before `SelfAccessorFixer`
  src/Fixer/Basic/PsrAutoloadingFixer.php
  src/Fixer/ClassNotation/SelfAccessorFixer.php
  tests/AutoReview/FixerFactoryTest.php
  tests/Fixtures/Integration/misc/PHP7_3.test
  tests/Fixtures/Integration/misc/phpdocs-invalid.test
  tests/Fixtures/Integration/priority/psr_autoloading,self_accessor.test
  tests/Fixtures/Integration/set/@Symfony-risky.test-out.php
  tests/IntegrationTest.php
Labels: kind/enhancement

#7114 feature: Introduce `YieldFromArrayToYieldsFixer`
  doc/list.rst
  doc/rules/array_notation/yield_from_array_to_yields.rst
  doc/rules/index.rst
  src/Fixer/ArrayNotation/YieldFromArrayToYieldsFixer.php
  src/Fixer/Basic/NoMultipleStatementsPerLineFixer.php
  src/Fixer/Whitespace/BlankLineBeforeStatementFixer.php
  src/Fixer/Whitespace/NoExtraBlankLinesFixer.php
  src/Fixer/Whitespace/NoWhitespaceInBlankLineFixer.php
  src/Fixer/Whitespace/StatementIndentationFixer.php
  tests/AutoReview/FixerFactoryTest.php
  tests/Fixer/ArrayNotation/YieldFromArrayToYieldsFixerTest.php
  tests/Fixtures/Integration/priority/yield_from_array_to_yields,blank_line_before_statement.test
  tests/Fixtures/Integration/priority/yield_from_array_to_yields,no_extra_blank_lines.test
  tests/Fixtures/Integration/priority/yield_from_array_to_yields,no_multiple_statements_per_line.test
  tests/Fixtures/Integration/priority/yield_from_array_to_yields,no_whitespace_in_blank_line.test
  tests/Fixtures/Integration/priority/yield_from_array_to_yields,statement_indentation.test
Labels: kind/feature

#7115 DX: add `YieldFromArrayToYieldsFixer` to `PhpCsFixer` set
  doc/list.rst
  doc/ruleSets/PhpCsFixer.rst
  doc/rules/array_notation/yield_from_array_to_yields.rst
  src/RuleSet/Sets/PhpCsFixerSet.php
  tests/Fixer/Alias/NoMixedEchoPrintFixerTest.php
  tests/Fixer/Alias/PowToExponentiationFixerTest.php
  tests/Fixer/CastNotation/ModernizeTypesCastingFixerTest.php
  tests/Fixer/ClassNotation/ClassDefinitionFixerTest.php
  tests/Fixer/ClassNotation/SingleClassElementPerStatementFixerTest.php
  tests/Fixer/ControlStructure/NoUnneededCurlyBracesFixerTest.php
  tests/Fixer/ControlStructure/NoUselessElseFixerTest.php
  tests/Fixer/ControlStructure/SwitchCaseSemicolonToColonFixerTest.php
  tests/Fixer/ControlStructure/SwitchCaseSpaceFixerTest.php
  tests/Fixer/ControlStructure/SwitchContinueToBreakFixerTest.php
  tests/Fixer/ControlStructure/YodaStyleFixerTest.php
  tests/Fixer/FunctionNotation/LambdaNotUsedImportFixerTest.php
  tests/Fixer/FunctionNotation/NativeFunctionInvocationFixerTest.php
  tests/Fixer/FunctionNotation/NoSpacesAfterFunctionNameFixerTest.php
  tests/Fixer/FunctionNotation/PhpdocToReturnTypeFixerTest.php
  tests/Fixer/LanguageConstruct/CombineConsecutiveUnsetsFixerTest.php
  tests/Fixer/LanguageConstruct/ErrorSuppressionFixerTest.php
  tests/Fixer/LanguageConstruct/NoUnsetOnPropertyFixerTest.php
  tests/Fixer/Operator/NewWithBracesFixerTest.php
  tests/Fixer/Operator/StandardizeIncrementFixerTest.php
  tests/Fixer/Operator/TernaryToNullCoalescingFixerTest.php
  tests/Fixer/PhpUnit/PhpUnitDedicateAssertFixerTest.php
  tests/Fixer/Semicolon/NoEmptyStatementFixerTest.php
  tests/Fixer/Semicolon/SemicolonAfterInstructionFixerTest.php
  tests/Fixer/Whitespace/NoExtraBlankLinesFixerTest.php
  tests/Fixer/Whitespace/NoSpacesAroundOffsetFixerTest.php
  tests/Fixer/Whitespace/NoTrailingWhitespaceFixerTest.php
  tests/Fixer/Whitespace/TypeDeclarationSpacesFixerTest.php
  tests/PregTest.php
  tests/Tokenizer/Analyzer/ClassyAnalyzerTest.php
  tests/Tokenizer/Analyzer/FunctionsAnalyzerTest.php
  tests/Tokenizer/Analyzer/GotoLabelAnalyzerTest.php
  tests/Tokenizer/TokenTest.php
  tests/Tokenizer/TokensAnalyzerTest.php
  tests/Tokenizer/Transformer/TypeAlternationTransformerTest.php
  tests/UtilsTest.php
Labels: kind/enhancement

#7167 DX: fix contravariant types in PHPDocs
  dev-tools/phpstan/baseline.php
  src/Fixer/ConfigurableFixerInterface.php
  src/Fixer/ListNotation/ListSyntaxFixer.php
Labels: kind/enhancement

#7169 bug: YieldFromArrayToYieldsFixer - fix for `yield from` after `}`
  src/Fixer/ArrayNotation/YieldFromArrayToYieldsFixer.php
  tests/Fixer/ArrayNotation/YieldFromArrayToYieldsFixerTest.php
  tests/Fixer/ClassNotation/ClassAttributesSeparationFixerTest.php
  tests/Fixer/ControlStructure/YodaStyleFixerTest.php
Labels: kind/bug

#7170 DX: remove unnecessary arrays from data providers
  tests/Console/SelfUpdate/NewVersionCheckerTest.php
  tests/Fixer/CastNotation/ShortScalarCastFixerTest.php
  tests/Fixer/ClassNotation/ClassAttributesSeparationFixerTest.php
  tests/Fixer/ClassNotation/ClassDefinitionFixerTest.php
  tests/Fixer/ClassNotation/NoBlankLinesAfterClassOpeningFixerTest.php
  tests/Fixer/Comment/NoEmptyCommentFixerTest.php
  tests/Fixer/ControlStructure/NoBreakCommentFixerTest.php
  tests/Fixer/ControlStructure/NoUselessElseFixerTest.php
  tests/Fixer/DoctrineAnnotation/DoctrineAnnotationIndentationFixerTest.php
  tests/Fixer/DoctrineAnnotation/DoctrineAnnotationSpacesFixerTest.php
  tests/Fixer/Operator/IncrementStyleFixerTest.php
  tests/Fixer/PhpTag/EchoTagSyntaxFixerTest.php
  tests/Fixer/PhpUnit/PhpUnitStrictFixerTest.php
  tests/Fixer/Phpdoc/NoBlankLinesAfterPhpdocFixerTest.php
  tests/Fixer/Phpdoc/PhpdocIndentFixerTest.php
  tests/Fixer/Phpdoc/PhpdocInlineTagNormalizerFixerTest.php
  tests/Fixer/Whitespace/IndentationTypeFixerTest.php
  tests/Fixer/Whitespace/LineEndingFixerTest.php
Labels: kind/enhancement

#7168 feature: Introduce `ReturnToYieldFromFixer`
  doc/list.rst
  doc/rules/array_notation/return_to_yield_from.rst
  doc/rules/index.rst
  src/Fixer/ArrayNotation/ReturnToYieldFromFixer.php
  src/Fixer/ArrayNotation/YieldFromArrayToYieldsFixer.php
  src/Fixer/FunctionNotation/PhpdocToReturnTypeFixer.php
  src/Fixer/NamespaceNotation/CleanNamespaceFixer.php
  src/Fixer/PhpUnit/PhpUnitDataProviderReturnTypeFixer.php
  tests/AutoReview/FixerFactoryTest.php
  tests/Fixer/ArrayNotation/ReturnToYieldFromFixerTest.php
  tests/Fixtures/Integration/priority/php_unit_data_provider_return_type,return_to_yield_from.test
  tests/Fixtures/Integration/priority/phpdoc_to_return_type,return_to_yield_from.test
  tests/Fixtures/Integration/priority/return_to_yield_from,yield_from_array_to_yields.test
Labels: kind/feature
