Repository PHP-CS-Fixer/PHP-CS-Fixer, pull requests merged in 2023-01, with the labels that each got.

#6722 feature: make OrderedInterfacesFixer non-risky
  doc/list.rst
  doc/rules/class_notation/ordered_interfaces.rst
  doc/rules/index.rst
  src/Fixer/ClassNotation/OrderedInterfacesFixer.php
Labels: kind/enhancement, RTM

#6734 bug: Fix type error when using paths intersection mode
  src/Console/Command/FixCommand.php
  tests/Console/Command/FixCommandTest.php
Labels: kind/bug

#6738 minor: improve rule sets order
  doc/list.rst
  doc/ruleSets/index.rst
  doc/rules/basic/braces.rst
  doc/rules/basic/encoding.rst
  doc/rules/casing/constant_case.rst
  doc/rules/casing/lowercase_keywords.rst
  doc/rules/class_notation/class_definition.rst
  doc/rules/class_notation/single_class_element_per_statement.rst
  doc/rules/class_notation/visibility_required.rst
  doc/rules/comment/no_trailing_whitespace_in_comment.rst
  doc/rules/control_structure/elseif.rst
  doc/rules/control_structure/no_break_comment.rst
  doc/rules/control_structure/switch_case_semicolon_to_colon.rst
  doc/rules/control_structure/switch_case_space.rst
  doc/rules/function_notation/function_declaration.rst
  doc/rules/function_notation/method_argument_space.rst
  doc/rules/function_notation/no_spaces_after_function_name.rst
  doc/rules/import/single_import_per_statement.rst
  doc/rules/import/single_line_after_imports.rst
  doc/rules/namespace_notation/blank_line_after_namespace.rst
  doc/rules/operator/no_space_around_double_colon.rst
  doc/rules/php_tag/full_opening_tag.rst
  doc/rules/php_tag/no_closing_tag.rst
  doc/rules/whitespace/indentation_type.rst
  doc/rules/whitespace/line_ending.rst
  doc/rules/whitespace/no_spaces_inside_parenthesis.rst
  doc/rules/whitespace/no_trailing_whitespace.rst
  doc/rules/whitespace/single_blank_line_at_eof.rst
  src/RuleSet/RuleSets.php
  tests/RuleSet/RuleSetsTest.php
Labels: kind/enhancement

#6702 feature: add PhpUnitDataProviderStaticFixer
  .php-cs-fixer.dist.php
  doc/list.rst
  doc/ruleSets/PHPUnit100MigrationRisky.rst
  doc/ruleSets/index.rst
  doc/rules/index.rst
  doc/rules/php_unit/php_unit_data_provider_static.rst
  doc/rules/php_unit/php_unit_dedicate_assert.rst
  doc/rules/php_unit/php_unit_dedicate_assert_internal_type.rst
  doc/rules/php_unit/php_unit_expectation.rst
  doc/rules/php_unit/php_unit_mock.rst
  doc/rules/php_unit/php_unit_namespaced.rst
  doc/rules/php_unit/php_unit_no_expectation_annotation.rst
  src/Fixer/PhpUnit/PhpUnitDataProviderStaticFixer.php
  src/RuleSet/AbstractMigrationSetDescription.php
  src/RuleSet/Sets/PHPUnit100MigrationRiskySet.php
  src/Tokenizer/Analyzer/DataProviderAnalyzer.php
  tests/Fixer/PhpUnit/PhpUnitDataProviderStaticFixerTest.php
  tests/Fixtures/Integration/misc/php_unit_data_provider_static,visibility_required.test
  tests/RuleSet/RuleSetsTest.php
  tests/RuleSet/Sets/AbstractSetTest.php
  tests/RuleSet/Sets/PHPUnit100MigrationRiskySetTest.php
  tests/Tokenizer/Analyzer/DataProviderAnalyzerTest.php
Labels: kind/feature

#6746 bug: Fix PHPDoc alignment fixer containing callbacks using `\Closure`
  src/DocBlock/TypeExpression.php
  tests/Console/Output/ProcessOutputTest.php
  tests/DocBlock/TypeExpressionTest.php
  tests/Fixer/Phpdoc/PhpdocAlignFixerTest.php
Labels: kind/bug, RTM

#6763 feature: Add php 7.4 types to Cookbook docs
  doc/cookbook_fixers.rst
Labels: RTM

#6762 feature: OctalNotationFixer - support _ notation
  src/Fixer/Basic/OctalNotationFixer.php
  tests/Fixer/Basic/OctalNotationFixerTest.php
Labels: kind/feature

#6542 bug: Fix indentation for comment at end of function followed by a comma
  src/Fixer/Whitespace/StatementIndentationFixer.php
  tests/Fixer/Basic/BracesFixerTest.php
  tests/Fixer/Whitespace/StatementIndentationFixerTest.php
Labels: kind/bug

#6668 bug: PhpdocSeparationFixer - Make groups handling more flexible
  doc/list.rst
  doc/rules/phpdoc/phpdoc_separation.rst
  src/DocBlock/TagComparator.php
  src/Fixer/Phpdoc/PhpdocSeparationFixer.php
  tests/AutoReview/ProjectCodeTest.php
  tests/DocBlock/TagComparatorTest.php
  tests/Fixer/Phpdoc/PhpdocSeparationFixerTest.php
Labels: kind/bug, kind/enhancement
