Repository PHP-CS-Fixer/PHP-CS-Fixer, pull requests merged in 2023-06, with the labels that each got.

#7013 minor: PHP8.3 - Fix TokensAnalyzer::isAnonymousClass support for `readonly`
  src/Tokenizer/TokensAnalyzer.php
  tests/Tokenizer/TokensAnalyzerTest.php
Labels: kind/feature, topic/PHP8.3

#5085 DX: Use `actions/stale` to handle stale issues and pull requests
  .github/workflows/issues_and_pull_requests.yml
Labels: topic/ci

#7000 bug: Fix `TypeExpression::allowsNull()` with nullable
  src/DocBlock/TypeExpression.php
  tests/DocBlock/TypeExpressionTest.php
  tests/Fixer/FunctionNotation/PhpdocToParamTypeFixerTest.php
  tests/Fixer/FunctionNotation/PhpdocToPropertyTypeFixerTest.php
  tests/Fixer/FunctionNotation/PhpdocToReturnTypeFixerTest.php
Labels: kind/bug, topic/types

#7045 bug: Fix chained calls semicolon indent in switch case
  src/Fixer/Semicolon/MultilineWhitespaceBeforeSemicolonsFixer.php
  tests/Fixer/Semicolon/MultilineWhitespaceBeforeSemicolonsFixerTest.php
Labels: kind/bug

#7029 minor: `SingleSpaceAroundConstructFixer` - support space before `as`
  doc/list.rst
  doc/rules/language_construct/single_space_around_construct.rst
  src/Fixer/LanguageConstruct/SingleSpaceAroundConstructFixer.php
  tests/Fixer/LanguageConstruct/SingleSpaceAroundConstructFixerTest.php
Labels: kind/feature

#7053 minor: Unify "blank lines before namespace" fixers
  doc/list.rst
  doc/ruleSets/PSR12.rst
  doc/rules/index.rst
  doc/rules/namespace_notation/blank_lines_before_namespace.rst
  doc/rules/namespace_notation/no_blank_lines_before_namespace.rst
  doc/rules/namespace_notation/single_blank_line_before_namespace.rst
  src/AbstractLinesBeforeNamespaceFixer.php
  src/Fixer/NamespaceNotation/BlankLinesBeforeNamespaceFixer.php
  src/Fixer/NamespaceNotation/CleanNamespaceFixer.php
  src/Fixer/NamespaceNotation/NoBlankLinesBeforeNamespaceFixer.php
  src/Fixer/NamespaceNotation/SingleBlankLineBeforeNamespaceFixer.php
  src/Fixer/PhpTag/BlankLineAfterOpeningTagFixer.php
  src/RuleSet/Sets/PSR12Set.php
  tests/AutoReview/FixerFactoryTest.php
  tests/Fixer/NamespaceNotation/BlankLinesBeforeNamespaceFixerTest.php
  tests/Fixer/NamespaceNotation/NoBlankLinesBeforeNamespaceFixerTest.php
  tests/Fixer/NamespaceNotation/SingleBlankLineBeforeNamespaceFixerTest.php
  tests/Fixtures/Integration/priority/blank_line_after_opening_tag,blank_lines_before_namespace.test
Labels: kind/refactoring, topic/whitespace

#7057 feature: Introduce `PhpUnitDataProviderNameFixer`
  doc/list.rst
  doc/rules/index.rst
  doc/rules/php_unit/php_unit_data_provider_name.rst
  src/Fixer/PhpUnit/PhpUnitDataProviderNameFixer.php
  src/Fixer/PhpUnit/PhpUnitDataProviderStaticFixer.php
  src/Tokenizer/Analyzer/Analysis/DataProviderAnalysis.php
  src/Tokenizer/Analyzer/DataProviderAnalyzer.php
  tests/Fixer/PhpUnit/PhpUnitDataProviderNameFixerTest.php
  tests/Tokenizer/Analyzer/Analysis/DataProviderAnalysisTest.php
  tests/Tokenizer/Analyzer/DataProviderAnalyzerTest.php
Labels: kind/feature

#7069 DX: add `php_unit_data_provider_name` to `@PhpCsFixer:risky` set
  doc/list.rst
  doc/ruleSets/PhpCsFixerRisky.rst
  doc/rules/php_unit/php_unit_data_provider_name.rst
  src/RuleSet/Sets/PhpCsFixerRiskySet.php
  tests/Tokenizer/Analyzer/CommentsAnalyzerTest.php
Labels: kind/enhancement

#7070 DX: rename tests and data providers
  tests/AutoReview/FixerFactoryTest.php
  tests/Fixer/Alias/NoMixedEchoPrintFixerTest.php
  tests/Fixer/Casing/ConstantCaseFixerTest.php
  tests/Fixer/ClassNotation/FinalInternalClassFixerTest.php
  tests/Fixer/ClassNotation/OrderedTypesFixerTest.php
  tests/Fixer/ClassNotation/VisibilityRequiredFixerTest.php
  tests/Fixer/Comment/SingleLineCommentStyleFixerTest.php
  tests/Fixer/ControlStructure/NoUselessElseFixerTest.php
  tests/Fixer/ControlStructure/YodaStyleFixerTest.php
  tests/Fixer/FunctionNotation/NullableTypeDeclarationForDefaultNullValueFixerTest.php
  tests/Fixer/LanguageConstruct/GetClassToClassKeywordFixerTest.php
  tests/Fixer/Whitespace/BlankLineBeforeStatementFixerTest.php
  tests/Fixer/Whitespace/NoExtraBlankLinesFixerTest.php
  tests/Fixer/Whitespace/NoSpacesAroundOffsetFixerTest.php
  tests/WhitespacesFixerConfigTest.php
Labels: kind/enhancement

#7080 bug: SelfAccessorFixer - fix for union types
  src/Fixer/ClassNotation/SelfAccessorFixer.php
  tests/Fixer/ClassNotation/SelfAccessorFixerTest.php
Labels: kind/bug

#7085 bug: CurlyBracesPositionFixer must run before StatementIndentationFixer
  doc/list.rst
  doc/rules/basic/braces.rst
  src/Fixer/Basic/CurlyBracesPositionFixer.php
  src/Fixer/Whitespace/StatementIndentationFixer.php
  tests/AutoReview/FixerFactoryTest.php
  tests/Fixtures/Integration/priority/curly_braces_position,statement_indentation.test
Labels: kind/bug

#7087 bug: NoMultipleStatementsPerLineFixer must run before CurlyBracesPositionFixer
  doc/list.rst
  doc/rules/basic/braces.rst
  src/Fixer/Basic/CurlyBracesPositionFixer.php
  src/Fixer/Basic/NoMultipleStatementsPerLineFixer.php
  src/Fixer/Basic/SingleLineEmptyBodyFixer.php
  tests/AutoReview/FixerFactoryTest.php
  tests/Fixtures/Integration/priority/no_multiple_statements_per_line,curly_braces_position.test
Labels: kind/bug

#7090 bug: PhpdocAddMissingParamAnnotationFixer - fix for promoted properties
  src/Fixer/Phpdoc/PhpdocAddMissingParamAnnotationFixer.php
  tests/Fixer/Phpdoc/PhpdocAddMissingParamAnnotationFixerTest.php
Labels: kind/bug

#7088 DX: fix priority of `SingleBlankLineBeforeNamespaceFixer`
  src/Fixer/NamespaceNotation/SingleBlankLineBeforeNamespaceFixer.php
  tests/AutoReview/FixerFactoryTest.php
Labels: kind/enhancement

#7092 DX: use FAST_LINT_TEST_CASES=1 for CI run on macOS
  .github/workflows/ci.yml
Labels: kind/enhancement

#5819 feature: `NullableTypeDeclarationForDefaultNullValue` - support for nullability in union types
  doc/list.rst
  doc/rules/function_notation/nullable_type_declaration_for_default_null_value.rst
  doc/rules/index.rst
  src/Fixer/ClassNotation/OrderedTypesFixer.php
  src/Fixer/FunctionNotation/NullableTypeDeclarationForDefaultNullValueFixer.php
  src/Tokenizer/Analyzer/Analysis/TypeAnalysis.php
  tests/AutoReview/FixerFactoryTest.php
  tests/Fixer/FunctionNotation/NullableTypeDeclarationForDefaultNullValueFixerTest.php
  tests/Fixtures/Integration/priority/nullable_type_declaration_for_default_null_value,ordered_types.test
  tests/Tokenizer/Analyzer/Analysis/TypeAnalysisTest.php
Labels: topic/types, status/rebase required

#7091 DX: fix priority of `FinalClassFixer`
  src/Fixer/ClassNotation/FinalClassFixer.php
  src/Fixer/ClassNotation/ProtectedToPrivateFixer.php
  src/Fixer/ClassNotation/SelfStaticAccessorFixer.php
  tests/AutoReview/FixerFactoryTest.php
  tests/Fixtures/Integration/priority/final_class,protected_to_private.test
  tests/Fixtures/Integration/priority/final_class,self_static_accessor.test
Labels: kind/enhancement

#7096 feature: SingleLineEmptyBodyFixer - support interfaces, traits and enums
  doc/list.rst
  doc/rules/basic/single_line_empty_body.rst
  doc/rules/index.rst
  src/Fixer/Basic/SingleLineEmptyBodyFixer.php
  tests/Fixer/Basic/SingleLineEmptyBodyFixerTest.php
Labels: kind/enhancement

#7100 DX: Rename abstract test classes to `*TestCase` convention
  tests/RuleSet/Sets/AbstractSetTestCase.php
  tests/RuleSet/Sets/DoctrineAnnotationSetTest.php
  tests/RuleSet/Sets/PERCS1x0RiskySetTest.php
  tests/RuleSet/Sets/PERCS1x0SetTest.php
  tests/RuleSet/Sets/PERRiskySetTest.php
  tests/RuleSet/Sets/PERSetTest.php
  tests/RuleSet/Sets/PHP54MigrationSetTest.php
  tests/RuleSet/Sets/PHP56MigrationRiskySetTest.php
  tests/RuleSet/Sets/PHP70MigrationRiskySetTest.php
  tests/RuleSet/Sets/PHP70MigrationSetTest.php
  tests/RuleSet/Sets/PHP71MigrationRiskySetTest.php
  tests/RuleSet/Sets/PHP71MigrationSetTest.php
  tests/RuleSet/Sets/PHP73MigrationSetTest.php
  tests/RuleSet/Sets/PHP74MigrationRiskySetTest.php
  tests/RuleSet/Sets/PHP74MigrationSetTest.php
  tests/RuleSet/Sets/PHP80MigrationRiskySetTest.php
  tests/RuleSet/Sets/PHP80MigrationSetTest.php
  tests/RuleSet/Sets/PHP81MigrationSetTest.php
  tests/RuleSet/Sets/PHP82MigrationSetTest.php
  tests/RuleSet/Sets/PHPUnit100MigrationRiskySetTest.php
  tests/RuleSet/Sets/PHPUnit30MigrationRiskySetTest.php
  tests/RuleSet/Sets/PHPUnit32MigrationRiskySetTest.php
  tests/RuleSet/Sets/PHPUnit35MigrationRiskySetTest.php
  tests/RuleSet/Sets/PHPUnit43MigrationRiskySetTest.php
  tests/RuleSet/Sets/PHPUnit48MigrationRiskySetTest.php
  tests/RuleSet/Sets/PHPUnit50MigrationRiskySetTest.php
  tests/RuleSet/Sets/PHPUnit52MigrationRiskySetTest.php
  tests/RuleSet/Sets/PHPUnit54MigrationRiskySetTest.php
  tests/RuleSet/Sets/PHPUnit55MigrationRiskySetTest.php
  tests/RuleSet/Sets/PHPUnit56MigrationRiskySetTest.php
  tests/RuleSet/Sets/PHPUnit57MigrationRiskySetTest.php
  tests/RuleSet/Sets/PHPUnit60MigrationRiskySetTest.php
  tests/RuleSet/Sets/PHPUnit75MigrationRiskySetTest.php
  tests/RuleSet/Sets/PHPUnit84MigrationRiskySetTest.php
  tests/RuleSet/Sets/PSR12RiskySetTest.php
  tests/RuleSet/Sets/PSR12SetTest.php
  tests/RuleSet/Sets/PSR1SetTest.php
  tests/RuleSet/Sets/PSR2SetTest.php
  tests/RuleSet/Sets/PhpCsFixerRiskySetTest.php
  tests/RuleSet/Sets/PhpCsFixerSetTest.php
  tests/RuleSet/Sets/SymfonyRiskySetTest.php
  tests/RuleSet/Sets/SymfonySetTest.php
  tests/Smoke/AbstractSmokeTestCase.php
  tests/Smoke/CiIntegrationTest.php
  tests/Smoke/InstallViaComposerTest.php
  tests/Smoke/PharTest.php
  tests/Smoke/StdinTest.php
Labels: kind/refactoring, topic/phpunit

#7102 DX: fix checkbashisms installation
  dev-tools/install.sh
Labels: kind/enhancement

#7107 DX: test all PHPUnit migration sets
  tests/RuleSet/RuleSetsTest.php
Labels: kind/enhancement
