Repository PHP-CS-Fixer/PHP-CS-Fixer, pull requests merged in 2023-10, with the labels that each got.

#6992 docs: config file - provide better link to Finder docs
  doc/config.rst
Labels: topic/documentation

#7397 fix: OrderedImportsFixer - handle non-grouped list of const/function imports
  src/Fixer/Import/OrderedImportsFixer.php
  tests/Fixer/Import/OrderedImportsFixerTest.php
Labels: kind/bug

#7398 DX: Do not mark as stale issues/PRs with milestone assigned
  .github/workflows/issues_and_pull_requests.yml
Labels: topic/ci

#6356 feat: phpDoc to property/return/param Fixer - allow fixing mixed on PHP >= 8
  src/Fixer/FunctionNotation/PhpdocToParamTypeFixer.php
  src/Fixer/FunctionNotation/PhpdocToPropertyTypeFixer.php
  src/Fixer/FunctionNotation/PhpdocToReturnTypeFixer.php
  tests/Fixer/FunctionNotation/PhpdocToParamTypeFixerTest.php
  tests/Fixer/FunctionNotation/PhpdocToPropertyTypeFixerTest.php
  tests/Fixer/FunctionNotation/PhpdocToReturnTypeFixerTest.php
Labels: kind/enhancement
