Repository PHP-CS-Fixer/PHP-CS-Fixer, pull requests merged in 2023-02, with the labels that each got.

#6776 bug: CurlyBracesPositionFixer - fix for open brace not preceded by space and followed by a comment
  src/Fixer/Basic/CurlyBracesPositionFixer.php
  tests/Fixer/Basic/CurlyBracesPositionFixerTest.php
Labels: kind/bug

#6781 DX: Add composer keywords
  composer.json
Labels: kind/enhancement

#6792 bug: FunctionsAnalyzer - fix detecting global function
  src/Tokenizer/Analyzer/FunctionsAnalyzer.php
  tests/Fixer/LanguageConstruct/IsNullFixerTest.php
  tests/Tokenizer/Analyzer/FunctionsAnalyzerTest.php
Labels: kind/bug

#6745 feature: [PHP8.2] Support for readonly classes
  src/AbstractDoctrineAnnotationFixer.php
  src/Fixer/AbstractPhpUnitFixer.php
  src/Fixer/ClassNotation/ClassDefinitionFixer.php
  src/Fixer/ClassNotation/FinalInternalClassFixer.php
  src/Fixer/ClassNotation/NoUnneededFinalMethodFixer.php
  src/Fixer/ClassNotation/ProtectedToPrivateFixer.php
  src/Fixer/ClassNotation/SelfStaticAccessorFixer.php
  src/Fixer/PhpUnit/PhpUnitInternalClassFixer.php
  src/Fixer/PhpUnit/PhpUnitTestClassRequiresCoversFixer.php
  src/Tokenizer/TokensAnalyzer.php
  tests/Fixer/ClassNotation/ClassDefinitionFixerTest.php
  tests/Fixer/ClassNotation/FinalInternalClassFixerTest.php
  tests/Fixer/ClassNotation/NoUnneededFinalMethodFixerTest.php
  tests/Fixer/ClassNotation/ProtectedToPrivateFixerTest.php
  tests/Fixer/ClassNotation/SelfStaticAccessorFixerTest.php
  tests/Fixer/DoctrineAnnotation/DoctrineAnnotationBracesFixerTest.php
  tests/Fixer/PhpUnit/PhpUnitInternalClassFixerTest.php
  tests/Fixer/PhpUnit/PhpUnitTestClassRequiresCoversFixerTest.php
  tests/Fixtures/Integration/misc/PHP8_2.test
  tests/Tokenizer/TokensAnalyzerTest.php
Labels: topic/PHP8.2
