Repository PHP-CS-Fixer/PHP-CS-Fixer, pull requests merged in 2023-03, with the labels that each got.

#6803 minor: PHP8.2 - support property in const expressions
  tests/Fixtures/Integration/misc/PHP8_2.test
Labels: topic/PHP8.2

#6812 bug: NativeFunctionTypeDeclarationCasingFixer - do not require T_STRING present in code
  src/Fixer/Casing/NativeFunctionTypeDeclarationCasingFixer.php
  tests/Fixer/Casing/NativeFunctionTypeDeclarationCasingFixerTest.php
Labels: kind/bug, RTM

#6810 bug: PhpdocTypesFixer - do not change case of array keys
  src/Fixer/Phpdoc/PhpdocTypesFixer.php
  tests/Fixer/Phpdoc/PhpdocTypesFixerTest.php
Labels: kind/bug, RTM

#6804 minor: PHP8.2 - handle union and intersection types for DNF types
  src/Tokenizer/AbstractTypeTransformer.php
  tests/Fixtures/Integration/misc/PHP8_2.test
  tests/Tokenizer/TokensAnalyzerTest.php
  tests/Tokenizer/Transformer/TypeAlternationTransformerTest.php
  tests/Tokenizer/Transformer/TypeIntersectionTransformerTest.php
Labels: RTM, topic/PHP8.2

#6824 bug: PhpUnitTestAnnotationFixer - do not break single line @depends
  src/Fixer/PhpUnit/PhpUnitTestAnnotationFixer.php
  tests/Fixer/PhpUnit/PhpUnitTestAnnotationFixerTest.php
Labels: kind/bug, RTM

#6823 minor: add custom tokens for Disjunctive Normal Form types parentheses
  src/Tokenizer/CT.php
  src/Tokenizer/Tokens.php
  src/Tokenizer/Transformer/DisjunctiveNormalFormTypeParenthesisTransformer.php
  tests/AutoReview/TransformerTest.php
  tests/Tokenizer/TokensTest.php
  tests/Tokenizer/Transformer/DisjunctiveNormalFormTypeParenthesisTransformerTest.php
Labels: kind/feature, topic/PHP8.2

#6806 bug: VisibilityRequiredFixer - handle DNF types
  src/Fixer/ClassNotation/VisibilityRequiredFixer.php
  tests/Fixer/ClassNotation/VisibilityRequiredFixerTest.php
Labels: kind/bug, topic/PHP8.2

#6827 minor: fix CI on PHP 8.3
  tests/Fixer/ControlStructure/NoUselessElseFixerTest.php
Labels: kind/bug

#6831 feature: Support for type casing in arrow functions
  src/Fixer/Casing/NativeFunctionTypeDeclarationCasingFixer.php
  tests/Fixer/Casing/NativeFunctionTypeDeclarationCasingFixerTest.php
Labels: kind/feature

#6826 bug: BinaryOperatorSpacesFixer - fix parameters with union types passed by reference
  src/Tokenizer/AbstractTypeTransformer.php
  tests/Fixer/Operator/BinaryOperatorSpacesFixerTest.php
  tests/Tokenizer/TokensAnalyzerTest.php
  tests/Tokenizer/Transformer/TypeAlternationTransformerTest.php
  tests/Tokenizer/Transformer/TypeIntersectionTransformerTest.php
Labels: kind/bug, RTM

#6835 bug: BinaryOperatorSpacesFixer - fix for static in type
  src/Tokenizer/AbstractTypeTransformer.php
  tests/Fixer/Operator/BinaryOperatorSpacesFixerTest.php
  tests/Tokenizer/Transformer/TypeAlternationTransformerTest.php
  tests/Tokenizer/Transformer/TypeIntersectionTransformerTest.php
Labels: kind/bug

#6837 DX: fix CI
  tests/Tokenizer/Transformer/TypeAlternationTransformerTest.php
Labels: kind/enhancement

#6836 bug: NoUnusedImportsFixer - fix for splat operator
  src/Tokenizer/AbstractTypeTransformer.php
  tests/Fixer/Import/NoUnusedImportsFixerTest.php
  tests/Tokenizer/Transformer/TypeAlternationTransformerTest.php
  tests/Tokenizer/Transformer/TypeIntersectionTransformerTest.php
Labels: kind/bug

#5126 bug: Fix MultilineWhitespaceBeforeSemicolonsFixer
  src/AbstractPhpdocTypesFixer.php
  src/Console/Application.php
  src/Console/Command/FixCommand.php
  src/Console/Command/HelpCommand.php
  src/Console/Command/ListSetsCommand.php
  src/Console/Output/ErrorOutput.php
  src/Differ/DiffConsoleFormatter.php
  src/Documentation/FixerDocumentGenerator.php
  src/Fixer/Basic/BracesFixer.php
  src/Fixer/Basic/NoTrailingCommaInSinglelineFixer.php
  src/Fixer/Basic/OctalNotationFixer.php
  src/Fixer/ClassNotation/VisibilityRequiredFixer.php
  src/Fixer/ControlStructure/NoAlternativeSyntaxFixer.php
  src/Fixer/ControlStructure/NoSuperfluousElseifFixer.php
  src/Fixer/ControlStructure/NoUnneededControlParenthesesFixer.php
  src/Fixer/ControlStructure/YodaStyleFixer.php
  src/Fixer/FunctionNotation/MethodArgumentSpaceFixer.php
  src/Fixer/Operator/BinaryOperatorSpacesFixer.php
  src/Fixer/PhpTag/EchoTagSyntaxFixer.php
  src/Fixer/PhpUnit/PhpUnitMethodCasingFixer.php
  src/Fixer/PhpUnit/PhpUnitTestAnnotationFixer.php
  src/Fixer/Phpdoc/NoSuperfluousPhpdocTagsFixer.php
  src/Fixer/Phpdoc/PhpdocAlignFixer.php
  src/Fixer/Phpdoc/PhpdocTagTypeFixer.php
  src/Fixer/ReturnNotation/ReturnAssignmentFixer.php
  src/Fixer/Semicolon/MultilineWhitespaceBeforeSemicolonsFixer.php
  src/Fixer/StringNotation/EscapeImplicitBackslashesFixer.php
  src/Fixer/StringNotation/ExplicitStringVariableFixer.php
  src/Fixer/StringNotation/StringLengthToEmptyFixer.php
  src/Fixer/Whitespace/MethodChainingIndentationFixer.php
  src/Fixer/Whitespace/StatementIndentationFixer.php
  src/Tokenizer/Analyzer/ControlCaseStructuresAnalyzer.php
  src/Tokenizer/Tokens.php
  tests/AutoReview/CommandTest.php
  tests/Fixer/ControlStructure/NoUselessElseFixerTest.php
  tests/Fixer/Import/OrderedImportsFixerTest.php
  tests/Fixer/Import/SingleImportPerStatementFixerTest.php
  tests/Fixer/PhpUnit/PhpUnitExpectationFixerTest.php
  tests/Fixer/Semicolon/MultilineWhitespaceBeforeSemicolonsFixerTest.php
  tests/Fixer/Whitespace/NoExtraBlankLinesFixerTest.php
  tests/FixerFactoryTest.php
  tests/Test/TokensWithObservedTransformers.php
  tests/Tokenizer/Analyzer/ControlCaseStructuresAnalyzerTest.php
  tests/Tokenizer/Transformer/NameQualifiedTransformerTest.php
Labels: kind/bug, RTM

#6843 DX: fix checkbashisms installation
  dev-tools/install.sh
Labels: kind/enhancement

#6844 docs: Fix rule description
  doc/list.rst
  doc/rules/index.rst
  doc/rules/operator/concat_space.rst
  src/Fixer/Operator/ConcatSpaceFixer.php
Labels: topic/documentation

#6756 DX: refactor PHPUnit fixers adding class-level annotation to use shared code
  src/Fixer/AbstractPhpUnitFixer.php
  src/Fixer/PhpUnit/PhpUnitInternalClassFixer.php
  src/Fixer/PhpUnit/PhpUnitSizeClassFixer.php
  src/Fixer/PhpUnit/PhpUnitTestClassRequiresCoversFixer.php
  tests/Fixer/PhpUnit/PhpUnitSizeClassFixerTest.php
  tests/Fixer/PhpUnit/PhpUnitTestClassRequiresCoversFixerTest.php
Labels: kind/refactoring, RTM

#6859 bug: CurlyBracesPositionFixer - fix for DNF types
  src/Fixer/Basic/CurlyBracesPositionFixer.php
  tests/Fixer/Basic/CurlyBracesPositionFixerTest.php
Labels: kind/bug

#6834 minor: Use Composer binary-only images instead of installer script
  docker/php-7.4/Dockerfile
  docker/php-8.0/Dockerfile
  docker/php-8.1/Dockerfile
Labels: kind/enhancement, RTM

#6833 minor: PHP8.2 Docker runtime
  .gitignore
  CONTRIBUTING.md
  docker-compose.override.yaml.dist
  docker-compose.yaml
  docker/php-8.2/Dockerfile
  docker/php-8.2/xdebug.ini
Labels: kind/enhancement

#6757 feature: add "force" option to PhpUnitDataProviderStaticFixer
  doc/list.rst
  doc/rules/php_unit/php_unit_data_provider_static.rst
  src/Fixer/PhpUnit/PhpUnitDataProviderStaticFixer.php
  tests/Fixer/PhpUnit/PhpUnitDataProviderStaticFixerTest.php
Labels: kind/feature

#6856 DX: unify option's descriptions
  doc/list.rst
  doc/rules/alias/no_alias_functions.rst
  doc/rules/basic/braces.rst
  doc/rules/basic/curly_braces_position.rst
  doc/rules/cast_notation/cast_spaces.rst
  doc/rules/class_notation/final_internal_class.rst
  doc/rules/class_notation/ordered_class_elements.rst
  doc/rules/class_notation/ordered_interfaces.rst
  doc/rules/comment/comment_to_phpdoc.rst
  doc/rules/comment/single_line_comment_style.rst
  doc/rules/control_structure/control_structure_continuation_position.rst
  doc/rules/import/ordered_imports.rst
  doc/rules/language_construct/error_suppression.rst
  doc/rules/operator/binary_operator_spaces.rst
  doc/rules/operator/operator_linebreak.rst
  doc/rules/php_tag/echo_tag_syntax.rst
  doc/rules/php_unit/php_unit_internal_class.rst
  doc/rules/php_unit/php_unit_method_casing.rst
  doc/rules/php_unit/php_unit_size_class.rst
  doc/rules/phpdoc/no_superfluous_phpdoc_tags.rst
  doc/rules/phpdoc/phpdoc_align.rst
  doc/rules/phpdoc/phpdoc_inline_tag_normalizer.rst
  doc/rules/phpdoc/phpdoc_line_span.rst
  doc/rules/phpdoc/phpdoc_tag_type.rst
  doc/rules/phpdoc/phpdoc_to_comment.rst
  doc/rules/whitespace/types_spaces.rst
  src/Fixer/Alias/NoAliasFunctionsFixer.php
  src/Fixer/Basic/BracesFixer.php
  src/Fixer/Basic/CurlyBracesPositionFixer.php
  src/Fixer/CastNotation/CastSpacesFixer.php
  src/Fixer/ClassNotation/FinalInternalClassFixer.php
  src/Fixer/ClassNotation/OrderedClassElementsFixer.php
  src/Fixer/ClassNotation/OrderedInterfacesFixer.php
  src/Fixer/Comment/CommentToPhpdocFixer.php
  src/Fixer/Comment/SingleLineCommentStyleFixer.php
  src/Fixer/ControlStructure/ControlStructureContinuationPositionFixer.php
  src/Fixer/Import/OrderedImportsFixer.php
  src/Fixer/LanguageConstruct/ErrorSuppressionFixer.php
  src/Fixer/Operator/BinaryOperatorSpacesFixer.php
  src/Fixer/Operator/OperatorLinebreakFixer.php
  src/Fixer/PhpTag/EchoTagSyntaxFixer.php
  src/Fixer/PhpUnit/PhpUnitInternalClassFixer.php
  src/Fixer/PhpUnit/PhpUnitMethodCasingFixer.php
  src/Fixer/PhpUnit/PhpUnitSizeClassFixer.php
  src/Fixer/Phpdoc/NoSuperfluousPhpdocTagsFixer.php
  src/Fixer/Phpdoc/PhpdocAlignFixer.php
  src/Fixer/Phpdoc/PhpdocInlineTagNormalizerFixer.php
  src/Fixer/Phpdoc/PhpdocLineSpanFixer.php
  src/Fixer/Phpdoc/PhpdocTagTypeFixer.php
  src/Fixer/Phpdoc/PhpdocToCommentFixer.php
  src/Fixer/Whitespace/TypesSpacesFixer.php
  tests/Test/AbstractFixerTestCase.php
Labels: kind/enhancement

#6847 feature: PhpUnitTestClassRequiresCoversFixer - support single-line PHPDocs
  src/Fixer/AbstractPhpUnitFixer.php
  src/Fixer/PhpUnit/PhpUnitInternalClassFixer.php
  src/Fixer/PhpUnit/PhpUnitSizeClassFixer.php
  src/Fixer/PhpUnit/PhpUnitTestClassRequiresCoversFixer.php
  tests/Fixer/PhpUnit/PhpUnitTestClassRequiresCoversFixerTest.php
Labels: kind/feature

#4885 minor: Deprecate BracesFixer
  doc/list.rst
  doc/ruleSets/PSR12.rst
  doc/ruleSets/PSR2.rst
  doc/ruleSets/Symfony.rst
  doc/rules/basic/braces.rst
  doc/rules/basic/curly_braces_position.rst
  doc/rules/basic/no_multiple_statements_per_line.rst
  doc/rules/control_structure/control_structure_braces.rst
  doc/rules/control_structure/control_structure_continuation_position.rst
  doc/rules/index.rst
  doc/rules/language_construct/declare_parentheses.rst
  doc/rules/whitespace/statement_indentation.rst
  src/Fixer/Basic/BracesFixer.php
  src/RuleSet/Sets/PSR12Set.php
  src/RuleSet/Sets/PSR2Set.php
  src/RuleSet/Sets/SymfonySet.php
  tests/ConfigTest.php
  tests/Console/ConfigurationResolverTest.php
  tests/Fixtures/Integration/misc/PHP7_4.test
  tests/RuleSet/RuleSetTest.php
Labels: kind/refactoring, kind/deprecation

#6858 feature: AbstractPhpUnitFixer - support attribute detection in docblock insertion
  src/Fixer/AbstractPhpUnitFixer.php
  tests/Fixer/PhpUnit/PhpUnitInternalClassFixerTest.php
  tests/Fixer/PhpUnit/PhpUnitMethodCasingFixerTest.php
  tests/Fixer/PhpUnit/PhpUnitSizeClassFixerTest.php
  tests/Fixer/PhpUnit/PhpUnitTestAnnotationFixerTest.php
Labels: kind/feature
