Repository PHP-CS-Fixer/PHP-CS-Fixer, pull requests merged in 2023-12, with the labels that each got.

#7488 DX: fix PHPStan error
  tests/Console/Output/ErrorOutputTest.php
Labels: kind/enhancement

#7486 DX: Update PHPStan to 1.10.46
  dev-tools/composer.lock
Labels: topic/ci

#7491 DX: PsrAutoloadingFixerTest - do not build mock in data provider
  tests/Fixer/Basic/PsrAutoloadingFixerTest.php
  tests/Test/AbstractFixerTestCase.php
Labels: kind/enhancement

#7492 DX: PsrAutoloadingFixerTest - merge all data providers into one
  phpstan.dist.neon
  tests/Fixer/Basic/PsrAutoloadingFixerTest.php
Labels: kind/enhancement

#7501 DX: replace Prophecy with anonymous classes in ProcessLintingResultTest
  tests/Linter/ProcessLintingResultTest.php
Labels: kind/enhancement

#7499 feat: Support `mb_str_pad` function in `mb_str_functions` rule
  src/Fixer/Alias/MbStrFunctionsFixer.php
  tests/Fixer/Alias/MbStrFunctionsFixerTest.php
Labels: kind/feature

#7503 DX: replace Prophecy with anonymous classes in CacheTest
  tests/Cache/CacheTest.php
Labels: kind/enhancement

#7513 fix: Downgrade PDepend to version not supporting Symfony 7
  dev-tools/composer.json
  dev-tools/composer.lock
Labels: topic/ci

#7522 fix: GlobalNamespaceImportFixer - key in PHPDoc's array shape matching class name
  src/Fixer/Import/GlobalNamespaceImportFixer.php
  tests/Fixer/Import/GlobalNamespaceImportFixerTest.php
Labels: kind/bug

#7523 fix: BinaryOperatorSpacesFixer - do not add whitespace inside short function
  src/Tokenizer/TokensAnalyzer.php
  tests/Fixer/Operator/BinaryOperatorSpacesFixerTest.php
  tests/Tokenizer/TokensAnalyzerTest.php
Labels: kind/bug

#7509 DX: remove Prophecy
  .github/composite-actions/install-composer-deps/action.yml
  composer.json
  tests/AutoReview/ProjectCodeTest.php
  tests/Cache/FileCacheManagerTest.php
  tests/Console/Command/DescribeCommandTest.php
  tests/Console/Command/SelfUpdateCommandTest.php
  tests/Console/Report/FixReport/ReporterFactoryTest.php
  tests/Console/Report/ListSetsReport/ReporterFactoryTest.php
  tests/Console/SelfUpdate/NewVersionCheckerTest.php
  tests/Console/WarningsDetectorTest.php
  tests/FixerConfiguration/DeprecatedFixerOptionTest.php
  tests/FixerDefinition/FixerDefinitionTest.php
  tests/FixerDefinition/VersionSpecificCodeSampleTest.php
  tests/FixerFactoryTest.php
  tests/Linter/CachingLinterTest.php
  tests/Runner/FileFilterIteratorTest.php
  tests/Runner/FileLintingIteratorTest.php
  tests/Runner/RunnerTest.php
  tests/TestCase.php
  tests/UtilsTest.php
Labels: kind/enhancement

#7531 fix: SpacesInsideParenthesesFixer - handle class instantiation parentheses
  src/Fixer/Whitespace/SpacesInsideParenthesesFixer.php
  tests/Fixer/Whitespace/SpacesInsideParenthesesFixerTest.php
Labels: kind/bug

#7532 DX: udate PHPstan to 1.10.48
  dev-tools/composer.json
  dev-tools/composer.lock
  src/Runner/FileLintingIterator.php
  tests/Cache/FileCacheManagerTest.php
  tests/FixerConfiguration/DeprecatedFixerOptionTest.php
  tests/FixerFactoryTest.php
Labels: kind/enhancement

#7527 DX: AbstractFixerTest - use anonymous classes
  tests/AbstractFixerTest.php
  tests/Fixtures/Test/AbstractFixerTest/SimpleFixer.php
  tests/Fixtures/Test/AbstractFixerTest/UnconfigurableFixer.php
Labels: kind/enhancement

#7535 DX: Change `@testWith` to `@dataProvider`
  tests/Linter/ProcessLinterProcessBuilderTest.php
  tests/Runner/FileFilterIteratorTest.php
Labels: topic/tests

#7534 DX: Introduce Markdownlint
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/workflows/markdown.yml
  .mdlrc
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
  UPGRADE-v3.md
  compose.yaml
  dev-tools/markdown.style.rb
  logo.md
Labels: topic/documentation, topic/ci

#7538 fix: NativeTypeDeclarationCasingFixer - do not crash on `var` keyword
  src/Fixer/Casing/NativeTypeDeclarationCasingFixer.php
  tests/Fixer/Casing/NativeTypeDeclarationCasingFixerTest.php
Labels: kind/bug

#7540 fix: AbstractFixerTestCase - fix checking for correct casing
  doc/rules/index.rst
  doc/rules/phpdoc/phpdoc_align.rst
  doc/rules/phpdoc/phpdoc_order_by_value.rst
  src/Fixer/Phpdoc/PhpdocAlignFixer.php
  src/Fixer/Phpdoc/PhpdocOrderByValueFixer.php
  tests/Test/AbstractFixerTestCase.php
Labels: kind/bug

#7536 CI: Introduce `composer-unused`
  .github/workflows/sca.yml
  composer.json
  dev-tools/composer.json
  dev-tools/composer.lock
Labels: topic/ci

#7549 DX: Unify Docker mount points and paths
  CONTRIBUTING.md
  compose.yaml
  docker/xdebug.ini
Labels: kind/enhancement

#2918 feat(EXPERIMENTAL): ClassKeywordFixer
  doc/rules/index.rst
  doc/rules/language_construct/class_keyword.rst
  src/Fixer/LanguageConstruct/ClassKeywordFixer.php
  tests/Fixer/LanguageConstruct/ClassKeywordFixerTest.php
Labels: kind/feature

#7553 DX: use anonymous function over concrete classes
  tests/Console/ConfigurationResolverTest.php
  tests/Console/TestToolInfo.php
  tests/Differ/DummyTestSplFileInfo.php
  tests/Differ/UnifiedDifferTest.php
Labels: kind/enhancement

#5620 feat: add phpDoc support for `fully_qualified_strict_types` fixer
  doc/rules/import/fully_qualified_strict_types.rst
  phpstan.dist.neon
  src/Fixer/Import/FullyQualifiedStrictTypesFixer.php
  tests/Fixer/Import/FullyQualifiedStrictTypesFixerTest.php
  tests/Fixtures/Integration/priority/phpdoc_to_return_type,fully_qualified_strict_types.test
Labels: kind/enhancement, kind/feature, topic/fqcn

#7543 DX: check fixer's options for wording
  tests/Test/AbstractFixerTestCase.php
Labels: kind/enhancement

#7556 DX: Enforce consistent naming in tests
  phpstan.dist.neon
  tests/Fixer/Alias/NoAliasFunctionsFixerTest.php
  tests/Fixer/Alias/NoMixedEchoPrintFixerTest.php
  tests/Fixer/Alias/PowToExponentiationFixerTest.php
  tests/Fixer/Alias/RandomApiMigrationFixerTest.php
  tests/Fixer/ArrayNotation/ArraySyntaxFixerTest.php
  tests/Fixer/Basic/NoTrailingCommaInSinglelineFixerTest.php
  tests/Fixer/Basic/NonPrintableCharacterFixerTest.php
  tests/Fixer/Casing/NativeFunctionTypeDeclarationCasingFixerTest.php
  tests/Test/AbstractFixerTestCase.php
Labels: kind/enhancement

#7558 DX: unify tests for casing fixers
  phpstan.dist.neon
  tests/Fixer/Casing/ConstantCaseFixerTest.php
  tests/Fixer/Casing/LowercaseKeywordsFixerTest.php
  tests/Fixer/Casing/MagicConstantCasingFixerTest.php
  tests/Fixer/Casing/MagicMethodCasingFixerTest.php
  tests/Fixer/Casing/NativeTypeDeclarationCasingFixerTest.php
  tests/Test/AbstractFixerTestCase.php
Labels: kind/enhancement

#7288 feat: Handle deprecated rule sets similarly to deprecated fixers
  doc/ruleSets/PER-CS1.0.rst
  doc/ruleSets/PER-CS1.0Risky.rst
  doc/ruleSets/PER-CS2.0Risky.rst
  doc/ruleSets/PER-CSRisky.rst
  doc/ruleSets/PER.rst
  doc/ruleSets/PERRisky.rst
  doc/ruleSets/PHP56MigrationRisky.rst
  doc/ruleSets/PHP70MigrationRisky.rst
  doc/ruleSets/PHP71MigrationRisky.rst
  doc/ruleSets/PHP74MigrationRisky.rst
  doc/ruleSets/PHP80MigrationRisky.rst
  doc/ruleSets/PHPUnit100MigrationRisky.rst
  doc/ruleSets/PHPUnit30MigrationRisky.rst
  doc/ruleSets/PHPUnit32MigrationRisky.rst
  doc/ruleSets/PHPUnit35MigrationRisky.rst
  doc/ruleSets/PHPUnit43MigrationRisky.rst
  doc/ruleSets/PHPUnit48MigrationRisky.rst
  doc/ruleSets/PHPUnit50MigrationRisky.rst
  doc/ruleSets/PHPUnit52MigrationRisky.rst
  doc/ruleSets/PHPUnit54MigrationRisky.rst
  doc/ruleSets/PHPUnit55MigrationRisky.rst
  doc/ruleSets/PHPUnit56MigrationRisky.rst
  doc/ruleSets/PHPUnit57MigrationRisky.rst
  doc/ruleSets/PHPUnit60MigrationRisky.rst
  doc/ruleSets/PHPUnit75MigrationRisky.rst
  doc/ruleSets/PHPUnit84MigrationRisky.rst
  doc/ruleSets/PSR12Risky.rst
  doc/ruleSets/PhpCsFixerRisky.rst
  doc/ruleSets/SymfonyRisky.rst
  doc/ruleSets/index.rst
  src/Console/Command/DocumentationCommand.php
  src/Documentation/RuleSetDocumentationGenerator.php
  src/RuleSet/DeprecatedRuleSetDescriptionInterface.php
  src/RuleSet/RuleSet.php
  src/RuleSet/Sets/PERCS1x0RiskySet.php
  src/RuleSet/Sets/PERCS1x0Set.php
  src/RuleSet/Sets/PERRiskySet.php
  src/RuleSet/Sets/PERSet.php
  tests/AutoReview/DescribeCommandTest.php
  tests/AutoReview/DocumentationTest.php
  tests/Console/Command/DescribeCommandTest.php
  tests/Console/ConfigurationResolverTest.php
  tests/RuleSet/RuleSetTest.php
  tests/Smoke/PharTest.php
Labels: kind/feature, topic/documentation

#7563 DX: do not allow overriding constructor of `PHPUnit\Framework\TestCase`
  tests/Smoke/InstallViaComposerTest.php
  tests/TestCase.php
Labels: kind/enhancement

#7562 DX: do not import ExpectDeprecationTrait in UtilsTest
  tests/UtilsTest.php
Labels: kind/enhancement

#7561 DX: add types to anonymous functions
  src/Fixer/ClassNotation/OrderedTypesFixer.php
  src/Fixer/ControlStructure/TrailingCommaInMultilineFixer.php
  src/Fixer/NamespaceNotation/BlankLinesBeforeNamespaceFixer.php
  src/Fixer/Phpdoc/GeneralPhpdocTagRenameFixer.php
  src/Fixer/Phpdoc/PhpdocOrderByValueFixer.php
  src/Fixer/Phpdoc/PhpdocOrderFixer.php
  src/Fixer/Phpdoc/PhpdocSeparationFixer.php
  src/Fixer/Phpdoc/PhpdocTagTypeFixer.php
  tests/Fixer/PhpUnit/PhpUnitConstructFixerTest.php
  tests/Tokenizer/TokensAnalyzerTest.php
Labels: kind/enhancement

#7459 feat: Support more FQCNs cases in `fully_qualified_strict_types`
  doc/rules/import/fully_qualified_strict_types.rst
  doc/rules/index.rst
  src/Fixer/Import/FullyQualifiedStrictTypesFixer.php
  tests/Cache/NullCacheManagerTest.php
  tests/Cache/SignatureTest.php
  tests/Fixer/Import/FullyQualifiedStrictTypesFixerTest.php
  tests/Runner/FileFilterIteratorTest.php
  tests/Runner/RunnerTest.php
  tests/Tokenizer/CTTest.php
Labels: kind/feature, topic/fqcn

#7564 DX: remove `PhpUnitNamespacedFixerTest::testClassIsFixed`
  phpstan.dist.neon
  tests/Fixer/PhpUnit/PhpUnitNamespacedFixerTest.php
Labels: kind/enhancement

#7567 DX: fix checking test class extends `PhpCsFixer\Tests\TestCase`
  tests/AutoReview/ComposerFileTest.php
  tests/AutoReview/DocumentationTest.php
  tests/AutoReview/ProjectCodeTest.php
Labels: kind/enhancement

#7581 chore: unify tests not agnostic of PHP version
  phpstan.dist.neon
  tests/AutoReview/ProjectCodeTest.php
  tests/Fixer/CastNotation/CastSpacesFixerTest.php
  tests/Fixer/CastNotation/LowercaseCastFixerTest.php
  tests/Fixer/CastNotation/ModernizeTypesCastingFixerTest.php
  tests/Fixer/CastNotation/ShortScalarCastFixerTest.php
  tests/Fixer/ClassNotation/ClassAttributesSeparationFixerTest.php
  tests/Fixer/ClassNotation/ClassDefinitionFixerTest.php
  tests/Fixer/ClassNotation/FinalInternalClassFixerTest.php
  tests/Fixer/ClassNotation/NoBlankLinesAfterClassOpeningFixerTest.php
  tests/Fixer/ClassNotation/NoNullPropertyInitializationFixerTest.php
  tests/Fixer/ClassNotation/NoPhp4ConstructorFixerTest.php
  tests/Fixer/ClassNotation/NoUnneededFinalMethodFixerTest.php
  tests/Fixer/ClassNotation/OrderedClassElementsFixerTest.php
  tests/Fixer/ClassNotation/OrderedInterfacesFixerTest.php
  tests/Fixer/ClassNotation/OrderedTraitsFixerTest.php
  tests/Fixer/ClassNotation/OrderedTypesFixerTest.php
  tests/Fixer/ClassNotation/SingleClassElementPerStatementFixerTest.php
  tests/Fixer/ClassNotation/SingleTraitInsertPerStatementFixerTest.php
  tests/Fixer/ClassNotation/VisibilityRequiredFixerTest.php
  tests/Fixer/FunctionNotation/NullableTypeDeclarationForDefaultNullValueFixerTest.php
  tests/Fixer/FunctionNotation/PhpdocToParamTypeFixerTest.php
  tests/Fixer/FunctionNotation/PhpdocToPropertyTypeFixerTest.php
  tests/Fixer/FunctionNotation/PhpdocToReturnTypeFixerTest.php
  tests/Fixer/FunctionNotation/StaticLambdaFixerTest.php
  tests/Fixer/FunctionNotation/VoidReturnFixerTest.php
  tests/PregTest.php
  tests/Test/AbstractFixerTestCase.php
  tests/Tokenizer/Analyzer/Analysis/TypeAnalysisTest.php
  tests/Tokenizer/Analyzer/FunctionsAnalyzerTest.php
  tests/Tokenizer/Analyzer/GotoLabelAnalyzerTest.php
  tests/Tokenizer/TokensAnalyzerTest.php
  tests/Tokenizer/Transformer/TypeIntersectionTransformerTest.php
Labels: kind/enhancement

#7584 DX: unify fixer's test method names - quick wins
  phpstan.dist.neon
  tests/Fixer/ControlStructure/ControlStructureContinuationPositionFixerTest.php
  tests/Fixer/ControlStructure/EmptyLoopBodyFixerTest.php
  tests/Fixer/ControlStructure/EmptyLoopConditionFixerTest.php
  tests/Fixer/FunctionNotation/LambdaNotUsedImportFixerTest.php
  tests/Fixer/Import/NoLeadingImportSlashFixerTest.php
  tests/Fixer/Import/NoUnusedImportsFixerTest.php
  tests/Fixer/Import/SingleLineAfterImportsFixerTest.php
  tests/Fixer/LanguageConstruct/DeclareEqualNormalizeFixerTest.php
  tests/Fixer/LanguageConstruct/DirConstantFixerTest.php
  tests/Fixer/LanguageConstruct/NullableTypeDeclarationFixerTest.php
  tests/Fixer/NamespaceNotation/BlankLineAfterNamespaceFixerTest.php
  tests/Fixer/NamespaceNotation/NoLeadingNamespaceWhitespaceFixerTest.php
  tests/Fixer/Operator/LongToShorthandOperatorFixerTest.php
  tests/Fixer/Operator/TernaryToElvisOperatorFixerTest.php
  tests/Fixer/PhpTag/BlankLineAfterOpeningTagFixerTest.php
  tests/Fixer/PhpTag/LinebreakAfterOpeningTagFixerTest.php
  tests/Fixer/PhpUnit/PhpUnitDataProviderReturnTypeFixerTest.php
  tests/Fixer/PhpUnit/PhpUnitDedicateAssertInternalTypeFixerTest.php
  tests/Fixer/PhpUnit/PhpUnitExpectationFixerTest.php
  tests/Fixer/PhpUnit/PhpUnitNoExpectationAnnotationFixerTest.php
  tests/Fixer/PhpUnit/PhpUnitTestAnnotationFixerTest.php
  tests/Fixer/PhpUnit/PhpUnitTestClassRequiresCoversFixerTest.php
  tests/Fixer/Phpdoc/NoSuperfluousPhpdocTagsFixerTest.php
  tests/Fixer/Phpdoc/PhpdocIndentFixerTest.php
  tests/Fixer/Phpdoc/PhpdocTagTypeFixerTest.php
  tests/Fixer/Phpdoc/PhpdocToCommentFixerTest.php
  tests/Fixer/Phpdoc/PhpdocTypesFixerTest.php
  tests/Fixer/Strict/DeclareStrictTypesFixerTest.php
  tests/Fixer/StringNotation/StringLineEndingFixerTest.php
  tests/Fixer/Whitespace/ArrayIndentationFixerTest.php
  tests/Fixer/Whitespace/BlankLineBetweenImportGroupsFixerTest.php
  tests/Fixer/Whitespace/HeredocIndentationFixerTest.php
  tests/Fixer/Whitespace/LineEndingFixerTest.php
  tests/Fixer/Whitespace/MethodChainingIndentationFixerTest.php
  tests/Fixer/Whitespace/NoWhitespaceInBlankLineFixerTest.php
  tests/Fixer/Whitespace/SingleBlankLineAtEofFixerTest.php
  tests/Fixer/Whitespace/TypeDeclarationSpacesFixerTest.php
  tests/Test/AbstractFixerTestCase.php
Labels: kind/enhancement

#7589 fix: NativeTypeDeclarationCasingFixe - handle static property without type
  src/Fixer/Casing/NativeTypeDeclarationCasingFixer.php
  tests/Fixer/Casing/NativeTypeDeclarationCasingFixerTest.php
Labels: kind/bug

#7576 DX: cleanup deprecation message
  tests/DocBlock/TagComparatorTest.php
  tests/Fixer/CastNotation/LowercaseCastFixerTest.php
Labels: kind/enhancement

#7588 DX: make sure that exceptions in `AbstractFixerTestCase::testProperMethodNaming` are not already fixed
  phpstan.dist.neon
  tests/Fixer/ControlStructure/NoUnneededBracesFixerTest.php
  tests/Fixer/FunctionNotation/FopenFlagsFixerTest.php
  tests/Fixer/LanguageConstruct/CombineConsecutiveIssetsFixerTest.php
  tests/Fixer/PhpUnit/PhpUnitFqcnAnnotationFixerTest.php
  tests/Fixer/StringNotation/SingleQuoteFixerTest.php
  tests/Test/AbstractFixerTestCase.php
Labels: kind/enhancement

#7597 feat: Ability to import FQCNs found during analysis
  dev-tools/phpstan/baseline.php
  doc/rules/import/fully_qualified_strict_types.rst
  src/Fixer/Import/FullyQualifiedStrictTypesFixer.php
  src/Fixer/Import/GlobalNamespaceImportFixer.php
  src/Fixer/Import/OrderedImportsFixer.php
  src/Fixer/Whitespace/StatementIndentationFixer.php
  src/Tokenizer/Processor/ImportProcessor.php
  src/Tokenizer/Transformer/NameQualifiedTransformer.php
  tests/AutoReview/FixerFactoryTest.php
  tests/Fixer/Import/FullyQualifiedStrictTypesFixerTest.php
  tests/Fixer/Import/GlobalNamespaceImportFixerTest.php
  tests/Fixtures/Integration/priority/fully_qualified_strict_types,ordered_imports.test
  tests/Fixtures/Integration/priority/fully_qualified_strict_types,statement_indentation.test
  tests/Fixtures/Integration/priority/global_namespace_import,statement_indentation.test
  tests/Tokenizer/Processor/ImportProcessorTest.php
Labels: kind/enhancement, kind/feature, topic/types, topic/fqcn

#7602 chore: do not check PHP_VERSION_ID
  tests/Fixer/ClassNotation/ClassDefinitionFixerTest.php
  tests/Fixer/FunctionNotation/NativeFunctionInvocationFixerTest.php
  tests/Fixer/FunctionNotation/RegularCallableCallFixerTest.php
  tests/Fixer/LanguageConstruct/NoUnsetOnPropertyFixerTest.php
  tests/Fixer/Operator/AssignNullCoalescingToCoalesceEqualFixerTest.php
  tests/Fixer/Operator/IncrementStyleFixerTest.php
  tests/Fixer/Operator/OperatorLinebreakFixerTest.php
  tests/Fixer/Whitespace/NoExtraBlankLinesFixerTest.php
  tests/Fixer/Whitespace/NoSpacesAroundOffsetFixerTest.php
  tests/FixerDefinition/VersionSpecificCodeSampleTest.php
  tests/FixerDefinition/VersionSpecificationTest.php
Labels: kind/enhancement

#7578 DX: remove `symfony/phpunit-bridge`
  composer.json
  phpunit.xml.dist
  tests/AutoReview/DocumentationTest.php
  tests/FileRemovalTest.php
  tests/Smoke/InstallViaComposerTest.php
  tests/TestCase.php
  tests/UtilsTest.php
Labels: kind/enhancement

#7608 DX: Allow running smoke tests within Docker runtime
  Dockerfile
Labels: kind/enhancement

#7577 DX: remove recursion from AbstractIntegrationTestCase::testIntegration
  tests/Test/AbstractIntegrationTestCase.php
Labels: kind/enhancement

#7622 fix: Improve how FQCN is handled in phpDoc
  src/Fixer/Import/FullyQualifiedStrictTypesFixer.php
  tests/Fixer/Import/FullyQualifiedStrictTypesFixerTest.php
Labels: topic/annotation, topic/fqcn

#7628 feat: Configurable phpDoc tags for FQCN processing
  doc/rules/import/fully_qualified_strict_types.rst
  src/Fixer/Import/FullyQualifiedStrictTypesFixer.php
  tests/Fixer/Import/FullyQualifiedStrictTypesFixerTest.php
Labels: kind/enhancement, topic/fqcn

#7635 fix: Import only unique symbols' short names
  src/Fixer/Import/FullyQualifiedStrictTypesFixer.php
  tests/Fixer/Import/FullyQualifiedStrictTypesFixerTest.php
Labels: kind/bug, topic/fqcn

#7603 feat: Introduce percentage bar as new default progress output
  ci-integration.sh
  doc/usage.rst
  phpstan.dist.neon
  src/Console/Command/FixCommand.php
  src/Console/ConfigurationResolver.php
  src/Console/Output/Progress/PercentageBarOutput.php
  src/Console/Output/Progress/ProgressOutputFactory.php
  src/Console/Output/Progress/ProgressOutputType.php
  tests/Console/ConfigurationResolverTest.php
  tests/Console/Output/Progress/PercentageBarOutputTest.php
  tests/Console/Output/Progress/ProgressOutputTypeTest.php
Labels: kind/feature, topic/I/O, topic/core

#7629 feat: Enable symbol importing in `@PhpCsFixer` ruleset
  doc/ruleSets/PhpCsFixer.rst
  doc/rules/import/fully_qualified_strict_types.rst
  src/Console/Output/ErrorOutput.php
  src/RuleSet/Sets/PhpCsFixerSet.php
  tests/AutoReview/ProjectCodeTest.php
  tests/Cache/FileHandlerTest.php
  tests/Cache/NullCacheManagerTest.php
  tests/Cache/SignatureTest.php
  tests/Console/ConfigurationResolverTest.php
  tests/Differ/AbstractDifferTestCase.php
  tests/DocBlock/DocBlockTest.php
  tests/Fixer/Alias/NoAliasFunctionsFixerTest.php
  tests/Fixer/ControlStructure/YodaStyleFixerTest.php
  tests/FixerConfiguration/InvalidOptionsForEnvExceptionTest.php
  tests/FixerDefinition/FileSpecificCodeSampleTest.php
  tests/Linter/TokenizerLintingResultTest.php
  tests/Test/AbstractFixerTestCase.php
Labels: topic/fqcn
