Repository PHP-CS-Fixer/PHP-CS-Fixer, pull requests merged in 2024-05, with the labels that each got.

#8006 DX: Install PCov extension for local Docker
  Dockerfile
Labels: topic/docker

#7777 feat: Ability to run Fixer with parallel runner 🎉
  .php-cs-fixer.dist.php
  composer.json
  doc/usage.rst
  src/Config.php
  src/Console/Application.php
  src/Console/Command/FixCommand.php
  src/Console/Command/FixCommandExitStatusCalculator.php
  src/Console/Command/WorkerCommand.php
  src/Console/ConfigurationResolver.php
  src/Error/Error.php
  src/Error/ErrorsManager.php
  src/Error/SourceExceptionFactory.php
  src/FixerFileProcessedEvent.php
  src/ParallelAwareConfigInterface.php
  src/Runner/FileCachingLintingFileIterator.php
  src/Runner/LintingFileIterator.php
  src/Runner/LintingResultAwareFileIteratorInterface.php
  src/Runner/Parallel/ParallelAction.php
  src/Runner/Parallel/ParallelConfig.php
  src/Runner/Parallel/ParallelConfigFactory.php
  src/Runner/Parallel/ParallelisationException.php
  src/Runner/Parallel/Process.php
  src/Runner/Parallel/ProcessFactory.php
  src/Runner/Parallel/ProcessIdentifier.php
  src/Runner/Parallel/ProcessPool.php
  src/Runner/Parallel/WorkerException.php
  src/Runner/Runner.php
  src/Runner/RunnerConfig.php
  tests/AutoReview/ProjectCodeTest.php
  tests/Cache/FileCacheManagerTest.php
  tests/ConfigTest.php
  tests/Console/ApplicationTest.php
  tests/Console/Command/FixCommandExitStatusCalculatorTest.php
  tests/Console/Command/FixCommandTest.php
  tests/Console/Command/WorkerCommandTest.php
  tests/Console/ConfigurationResolverTest.php
  tests/Error/ErrorTest.php
  tests/Error/ErrorsManagerTest.php
  tests/Error/SourceExceptionFactoryTest.php
  tests/Runner/FileCachingLintingFileIteratorTest.php
  tests/Runner/LintingFileIteratorTest.php
  tests/Runner/Parallel/ParallelConfigFactoryTest.php
  tests/Runner/Parallel/ParallelConfigTest.php
  tests/Runner/Parallel/ParallelisationExceptionTest.php
  tests/Runner/Parallel/ProcessFactoryTest.php
  tests/Runner/Parallel/ProcessIdentifierTest.php
  tests/Runner/Parallel/ProcessPoolTest.php
  tests/Runner/Parallel/ProcessTest.php
  tests/Runner/Parallel/WorkerExceptionTest.php
  tests/Runner/RunnerConfigTest.php
  tests/Runner/RunnerTest.php
  tests/Smoke/CiIntegrationTest.php
  tests/Smoke/PharTest.php
  tests/Smoke/StdinTest.php
Labels: topic/I/O, topic/core

#8021 docs: Improve Docker usage example
  README.md
Labels: topic/docker

#8026 fix: Support named args in `ParallelConfigFactory::detect()`
  src/Runner/Parallel/ParallelConfig.php
  src/Runner/Parallel/ParallelConfigFactory.php
  tests/Runner/Parallel/ParallelConfigFactoryTest.php
Labels: topic/parallel

#8044 fix: `PhpUnitSizeClassFixer` - do not add annotation when there are attributes
  src/Fixer/PhpUnit/PhpUnitSizeClassFixer.php
  tests/Fixer/PhpUnit/PhpUnitSizeClassFixerTest.php
Labels: kind/bug

#8004 fix: `ConstantCaseFixer` - do not change namespace
  src/Fixer/Casing/ConstantCaseFixer.php
  tests/Fixer/Casing/ConstantCaseFixerTest.php
Labels: kind/bug

#8042 fix: `PhpUnitTestClassRequiresCoversFixer` - attribute detection when class is `readonly`
  src/Fixer/AbstractPhpUnitFixer.php
  src/Fixer/PhpUnit/PhpUnitTestClassRequiresCoversFixer.php
  tests/Fixer/PhpUnit/PhpUnitTestClassRequiresCoversFixerTest.php
Labels: kind/bug

#8043 fix: `PhpUnitAttributesFixer` - do not add attribute if already present
  src/Fixer/PhpUnit/PhpUnitAttributesFixer.php
  tests/Fixer/PhpUnit/PhpUnitAttributesFixerTest.php
Labels: kind/bug

#8046 feat(GroupImportFixer): Ability to configure which type of imports should be grouped
  doc/rules/import/group_import.rst
  phpstan.dist.neon
  src/Fixer/Import/GroupImportFixer.php
  src/Tokenizer/Analyzer/Analysis/NamespaceUseAnalysis.php
  tests/Fixer/Import/GroupImportFixerTest.php
Labels: kind/feature

#8051 fix: clear `Tokens::$blockStartCache` and `Tokens::$blockEndCache` when calling `Tokens::setCode`
  src/Tokenizer/Tokens.php
  tests/Fixtures/Integration/misc/trailing_comma_in_multiline,binary_operator_spaces.test
Labels: kind/bug

#8054 fix: `PhpUnitTestClassRequiresCoversFixer` - do not add annotation when attribute with leading slash present
  src/Fixer/AbstractPhpUnitFixer.php
  tests/Fixer/PhpUnit/PhpUnitTestClassRequiresCoversFixerTest.php
Labels: kind/bug

#8055 fix: `ConstantCaseFixer` - do not change class constant usages
  src/Fixer/Casing/ConstantCaseFixer.php
  tests/Fixer/Casing/ConstantCaseFixerTest.php
Labels: kind/bug
