Repository PHP-CS-Fixer/PHP-CS-Fixer, pull requests merged in 2024-01, with the labels that each got.

#7654 fix: Handle FQCN properly with `leading_backslash_in_global_namespace` option enabled
  doc/rules/import/fully_qualified_strict_types.rst
  src/Fixer/Import/FullyQualifiedStrictTypesFixer.php
  tests/Fixer/Import/FullyQualifiedStrictTypesFixerTest.php
  tests/Fixtures/Integration/misc/PHP7_1.test
  tests/Fixtures/Integration/misc/PHP7_3.test
  tests/Fixtures/Integration/misc/PHP8_0.test
  tests/Fixtures/Integration/misc/PHP8_2.test
Labels: topic/fqcn

#7648 fix: `fully_qualified_strict_types` with `leading_backslash_in_global_namespace` enabled - handle reserved types in phpDoc
  src/Fixer/Import/FullyQualifiedStrictTypesFixer.php
  tests/Fixer/Import/FullyQualifiedStrictTypesFixerTest.php
  tests/Fixtures/Integration/misc/fully_qualified_strict_types-leading_backslash_in_global_namespace.test
Labels: topic/phpdoc, topic/fqcn

#7660 feat: Introduce `heredoc_closing_marker` fixer
  doc/rules/index.rst
  doc/rules/string_notation/heredoc_closing_marker.rst
  src/DocBlock/TypeExpression.php
  src/Fixer/Import/FullyQualifiedStrictTypesFixer.php
  src/Fixer/StringNotation/HeredocClosingMarkerFixer.php
  tests/Fixer/StringNotation/HeredocClosingMarkerFixerTest.php
Labels: kind/feature

#7659 feat: Support typed properties and attributes in `fully_qualified_strict_types`
  src/Fixer/Import/FullyQualifiedStrictTypesFixer.php
  tests/Fixer/Import/FullyQualifiedStrictTypesFixerTest.php
  tests/Fixtures/Integration/misc/PHP8_0.test
Labels: topic/fqcn, topic/attributes

#7555 feat: Add support for official Docker images of Fixer
  .github/workflows/docker.yml
  Dockerfile
  README.md
  doc/installation.rst
  tests/AutoReview/CiConfigurationTest.php
Labels: kind/feature, topic/ci

#7702 CI: Fix PHP 8.4
  tests/PregTest.php
Labels: topic/ci, BLOCKER

#7663 fix: indentation of control structure body without braces
  src/Fixer/Whitespace/StatementIndentationFixer.php
  tests/Fixer/Whitespace/StatementIndentationFixerTest.php
Labels: kind/bug

#6505 feat: Add `spacing` option to `PhpdocAlignFixer`
  doc/rules/phpdoc/phpdoc_align.rst
  src/Fixer/Phpdoc/PhpdocAlignFixer.php
  tests/Fixer/Phpdoc/PhpdocAlignFixerTest.php
Labels: kind/feature, topic/phpdoc, topic/whitespace

#7716 CI: Give write permissions to Stale Bot
  .github/workflows/issues_and_pull_requests.yml
Labels: topic/ci

#7739 fix: Proper Docker image name suffix
  .github/workflows/docker.yml
Labels: topic/ci

#7749 fix: `FullyQualifiedStrictTypesFixer` - do not modify statements with property fetch and `::`
  src/Fixer/Import/FullyQualifiedStrictTypesFixer.php
  tests/Fixer/Import/FullyQualifiedStrictTypesFixerTest.php
Labels: topic/fqcn

#7750 fix: `FullyQualifiedStrictTypesFixer` - do not change case of the symbol when there's name collision between imported class and imported function
  src/Fixer/Import/FullyQualifiedStrictTypesFixer.php
  tests/Fixer/Import/FullyQualifiedStrictTypesFixerTest.php
Labels: topic/fqcn

#7757 docs: Add PHP-CS-Fixer integration in a GitHub Action step
  doc/installation.rst
Labels: topic/documentation

#7767 fix: `ClassKeywordFixer` must run before `FullyQualifiedStrictTypesFixer`
  src/Fixer/Import/FullyQualifiedStrictTypesFixer.php
  src/Fixer/LanguageConstruct/ClassKeywordFixer.php
  tests/AutoReview/FixerFactoryTest.php
  tests/Fixtures/Integration/priority/class_keyword,fully_qualified_strict_types.test
Labels: topic/priority, topic/fqcn

#7769 fix: Allow using cache when running in Docker distribution
  doc/usage.rst
  src/Console/ConfigurationResolver.php
  src/ToolInfo.php
  src/ToolInfoInterface.php
  tests/Console/Command/SelfUpdateCommandTest.php
  tests/Console/ConfigurationResolverTest.php
  tests/Console/WarningsDetectorTest.php
Labels: kind/bug, topic/docker

#7788 chore: Exclude `topic/core` issues/PRs from Stale Bot
  .github/workflows/issues_and_pull_requests.yml
Labels: kind/enhancement
