Repository PHP-CS-Fixer/PHP-CS-Fixer, pull requests merged in 2024-08, with the labels that each got.

#8160 chore: remove `beStrictAboutTodoAnnotatedTests` from PHPUnit's config
  phpunit.xml.dist
Labels: topic/ci

#7705 fix: Do not shorten FQN for class resolution if imported symbol is not a class
  .github/workflows/ci.yml
  .php-cs-fixer.php-highest.php
  dev-tools/phpstan/baseline.php
  phpstan.dist.neon
  src/Fixer/Import/FullyQualifiedStrictTypesFixer.php
  src/Tokenizer/Analyzer/Analysis/NamespaceUseAnalysis.php
  src/Tokenizer/Analyzer/NamespaceUsesAnalyzer.php
  tests/Fixer/Import/FullyQualifiedStrictTypesFixerTest.php
Labels: topic/fqcn

#8145 chore: remove/update duplicates from data providers that are copies in code
  tests/AutoReview/ProjectCodeTest.php
  tests/Console/Command/SelfUpdateCommandTest.php
  tests/Console/Output/Progress/DotsOutputTest.php
  tests/DocBlock/TypeExpressionTest.php
  tests/Fixer/ArrayNotation/ArraySyntaxFixerTest.php
  tests/Fixer/ArrayNotation/TrimArraySpacesFixerTest.php
  tests/Fixer/Basic/BracesFixerTest.php
  tests/Fixer/Basic/BracesPositionFixerTest.php
  tests/Fixer/Basic/CurlyBracesPositionFixerTest.php
  tests/Fixer/ClassNotation/FinalClassFixerTest.php
  tests/Fixer/ConstantNotation/NativeConstantInvocationFixerTest.php
  tests/Fixer/ControlStructure/NoBreakCommentFixerTest.php
  tests/Fixer/ControlStructure/YodaStyleFixerTest.php
  tests/Fixer/FunctionNotation/PhpdocToParamTypeFixerTest.php
  tests/Fixer/Import/OrderedImportsFixerTest.php
  tests/Fixer/LanguageConstruct/SingleSpaceAfterConstructFixerTest.php
  tests/Fixer/LanguageConstruct/SingleSpaceAroundConstructFixerTest.php
  tests/Fixer/Operator/StandardizeIncrementFixerTest.php
  tests/Fixer/PhpUnit/PhpUnitTargetVersionTest.php
  tests/Fixer/Phpdoc/PhpdocInlineTagNormalizerFixerTest.php
  tests/Fixer/Phpdoc/PhpdocTypesOrderFixerTest.php
  tests/Fixer/StringNotation/SingleQuoteFixerTest.php
  tests/Fixer/Whitespace/MethodChainingIndentationFixerTest.php
  tests/Fixer/Whitespace/SpacesInsideParenthesesFixerTest.php
  tests/FixerNameValidatorTest.php
  tests/Tokenizer/Analyzer/AlternativeSyntaxAnalyzerTest.php
  tests/Tokenizer/Analyzer/AttributeAnalyzerTest.php
  tests/Tokenizer/Analyzer/ClassyAnalyzerTest.php
  tests/Tokenizer/Analyzer/FunctionsAnalyzerTest.php
  tests/Tokenizer/TokensAnalyzerTest.php
  tests/Tokenizer/Transformer/ReturnRefTransformerTest.php
Labels: topic/tests

#8164 chore: remove duplicates from data providers
  tests/AbstractDoctrineAnnotationFixerTestCase.php
  tests/AutoReview/ProjectCodeTest.php
  tests/Fixer/Basic/PsrAutoloadingFixerTest.php
  tests/Fixer/CastNotation/LowercaseCastFixerTest.php
  tests/Fixer/Comment/NoEmptyCommentFixerTest.php
  tests/Fixer/ControlStructure/NoUnneededControlParenthesesFixerTest.php
  tests/Fixer/ControlStructure/NoUselessElseFixerTest.php
  tests/Fixer/DoctrineAnnotation/DoctrineAnnotationArrayAssignmentFixerTest.php
  tests/Fixer/DoctrineAnnotation/DoctrineAnnotationIndentationFixerTest.php
  tests/Fixer/DoctrineAnnotation/DoctrineAnnotationSpacesFixerTest.php
  tests/Fixer/PhpUnit/PhpUnitStrictFixerTest.php
  tests/Tokenizer/TokenTest.php
Labels: topic/tests

#8156 feat: `SingleImportPerStatementFixer` - remove braces for single import
  src/Fixer/Import/SingleImportPerStatementFixer.php
  tests/Fixer/Import/SingleImportPerStatementFixerTest.php
Labels: kind/enhancement

#8176 chore: add `@return` tags for data providers already having PHPDoc
  phpstan.dist.neon
  tests/Fixer/Whitespace/BlankLineBeforeStatementFixerTest.php
  tests/Tokenizer/Analyzer/AttributeAnalyzerTest.php
Labels: topic/tests

#8178 chore: add tags for data providers that changes PHPStan's baseline
  dev-tools/phpstan/baseline.php
  phpstan.dist.neon
  tests/Fixer/Operator/IncrementStyleFixerTest.php
  tests/Fixer/Whitespace/LineEndingFixerTest.php
Labels: topic/tests

#8172 feat: Add `array_destructuring` as option for `trailing_comma_in_multiline`
  doc/rules/control_structure/trailing_comma_in_multiline.rst
  doc/rules/index.rst
  src/Fixer/ControlStructure/TrailingCommaInMultilineFixer.php
  tests/Fixer/ControlStructure/TrailingCommaInMultilineFixerTest.php
Labels: kind/feature

#8183 fix: `FullyQualifiedStrictTypesFixer` - reset cache even if there is no `use`
  src/Fixer/Import/FullyQualifiedStrictTypesFixer.php
  tests/Fixer/Import/FullyQualifiedStrictTypesFixerTest.php
Labels: kind/bug
