Repository PHP-CS-Fixer/PHP-CS-Fixer, pull requests merged in 2024-06, with the labels that each got.

#8061 DX: Remove version from Docker Compose files
  compose.override.dist.yaml
  compose.yaml
Labels: kind/enhancement, topic/docker

#8062 fix: Look up for PHPDoc's variable name by only chars allowed in the variables
  phpstan.dist.neon
  src/DocBlock/Annotation.php
  tests/DocBlock/AnnotationTest.php
  tests/Fixer/Phpdoc/NoSuperfluousPhpdocTagsFixerTest.php
Labels: kind/bug, topic/phpdoc

#8008 fix: `native_constant_invocation` - array constants with native constant names
  src/Tokenizer/TokensAnalyzer.php
  tests/Fixer/ConstantNotation/NativeConstantInvocationFixerTest.php
  tests/Tokenizer/TokensAnalyzerTest.php
Labels: kind/bug

#8064 feat: `SimpleToComplexStringVariableFixer` - support variable being an array
  src/Fixer/StringNotation/SimpleToComplexStringVariableFixer.php
  src/Tokenizer/Tokens.php
  tests/Fixer/StringNotation/SimpleToComplexStringVariableFixerTest.php
  tests/Tokenizer/TokensTest.php
Labels: kind/feature

#8065 docs: Make wording in `final_class` docs less dismissive
  doc/rules/class_notation/final_class.rst
  src/Fixer/ClassNotation/FinalClassFixer.php
Labels: topic/documentation

#8073 fix: Update `PhpUnitTestCaseStaticMethodCallsFixer::STATIC_METHODS`
  src/Fixer/PhpUnit/PhpUnitTestCaseStaticMethodCallsFixer.php
  tests/Fixer/PhpUnit/PhpUnitTestCaseStaticMethodCallsFixerTest.php
Labels: topic/phpunit, topic/ci

#8074 CI: Update PHPStan to 1.11.4
  dev-tools/composer.json
  dev-tools/composer.lock
  dev-tools/phpstan/baseline.php
Labels: topic/ci

#8068 fix: Bump React's JSON decoder buffer size
  src/Runner/Runner.php
Labels: kind/enhancement, topic/parallel

#8075 fix: `PhpUnitAttributesFixer` - handle multiple annotations of the same name
  phpstan.dist.neon
  src/Fixer/PhpUnit/PhpUnitAttributesFixer.php
  tests/Fixer/PhpUnit/PhpUnitAttributesFixerTest.php
Labels: kind/bug

#8090 feat: `PhpUnitAttributesFixer` - add option to keep annotations
  doc/rules/php_unit/php_unit_attributes.rst
  src/Fixer/PhpUnit/PhpUnitAttributesFixer.php
  tests/Fixer/PhpUnit/PhpUnitAttributesFixerTest.php
Labels: kind/feature
