Repository PHP-CS-Fixer/PHP-CS-Fixer, pull requests merged in 2024-11, with the labels that each got.

#8265 chore: remove not needed PHP version requirements in descriptions
  doc/rules/function_notation/combine_nested_dirname.rst
  doc/rules/function_notation/phpdoc_to_param_type.rst
  doc/rules/function_notation/phpdoc_to_property_type.rst
  doc/rules/function_notation/void_return.rst
  doc/rules/index.rst
  doc/rules/language_construct/explicit_indirect_variable.rst
  doc/rules/list_notation/list_syntax.rst
  doc/rules/operator/ternary_to_null_coalescing.rst
  doc/rules/strict/declare_strict_types.rst
  src/Fixer/FunctionNotation/CombineNestedDirnameFixer.php
  src/Fixer/FunctionNotation/PhpdocToParamTypeFixer.php
  src/Fixer/FunctionNotation/PhpdocToPropertyTypeFixer.php
  src/Fixer/FunctionNotation/VoidReturnFixer.php
  src/Fixer/LanguageConstruct/ExplicitIndirectVariableFixer.php
  src/Fixer/ListNotation/ListSyntaxFixer.php
  src/Fixer/Operator/TernaryToNullCoalescingFixer.php
  src/Fixer/Strict/DeclareStrictTypesFixer.php
Labels: topic/documentation

#8276 refactor: Runner - Enhance eventing system
  src/Console/Command/FixCommand.php
  src/Console/Command/WorkerCommand.php
  src/Console/Output/Progress/DotsOutput.php
  src/Console/Output/Progress/NullOutput.php
  src/Console/Output/Progress/PercentageBarOutput.php
  src/Console/Output/Progress/ProgressOutputInterface.php
  src/Runner/Event/AnalysisStarted.php
  src/Runner/Event/FileProcessed.php
  src/Runner/FileFilterIterator.php
  src/Runner/Runner.php
  tests/Console/Command/WorkerCommandTest.php
  tests/Console/Output/Progress/DotsOutputTest.php
  tests/Console/Output/Progress/PercentageBarOutputTest.php
  tests/Runner/Event/AnalysisStartedTest.php
  tests/Runner/Event/FileProcessedTest.php
  tests/Runner/FileFilterIteratorTest.php
Labels: kind/enhancement

#8256 fix: `BlankLineAfterOpeningTagFixer` - add blank line in file starting with multi-line comment
  src/Fixer/PhpTag/BlankLineAfterOpeningTagFixer.php
  tests/Fixer/PhpTag/BlankLineAfterOpeningTagFixerTest.php
Labels: kind/bug

#8268 fix: Do not mark with `@coversNothing` if `CoversMethod`/`CoversFunction` attribute is used
  src/Fixer/PhpUnit/PhpUnitTestClassRequiresCoversFixer.php
  tests/Fixer/PhpUnit/PhpUnitTestClassRequiresCoversFixerTest.php
Labels: topic/phpunit

#8277 feat: create `@PHP82Migration:risky` ruleset
  .php-cs-fixer.php-highest.php
  doc/ruleSets/PHP82MigrationRisky.rst
  doc/ruleSets/index.rst
  doc/rules/alias/modernize_strpos.rst
  doc/rules/alias/no_alias_functions.rst
  doc/rules/alias/pow_to_exponentiation.rst
  doc/rules/alias/random_api_migration.rst
  doc/rules/basic/non_printable_character.rst
  doc/rules/class_notation/no_php4_constructor.rst
  doc/rules/class_notation/no_unneeded_final_method.rst
  doc/rules/class_notation/phpdoc_readonly_class_comment_to_keyword.rst
  doc/rules/function_notation/combine_nested_dirname.rst
  doc/rules/function_notation/implode_call.rst
  doc/rules/function_notation/no_unreachable_default_argument_value.rst
  doc/rules/function_notation/use_arrow_functions.rst
  doc/rules/function_notation/void_return.rst
  doc/rules/language_construct/get_class_to_class_keyword.rst
  doc/rules/strict/declare_strict_types.rst
  src/RuleSet/Sets/PHP82MigrationRiskySet.php
  tests/RuleSet/Sets/PHP82MigrationRiskySetTest.php
Labels: kind/feature

#8264 chore: do not use `Reflection*::setAccessible`
  dev-tools/phpstan/baseline.php
  tests/AutoReview/ProjectCodeTest.php
  tests/AutoReview/TransformerTest.php
  tests/Fixer/Alias/NoMixedEchoPrintFixerTest.php
  tests/Fixer/Alias/RandomApiMigrationFixerTest.php
  tests/Fixer/Casing/MagicMethodCasingFixerTest.php
  tests/Fixer/ClassNotation/ClassAttributesSeparationFixerTest.php
  tests/Fixer/ClassNotation/ClassDefinitionFixerTest.php
  tests/Fixer/Comment/NoEmptyCommentFixerTest.php
  tests/Fixer/ControlStructure/NoUselessElseFixerTest.php
  tests/FixerFactoryTest.php
  tests/Runner/Parallel/ParallelConfigFactoryTest.php
  tests/Runner/Parallel/ProcessFactoryTest.php
  tests/Tokenizer/Transformer/SquareBraceTransformerTest.php
Labels: topic/tests

#8293 refactor: Rename newly introduced option
  .php-cs-fixer.php-highest.php
  doc/rules/function_notation/phpdoc_to_param_type.rst
  doc/rules/function_notation/phpdoc_to_property_type.rst
  doc/rules/function_notation/phpdoc_to_return_type.rst
  src/AbstractPhpdocToTypeDeclarationFixer.php
  src/Fixer/FunctionNotation/PhpdocToParamTypeFixer.php
  src/Fixer/FunctionNotation/PhpdocToPropertyTypeFixer.php
  src/Fixer/FunctionNotation/PhpdocToReturnTypeFixer.php
  tests/Fixtures/Integration/priority/phpdoc_to_property_type,fully_qualified_strict_types.test
Labels: kind/enhancement

#8280 feat: Ability to set upper limit when using CPU auto-detection
  composer.json
  src/Runner/Parallel/ParallelConfigFactory.php
  tests/Runner/Parallel/ParallelConfigFactoryTest.php
Labels: topic/parallel

#8311 feat: `UseArrowFunctionsFixer` - support multiline statements
  doc/rules/function_notation/use_arrow_functions.rst
  doc/rules/index.rst
  src/Fixer/FunctionNotation/UseArrowFunctionsFixer.php
  tests/Fixer/FunctionNotation/UseArrowFunctionsFixerTest.php
Labels: kind/feature
