Repository PHP-CS-Fixer/PHP-CS-Fixer, pull requests merged in 2024-04, with the labels that each got.

#7916 feat: Add trailing comma in multiline to PER-CS 2.0
  doc/ruleSets/PER-CS2.0.rst
  doc/rules/control_structure/trailing_comma_in_multiline.rst
  src/RuleSet/Sets/PERCS2x0Set.php
  tests/Fixtures/Integration/set/@PER-CS2.0.test-in.php
  tests/Fixtures/Integration/set/@PER-CS2.0.test-out.php
  tests/Fixtures/Integration/set/@PER-CS2.0_php80.test
  tests/Fixtures/Integration/set/@PER-CS2.0_php80.test-in.php
  tests/Fixtures/Integration/set/@PER-CS2.0_php80.test-out.php
Labels: kind/feature

#7937 fix: Remove Infection during Docker release
  Dockerfile
Labels: topic/docker

#7935 test: Ignore PHP version related mutations
  infection.json5.dist
Labels: topic/tests

#7936 chore: Properly determine self-approval trigger commit
  .github/workflows/self-approval.yml
Labels: topic/ci

#7831 feat: introduce `PhpUnitAttributesFixer`
  .php-cs-fixer.php-highest.php
  doc/rules/index.rst
  doc/rules/php_unit/php_unit_attributes.rst
  src/Fixer/AbstractPhpUnitFixer.php
  src/Fixer/Import/FullyQualifiedStrictTypesFixer.php
  src/Fixer/PhpUnit/PhpUnitAttributesFixer.php
  src/Fixer/Phpdoc/PhpdocSeparationFixer.php
  src/Fixer/Phpdoc/PhpdocTrimConsecutiveBlankLineSeparationFixer.php
  src/Fixer/Phpdoc/PhpdocTrimFixer.php
  tests/AutoReview/FixerFactoryTest.php
  tests/Fixer/PhpUnit/PhpUnitAttributesFixerTest.php
  tests/Fixtures/Integration/priority/php_unit_attributes,fully_qualified_strict_types.test
  tests/Fixtures/Integration/priority/php_unit_attributes,phpdoc_separation.test
  tests/Fixtures/Integration/priority/php_unit_attributes,phpdoc_trim.test
  tests/Fixtures/Integration/priority/php_unit_attributes,phpdoc_trim_consecutive_blank_line_separation.test
  tests/Linter/AbstractLinterTestCase.php
  tests/Test/AbstractIntegrationTestCase.php
Labels: kind/feature, topic/phpdoc, topic/phpunit, topic/attributes

#7880 fix: `PhpUnitTestClassRequiresCoversFixer` - do not add annotation when there are attributes
  src/Fixer/AbstractPhpUnitFixer.php
  src/Fixer/PhpUnit/PhpUnitInternalClassFixer.php
  src/Fixer/PhpUnit/PhpUnitSizeClassFixer.php
  src/Fixer/PhpUnit/PhpUnitTestClassRequiresCoversFixer.php
  tests/Fixer/PhpUnit/PhpUnitTestClassRequiresCoversFixerTest.php
Labels: kind/bug

#7955 fix: `FullyQualifiedStrictTypesFixer` - do not add imports before PHP opening tag
  src/Tokenizer/Analyzer/NamespacesAnalyzer.php
  tests/Fixer/Import/FullyQualifiedStrictTypesFixerTest.php
  tests/Tokenizer/Analyzer/NamespacesAnalyzerTest.php
Labels: kind/bug

#7952 DX: Improve internal dist config for Fixer
  .php-cs-fixer.dist.php
Labels: kind/refactoring

#7967 DX: Prevent having deprecated fixers listed as successors of other deprecated fixers
  doc/rules/basic/braces.rst
  src/Fixer/Basic/BracesFixer.php
  tests/RuleSet/RuleSetTest.php
  tests/RuleSet/RuleSetsTest.php
  tests/Test/AbstractFixerTestCase.php
  tests/Test/TestCaseUtils.php
Labels: topic/tests

#7970 CI: Ad-hoc fix for MacOS jobs
  .github/workflows/ci.yml
Labels: topic/ci, BLOCKER

#7395 feat: Introduce `OrderedAttributesFixer`
  doc/rules/attribute_notation/ordered_attributes.rst
  doc/rules/index.rst
  src/Fixer/AttributeNotation/OrderedAttributesFixer.php
  src/Fixer/Import/FullyQualifiedStrictTypesFixer.php
  tests/AutoReview/FixerFactoryTest.php
  tests/Fixer/AttributeNotation/OrderedAttributesFixerTest.php
  tests/Fixer/Import/FullyQualifiedStrictTypesFixerTest.php
  tests/Fixtures/Integration/priority/fully_qualified_strict_types,ordered_attributes.test
Labels: kind/feature

#7971 DX: Resolve/Ignore PHPStan issues on level 6 + bump to level 7 with new baseline
  dev-tools/phpstan/baseline.php
  phpstan.dist.neon
  src/Console/ConfigurationResolver.php
  src/Doctrine/Annotation/Tokens.php
  src/Fixer/Alias/NoMixedEchoPrintFixer.php
  src/Fixer/ArrayNotation/ArraySyntaxFixer.php
  src/Fixer/LanguageConstruct/DeclareEqualNormalizeFixer.php
  src/Fixer/Operator/ConcatSpaceFixer.php
  src/Fixer/PhpUnit/PhpUnitConstructFixer.php
  src/Fixer/Phpdoc/PhpdocTrimConsecutiveBlankLineSeparationFixer.php
  src/Fixer/Whitespace/NoExtraBlankLinesFixer.php
  src/StdinFileInfo.php
  tests/DocBlock/TypeExpressionTest.php
Labels: kind/refactoring
