Repository PHP-CS-Fixer/PHP-CS-Fixer, pull requests merged in 2025-09, with the labels that each got.

#9011 chore: `PhpUnitDedicateAssertFixer` - improve code for phpstan
  dev-tools/phpstan/baseline/method.nonObject.php
  src/Fixer/PhpUnit/PhpUnitDedicateAssertFixer.php
Labels: status/self-approved

#9052 CI: fix typos in `CHANGELOG.md`
  CHANGELOG.md
  dev-tools/typos.toml
Labels: topic/ci

#9069 test: extend tests to cover new migration rule set names
  src/RuleSet/AbstractMigrationSetDescription.php
  tests/RuleSet/AbstractMigrationSetDescriptionTest.php
Labels: status/self-approved

#9076 test: ensure alpine version same between Dockerfile and compose.yaml
  tests/AutoReview/CiConfigurationTest.php
Labels: status/self-approved

#9078 deps: upgrade alpine wherever possible
  .github/workflows/release.yml
  compose.yaml
Labels: status/self-approved

#9067 refactor: introduce concept of AutomaticRuleSet
  composer.json
  dev-tools/php-compatibility/phpcs-php-compatibility.xml
  dev-tools/phpstan/baseline/_loader.php
  dev-tools/phpstan/baseline/shipmonk.deadMethod.php
  dev-tools/phpstan/baseline/trait.unused.php
  src/ComposerJsonReader.php
  src/ConfigurationException/UnresolvableAutoRuleSetConfigurationException.php
  src/Console/Command/DescribeCommand.php
  src/Documentation/FixerDocumentGenerator.php
  src/Documentation/RuleSetDocumentationGenerator.php
  src/RuleSet/AbstractMigrationSetDescription.php
  src/RuleSet/AutomaticMigrationSetTrait.php
  src/RuleSet/AutomaticRuleSetDescriptionInterface.php
  tests/ComposerJsonReaderTest.php
  tests/ConfigurationException/UnresolvableAutoRuleSetConfigurationExceptionTest.php
  tests/RuleSet/AbstractMigrationSetDescriptionTest.php
  tests/RuleSet/RuleSetsTest.php
Labels: status/self-approved

#9057 chore: `getcwd()` - ignore `false` return value
  dev-tools/phpstan/baseline/argument.type.php
  src/Console/Command/DescribeCommand.php
  src/Console/Command/FixCommand.php
  src/Console/Command/ListFilesCommand.php
  src/Console/Command/WorkerCommand.php
Labels: status/self-approved

#9089 CI: Test docs generation only once per CI pipeline
  phpunit.xml.dist
  tests/Console/Command/DocumentationCommandTest.php
Labels: kind/enhancement, topic/ci

#9090 feat: introduce `@auto`, `@auto:risky` sets
  .php-cs-fixer.dist.php
  doc/ruleSets/Auto.rst
  doc/ruleSets/AutoRisky.rst
  doc/ruleSets/index.rst
  src/Config.php
  src/RuleSet/Sets/AutoRiskySet.php
  src/RuleSet/Sets/AutoSet.php
  tests/RuleSet/Sets/AutoRiskySetTest.php
  tests/RuleSet/Sets/AutoSetTest.php
Labels: status/self-approved

#6083 feat: Support custom rulesets
  doc/config.rst
  phpstan.dist.neon
  src/Config.php
  src/Console/Command/DocumentationCommand.php
  src/Console/ConfigurationResolver.php
  src/CustomRulesetsAwareConfigInterface.php
  src/RuleSet/RuleSetDescriptionInterface.php
  src/RuleSet/RuleSets.php
  src/RuleSetNameValidator.php
  tests/AutoReview/DocumentationTest.php
  tests/ConfigTest.php
  tests/Console/ConfigurationResolverTest.php
  tests/Fixtures/ExternalRuleSet/ExampleRuleset.php
  tests/RuleSet/RuleSetTest.php
  tests/RuleSet/RuleSetsTest.php
  tests/RuleSetNameValidatorTest.php
Labels: kind/feature

#9106 deps: use `shipmonk/composer-dependency-analyser` instead of `icanhazstring/composer-unused` and `maglnet/composer-require-checker`
  .composer-require-checker.json
  .github/workflows/sca.yml
  composer-dependency-analyser.php
  composer.json
  dev-tools/composer.json
  dev-tools/composer.lock
Labels: dependencies
