Repository PHP-CS-Fixer/PHP-CS-Fixer, pull requests merged in 2025-03, with the labels that each got.

#8466 fix: `MbStrFunctionsFixer` must run before `NativeFunctionInvocationFixer`
  src/Fixer/Alias/MbStrFunctionsFixer.php
  src/Fixer/FunctionNotation/NativeFunctionInvocationFixer.php
  tests/AutoReview/FixerFactoryTest.php
  tests/Fixtures/Integration/priority/mb_str_functions,native_function_invocation.test
Labels: kind/bug

#8469 fix: `MethodArgumentSpaceFixer` - fix nested calls for `ensure_fully_multiline` option
  src/Fixer/FunctionNotation/MethodArgumentSpaceFixer.php
  tests/Fixer/FunctionNotation/MethodArgumentSpaceFixerTest.php
Labels: kind/bug

#8048 refactor: add `FullyQualifiedNameAnalyzer`
  src/Fixer/AbstractPhpUnitFixer.php
  src/Fixer/AttributeNotation/OrderedAttributesFixer.php
  src/Fixer/PhpUnit/PhpUnitAttributesFixer.php
  src/Tokenizer/Analyzer/FullyQualifiedNameAnalyzer.php
  tests/Tokenizer/Analyzer/FullyQualifiedNameAnalyzerTest.php
Labels: kind/refactoring, topic/fqcn

#8476 DX: cleanup `PhpdocNoAliasTagFixerTest`
  tests/Fixer/Phpdoc/PhpdocNoAliasTagFixerTest.php
  tests/Test/AbstractFixerTestCase.php
Labels: kind/cleanup

#8317 fix: `SingleSpaceAroundConstructFixer` - handle alternative syntax
  src/Fixer/LanguageConstruct/SingleSpaceAroundConstructFixer.php
  tests/Fixer/LanguageConstruct/SingleSpaceAroundConstructFixerTest.php
Labels: kind/bug

#8486 fix: `PhpdocAlignFixer` - align correctly type with UTF8 characters
  src/Fixer/Phpdoc/PhpdocAlignFixer.php
  tests/Fixer/Phpdoc/PhpdocAlignFixerTest.php
Labels: kind/bug

#8484 fix: `BinaryOperatorSpacesFixer` - do not break alignment of UTF-8 array keys
  dev-tools/phpstan/baseline.php
  src/Fixer/Operator/BinaryOperatorSpacesFixer.php
  tests/Fixer/Operator/BinaryOperatorSpacesFixerTest.php
Labels: kind/bug

#8474 fix: `MbStrFunctionsFixer` - fix imports
  src/Fixer/Alias/MbStrFunctionsFixer.php
  tests/Fixer/Alias/MbStrFunctionsFixerTest.php
Labels: kind/bug

#8480 fix: `TrailingCommaInMultilineFixer` - handle empty match body
  src/Fixer/ControlStructure/TrailingCommaInMultilineFixer.php
  tests/Fixer/ControlStructure/TrailingCommaInMultilineFixerTest.php
Labels: kind/bug

#8492 feat: `StatementIndentationFixer` - handle property hooks
  src/Fixer/Whitespace/StatementIndentationFixer.php
  tests/Fixer/Whitespace/StatementIndentationFixerTest.php
Labels: kind/feature

#8495 fix: `VisibilityRequiredFixer` - handle property hooks
  src/Tokenizer/TokensAnalyzer.php
  tests/Fixer/ClassNotation/VisibilityRequiredFixerTest.php
  tests/Tokenizer/TokensAnalyzerTest.php
Labels: kind/bug

#8503 fix: `MethodArgumentSpaceFixer` - handle when nested in HTML
  src/Fixer/FunctionNotation/MethodArgumentSpaceFixer.php
  tests/Fixer/FunctionNotation/MethodArgumentSpaceFixerTest.php
  tests/Fixtures/Integration/misc/method_argument_space,statement_indentation.test
Labels: kind/bug

#8448 test: run code coverage on PHP 8.4
  .github/workflows/ci.yml
Labels: topic/tests

#8504 refactor: `TokensAnalyzerTest` - better test `isArray` and `isArrayMultiLine`
  phpstan.dist.neon
  tests/Tokenizer/TokensAnalyzerTest.php
Labels: kind/refactoring

#8505 DX: cleanup `NoExtraBlankLinesFixerTest`
  phpstan.dist.neon
  tests/Fixer/CastNotation/LowercaseCastFixerTest.php
  tests/Fixer/CastNotation/ShortScalarCastFixerTest.php
  tests/Fixer/Whitespace/NoExtraBlankLinesFixerTest.php
  tests/Test/AbstractFixerTestCase.php
Labels: kind/cleanup

#8506 DX: remove more duplicated test methods
  phpstan.dist.neon
  tests/AutoReview/DuplicatesTestsTest.php
  tests/AutoReview/ProjectCodeTest.php
  tests/Fixer/AttributeNotation/AttributeEmptyParenthesesFixerTest.php
  tests/Fixer/AttributeNotation/OrderedAttributesFixerTest.php
  tests/Fixer/ClassNotation/OrderedTypesFixerTest.php
  tests/Tokenizer/TokensAnalyzerTest.php
  tests/Tokenizer/Transformer/BraceTransformerTest.php
  tests/Tokenizer/Transformer/NullableTypeTransformerTest.php
  tests/Tokenizer/Transformer/SquareBraceTransformerTest.php
  tests/Tokenizer/Transformer/TypeColonTransformerTest.php
Labels: kind/cleanup, topic/tests

#8508 DX: for duplicated test methods check methods without parameters
  phpstan.dist.neon
  tests/AutoReview/DuplicatedTestsTest.php
  tests/Fixer/PhpUnit/PhpUnitExpectationFixerTest.php
  tests/Fixer/PhpUnit/PhpUnitMockFixerTest.php
Labels: kind/cleanup, topic/tests

#8415 feat: add support for asymmetric visibility to Doctrine's fixers
  src/AbstractDoctrineAnnotationFixer.php
  tests/Fixer/DoctrineAnnotation/DoctrineAnnotationArrayAssignmentFixerTest.php
Labels: kind/feature, topic/PHP8.4

#8519 chore: update `checkbashisms` to 2.25.5
  dev-tools/install.sh
Labels: topic/ci

#8517 fix: `OrderedClassElementsFixer` - do not crash on property hook
  src/Fixer/ClassNotation/OrderedClassElementsFixer.php
  tests/Fixer/ClassNotation/OrderedClassElementsFixerTest.php
Labels: kind/bug, topic/PHP8.4

#8520 CI: fix code coverage job
  .gitignore
  phpunit.xml.dist
Labels: topic/ci

#8496 fix: `BracesPositionFixer` - do not create two consecutive whitespace tokens
  src/Fixer/Basic/BracesPositionFixer.php
  tests/Fixer/Basic/BracesPositionFixerTest.php
Labels: kind/bug

#8463 fix: `PhpUnitMethodCasingFixer` - do not touch anonymous class
  src/Fixer/AbstractPhpUnitFixer.php
  tests/Fixer/PhpUnit/PhpUnitMethodCasingFixerTest.php
Labels: kind/bug

#8510 fix: `PhpUnitAttributesFixer` - handle parentheses after data provider method name
  src/Fixer/PhpUnit/PhpUnitAttributesFixer.php
  tests/Fixer/PhpUnit/PhpUnitAttributesFixerTest.php
Labels: kind/bug, topic/phpunit, topic/attributes

#8530 chore: update return type of `FixerOptionInterface::getAllowedValues`
  src/FixerConfiguration/AliasedFixerOptionBuilder.php
  src/FixerConfiguration/FixerOption.php
  src/FixerConfiguration/FixerOptionBuilder.php
  src/FixerConfiguration/FixerOptionInterface.php
  tests/Console/Command/HelpCommandTest.php
  tests/FixerConfiguration/AliasedFixerOptionTest.php
  tests/RuleSet/RuleSetsTest.php
Labels: kind/cleanup

#8531 deps: update PHPStan
  dev-tools/composer.json
  dev-tools/composer.lock
  dev-tools/phpstan/baseline.php
Labels: dependencies

#8529 chore: make options that have default and allowed sets the same size the same array
  doc/rules/basic/no_trailing_comma_in_singleline.rst
  doc/rules/class_notation/visibility_required.rst
  doc/rules/php_unit/php_unit_construct.rst
  doc/rules/phpdoc/phpdoc_types.rst
  src/Fixer/Basic/NoTrailingCommaInSinglelineFixer.php
  src/Fixer/ClassNotation/VisibilityRequiredFixer.php
  src/Fixer/PhpUnit/PhpUnitConstructFixer.php
  src/Fixer/Phpdoc/PhpdocTypesFixer.php
  tests/Test/AbstractFixerTestCase.php
Labels: kind/enhancement

#8507 fix: `MbStrFunctionsFixer` - fix imports with leading backslash
  src/Fixer/Alias/MbStrFunctionsFixer.php
  tests/Fixer/Alias/MbStrFunctionsFixerTest.php
Labels: kind/bug

#8483 fix: `OrderedImportsFixer` - fix syntax error with grouped use statement and multiple use with comma
  src/Fixer/Import/OrderedImportsFixer.php
  tests/Fixer/Import/OrderedImportsFixerTest.php
Labels: kind/bug

#8459 fix: `OrderedImportsFixer` - do not take the braces part in grouped imports into account
  src/Fixer/Import/OrderedImportsFixer.php
  tests/Fixer/Import/OrderedImportsFixerTest.php
Labels: kind/bug

#8512 fix: `NoUnreachableDefaultArgumentValueFixer` - do not crash on property hook
  src/Fixer/FunctionNotation/NoUnreachableDefaultArgumentValueFixer.php
  tests/Fixer/FunctionNotation/NoUnreachableDefaultArgumentValueFixerTest.php
Labels: kind/bug, topic/PHP8.4

#8539 chore: `FunctionsAnalyzerTest` cleanup
  phpstan.dist.neon
  tests/Tokenizer/Analyzer/FunctionsAnalyzerTest.php
Labels: kind/cleanup

#8543 chore: add return types for data providers for non-fixers
  phpstan.dist.neon
  tests/AbstractFunctionReferenceFixerTest.php
  tests/AutoReview/DescribeCommandTest.php
  tests/AutoReview/FixerFactoryTest.php
  tests/Cache/CacheTest.php
  tests/ConfigTest.php
  tests/Console/Command/HelpCommandTest.php
  tests/Console/Command/SelfUpdateCommandTest.php
  tests/Console/ConfigurationResolverTest.php
  tests/Console/Output/Progress/DotsOutputTest.php
  tests/DocBlock/AnnotationTest.php
  tests/DocBlock/TagComparatorTest.php
  tests/DocBlock/TypeExpressionTest.php
  tests/Doctrine/Annotation/TokenTest.php
  tests/FixerConfiguration/AliasedFixerOptionTest.php
  tests/FixerConfiguration/AllowedValueSubsetTest.php
  tests/Indicator/PhpUnitTestCaseIndicatorTest.php
  tests/RuleSet/RuleSetTest.php
  tests/Smoke/CiIntegrationTest.php
  tests/Tokenizer/Analyzer/AlternativeSyntaxAnalyzerTest.php
  tests/Tokenizer/Analyzer/ArgumentsAnalyzerTest.php
  tests/Tokenizer/Analyzer/ClassyAnalyzerTest.php
  tests/Tokenizer/Analyzer/CommentsAnalyzerTest.php
  tests/Tokenizer/Analyzer/ControlCaseStructuresAnalyzerTest.php
  tests/Tokenizer/Analyzer/NamespacesAnalyzerTest.php
  tests/Tokenizer/Analyzer/RangeAnalyzerTest.php
  tests/Tokenizer/TokenTest.php
  tests/Tokenizer/TokensAnalyzerTest.php
  tests/Tokenizer/TokensTest.php
  tests/Tokenizer/Transformer/ArrayTypehintTransformerTest.php
  tests/Tokenizer/Transformer/AttributeTransformerTest.php
  tests/Tokenizer/Transformer/BraceClassInstantiationTransformerTest.php
  tests/Tokenizer/Transformer/BraceTransformerTest.php
  tests/Tokenizer/Transformer/ClassConstantTransformerTest.php
  tests/Tokenizer/Transformer/ConstructorPromotionTransformerTest.php
  tests/Tokenizer/Transformer/DisjunctiveNormalFormTypeParenthesisTransformerTest.php
  tests/Tokenizer/Transformer/FirstClassCallableTransformerTest.php
  tests/Tokenizer/Transformer/ImportTransformerTest.php
  tests/Tokenizer/Transformer/NameQualifiedTransformerTest.php
  tests/Tokenizer/Transformer/NamedArgumentTransformerTest.php
  tests/Tokenizer/Transformer/NamespaceOperatorTransformerTest.php
  tests/Tokenizer/Transformer/NullableTypeTransformerTest.php
  tests/Tokenizer/Transformer/ReturnRefTransformerTest.php
  tests/Tokenizer/Transformer/SquareBraceTransformerTest.php
  tests/Tokenizer/Transformer/TypeAlternationTransformerTest.php
  tests/Tokenizer/Transformer/TypeColonTransformerTest.php
  tests/Tokenizer/Transformer/TypeIntersectionTransformerTest.php
Labels: kind/cleanup, topic/tests

#8544 chore: add return types for remaining data providers
  phpstan.dist.neon
  tests/Fixer/Casing/NativeFunctionTypeDeclarationCasingFixerTest.php
  tests/Fixer/Casing/NativeTypeDeclarationCasingFixerTest.php
  tests/Fixer/ControlStructure/SwitchCaseSpaceFixerTest.php
  tests/Fixer/ControlStructure/SwitchContinueToBreakFixerTest.php
Labels: kind/cleanup, topic/tests

#8246 feat: add `NewExpressionParenthesesFixer`
  doc/rules/index.rst
  doc/rules/operator/new_expression_parentheses.rst
  src/Fixer/ControlStructure/NoUnneededControlParenthesesFixer.php
  src/Fixer/Operator/NewExpressionParenthesesFixer.php
  src/Fixer/Operator/NewWithParenthesesFixer.php
  tests/AutoReview/FixerFactoryTest.php
  tests/Fixer/Operator/NewExpressionParenthesesFixerTest.php
  tests/Fixtures/Integration/priority/new_with_parentheses,new_expression_parentheses.test
  tests/Fixtures/Integration/priority/no_unneeded_control_parentheses,new_expression_parentheses.test
Labels: kind/feature
