Repository PHP-CS-Fixer/PHP-CS-Fixer, pull requests merged in 2025-01, with the labels that each got.

#8338 docs: `PhpUnitTestCaseStaticMethodCallsFixer` - fix type of `methods` option and add example with it
  doc/rules/php_unit/php_unit_test_case_static_method_calls.rst
  src/Fixer/PhpUnit/PhpUnitTestCaseStaticMethodCallsFixer.php
Labels: topic/documentation

#8326 chore: fix CI for Windows
  composer.json
  tests/Linter/ProcessLinterProcessBuilderTest.php
Labels: topic/ci

#8346 chore: do not use bitwise "or" assignment operator
  dev-tools/phpstan/baseline.php
  src/Fixer/Phpdoc/PhpdocAlignFixer.php
  src/Fixer/Semicolon/MultilineWhitespaceBeforeSemicolonsFixer.php
Labels: kind/cleanup

#8353 chore: remove impossible `@throws` annotation
  dev-tools/phpstan/baseline.php
  src/Fixer/ListNotation/ListSyntaxFixer.php
Labels: kind/cleanup

#8352 chore: simplify loops that are using `end`/`prev` functions
  dev-tools/phpstan/baseline.php
  src/Fixer/ClassNotation/ClassAttributesSeparationFixer.php
  src/Fixer/ClassNotation/NoUnneededFinalMethodFixer.php
Labels: kind/cleanup

#8355 chore: PHPStan - upgrade to 2.1
  dev-tools/composer.json
  dev-tools/composer.lock
Labels: topic/ci

#8357 chore: dependabot integration
  .github/dependabot.yml
Labels: topic/ci

#7844 CI: Introduce PHP compatibility check
  .github/workflows/sca.yml
  .gitignore
  composer.json
  dev-tools/composer.json
  dev-tools/composer.lock
  dev-tools/php-compatibility/phpcs-php-compatibility.xml
  tests/AutoReview/CiConfigurationTest.php
Labels: topic/ci

#8367 fix: `FullyQualifiedStrictTypesFixer` - fix return types
  src/Fixer/Import/FullyQualifiedStrictTypesFixer.php
  tests/Fixer/Import/FullyQualifiedStrictTypesFixerTest.php
Labels: kind/bug

#8019 feat: Add stripos to modernize_strpos rule
  doc/rules/alias/modernize_strpos.rst
  doc/rules/index.rst
  src/Fixer/Alias/ModernizeStrposFixer.php
  src/Fixer/Phpdoc/PhpdocAddMissingParamAnnotationFixer.php
  src/Fixer/Phpdoc/PhpdocSummaryFixer.php
  src/Fixer/Phpdoc/PhpdocVarAnnotationCorrectOrderFixer.php
  tests/Fixer/Alias/ModernizeStrposFixerTest.php
Labels: kind/feature

#8377 deps: bump alpine from 3.18 to 3.21
  Dockerfile
Labels: topic/docker

#8380 refactor: Use native `Yaml::parseFile()` instead of custom method
  tests/AutoReview/CiConfigurationTest.php
Labels: kind/refactoring

#8386 fix: `NativeTypeDeclarationCasingFixer` - fix for promoted properties, enums, `false` and `mixed`
  src/Fixer/Casing/NativeTypeDeclarationCasingFixer.php
  tests/Fixer/Casing/NativeTypeDeclarationCasingFixerTest.php
Labels: kind/bug

#8396 chore: run SCA on PHP 8.4
  .github/workflows/sca.yml
  dev-tools/composer.json
  dev-tools/composer.lock
  dev-tools/phpstan/baseline.php
Labels: topic/ci

#8404 fix: `NativeTypeDeclarationCasingFixer` - do not touch constants named as native types
  src/Fixer/Casing/NativeTypeDeclarationCasingFixer.php
  tests/Fixer/Casing/NativeTypeDeclarationCasingFixerTest.php
Labels: kind/bug
